### ISSUE TITLE
Topic 3: Color Contrast Issue w/Button

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#101]
Location: Topic 3 > Knowledge Check > Question 1
Issue:  When the ‘Redo question’ button is selected, the color contrast ratio of the button text is 3.7:1, which is below the 4.5:1 requirement.  This also occurs when the ‘Check’ and ‘Finish Attempt’ buttons are selected as well.  This is a global issue within the Knowledge Checks.
![Top3_CCA Button (Question 1 - Knowledge Check page)](https://user-images.githubusercontent.com/34749031/59284164-c8b76f00-8c39-11e9-844f-999bcac31337.jpg)

**Comment by KSmithO** [comment]
Someone double check my logic, but I think at the moment they are selected, they are actually disabled because the system is doing something (either generating a new question, checking your answer, finished the attempt, etc). If the button is disabled, then CC would not apply.

**Comment by drewnielson** [comment]
Agreed. Same goes for the "Check" question button. Color contrast is fine before you activate the button. After activating the button, it becomes disabled to prevent the user from activating again. At that moment, color contrast does not apply.

**Comment by HD508Github** [comment]
Correct, when the button is selected, it becomes disabled, then the system re-displays the question.  At this point, the button becomes enabled again.

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D3A09F.E6927B00]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.
