### ISSUE TITLE
Lesson 4: Inconsistent text in Change Notification: Passing Example

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#103]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [X ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Inconsistency in text

## Location
[Change Notification: Passing Examples: Example 1](https://training.section508testing.net/mod/book/view.php?id=1223&chapterid=2653)

## Actual Behavior / Observation
Text at top lists score as Capitals:6 and Predators:2. ANDI lists different scores in the screen capture.

## Expected Behavior / Recommendation
Scores should match

## Steps to Reproduce the Issue (if applicable)
N/A - read chapter

**Comment by drewnielson** [comment]
Thanks @jcarrschwab! The text that was displaying was actually the alt text for a missing image, since the source reference was incorrect. I corrected the source reference, and the image now displays. That should fix the issue.
