### ISSUE TITLE
How long the course might take

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#104]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [x ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
https://training.section508testing.net/mod/book/view.php?id=1221&chapterid=2609
Middle of next to last line on the page.
## Actual Behavior / Observation
 however all you existing certifications 
## Expected Behavior / Recommendation
Change you to your
## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
Thanks @smh243. Fixed.
