### ISSUE TITLE
Example of keyboard trap not functioning as described in training

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#106]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Using Chrome browser.
Observations:
- Keyboard to activate "Browse" button launches Windows Explorer to select file. Instructions say it won't function.
- Training refers to the OK button not receiving focus on the pop-ups for Course Topics and New Folder, but the X button does and the user can press Esc. 
  - I don't see an X to close the pop-up.
  - OK receives focus and works with keyboard.
  - Esc works
- On the main modal dialog box, the OK and Cancel receive focus but are non-functional. 

## Location
[Keyboard Trap: Passing Example](https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2691)

**Comment by drewnielson** [comment]
@AnnMarieDavis , looks like we need to modify the narrative/instructions to align with the actual example - can you take this one? I would suggest working with @jcarrschwab to get a better idea of what she is seeing, i.e., why she doesn't see the X to close the pop-up. Need to also better describe exactly what is and isn't functional in the interactive sample.

**Comment by AnnMarieDavis** [comment]
Topic 4 Lesson 3 (4.C) Passing Example 1: Instructions and screen shot are based on screen shots using IE as the browser. Update the instructions and screen shots so the interactive example more closely meets the user experience; other browsers do not show an x in the modal dialog boxes. https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2691

**Comment by drewnielson** [comment]
@AnnMarieDavis, is this issue resolved?

**Comment by AnnMarieDavis** [comment]
Yes, I have closed it now, since it has now been reviewed. (A note was added to the course indicating the message display may vary depending on the user’s browser.)

Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by AnnMarieDavis** [comment]
Yes. An additional note was added that the visual presentation of the message may vary depending upon the user's browser.
