### ISSUE TITLE
Moodle not marking complete until user refreshs page

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#107]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [x ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
After passing the incremental exam for Auto Playing and Auto Updating content, the check box for completion does not get checked and the next topic is not available. After taking the exam twice, I refreshed the page, and it did check the box. 

## Location
https://training.section508testing.net/course/view.php?id=78
## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
After passing the exam I came back to the course page, expected the Practical exam box to be checked and the next topic to be available.

## Steps to Reproduce the Issue (if applicable)
took exam, mashed exit button, came back to course structure page. check box not checked.

**Comment by Ailikekaus** [comment]
What is a "Moodle"?:
Title: "Moodle not marking..."
![image](https://user-images.githubusercontent.com/19952958/59464249-eb8e8280-8df5-11e9-919c-515b45d63523.png)

**Comment by smh243** [comment]
Moodle is the delivery platform for the course.

Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>
or email the EES Customer Service Center<mailto:EESCSC@va.gov>
[cid:image006.jpg@01D52204.80904610]

**Comment by Ailikekaus** [comment]
Learn new stuff every day...

**Comment by drewnielson** [comment]
Unfortunately, not something we can fix. However, we are adding text to the incremental exam page to instruct students that they will have to refresh the course page to get the activity status to update. See issue #91 for detail and status.

**Comment by drewnielson** [comment]
Also added text under each incremental exam to direct the user to refresh the course page after passing an incremental exam.
