### ISSUE TITLE
Focus: Change of Context Example 2 has no link

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#108]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Paragraph refers to users being able to "click here" to interact with failing example, but there is no active link text. 

## Location
[Focus: Change of Context Failing Example 2(https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2708)]

**Comment by drewnielson** [comment]
Thanks! Not sure what happened to the content. Will investigate further tomorrow morning.

**Comment by drewnielson** [comment]
Fixed. Link added.
