### ISSUE TITLE
Typo - silent vs silence. Lesson 1: Audio Control, Passing & Failing examples 3 

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#110]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [X] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Text in example description and web link in example images contain a probable typo: "Silent" vs "Silence".

## Location
https://training.section508testing.net/mod/book/view.php?id=1223&chapterid=2629

DHSA-TT-200-A
Topic 2: Auto-Playing and Auto-Updating Content
Auto-Playing and Auto-Updating Content
Lesson 1: Audio Control
Passing example Number 3

Additional instances of "Silent" text and in image in Failing example 3
https://training.section508testing.net/mod/book/view.php?id=1223&chapterid=2630

## Actual Behavior / Observation
"Silent audio" is an oxymoron, meaning "soundless audio"; multiple instances on the page. 
"Silent" is an adjective meaning quiet or soundless.

## Expected Behavior / Recommendation
"Silence" is the verb form, meaning "to quiet" or "to stop".
The desired verb is likely "Silence", ie: "Silence audio"

## Steps to Reproduce the Issue (if applicable)
Simply display the page and read the text carefully.

**Comment by Ailikekaus** [comment]
![TTv5_SilentTypo_20190613](https://user-images.githubusercontent.com/19952958/59464303-0eb93200-8df6-11e9-8fd9-2f162c00b62b.png)

**Comment by drewnielson** [comment]
Thanks! Good points.

**Comment by drewnielson** [comment]
Fixed
