### ISSUE TITLE
Mousing over interactive components

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#113]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [x ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Chrome/Win 10. Launched page.
 It opened in a new tab, not a new window.
Mousing over either button did not reveal they are interactive elements.

## Location

https://dev.section508testing.net/html/4B_Fail3.html
Lesson 2: Keystroke Timing
Failing examples
Example 3

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
Whether a page opens in a new window or new tab depends on your browser settings. We can modify text to indicate "opens in a new window/tab" instead of "opens in a new window," but again, that is a browser preference setting. 

I'm confused by the comment, "Mousing over either button did not reveal they are interactive elements." What behavior would you expect to see when you hover over the buttons, and why would you expect that behavior?

**Comment by smh243** [comment]
I expected the mouse pointer to change from an arrow to something like a hand to indicate that there is a component on the page that can be interacted with, or the button to change to indicate it was an interactive component.
Thanks,
Mark

Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>
or email the EES Customer Service Center<mailto:EESCSC@va.gov>
[cid:image006.jpg@01D525A8.4A9E4F00]

**Comment by drewnielson** [comment]
Added finger pointer cursor for buttons just make it clearer the buttons are interactive.
