### ISSUE TITLE
ATT200A pilot feedback Allen Hoffman #2-2.A : https://training.section508testing.net/mod/book/view.php?id=1223&chapterid=2623

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#114]
On page:
https://training.section508testing.net/mod/book/view.php?id=1223&chapterid=2623
Text says:
if audio content plays automatically for more than 3 seconds, there is a mechanism within the first three elements encountered for the user to pause or stop the audio or control the volume of the content.

Change to:
if audio content plays automatically for more than 3 seconds, there is a mechanism within the first three interactive elements encountered for the user to pause or stop the audio or control the volume of the content.

Rationale:
Added interactive to clearly identify that first three elements must be interactive.  I don’t think counting images for example would correctly test this.

**Comment by drewnielson** [comment]
Added question with the following response/answer to the FAQ Wiki:

**Answer**
Mechanism is specifically defined to include any element, including text or images. For example, text could be an effective element to provide a keyboard shortcut, which could function to pause or stop the audio or control the volume of the audio content.
