### ISSUE TITLE
Issue: Instructions not clear on how to report failure for illogical focus

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#118]
From: CarrSchwab, Joyce (CTR) <Joyce.CarrSchwab@associates.ice.dhs.gov> 
Sent: Thursday, June 13, 2019 3:17 PM
To: Accessibility <Accessibility@HQ.DHS.GOV>
Subject: Section 508 Training Pilot: Incremental Exam Question

Good afternoon,

I think I’m identifying the issues correctly, however I think I’m not getting credit on the exam because of how I record the issues. 

For example, if a page fails due to the sequence of focus/illogical order of fields, do you note the field before or after the issue.

State, City in an address – the focus moves correctly, but we generally list City first
State focus moves to a field earlier in sequence – is State reported or Contact Name

Please include these in the questions for Tuesday afternoon’s session. 

Thanks,
Joyce

Joyce N. Carr Schwab, PMP, CSM
Dev Technology Group, Inc.
900 7th Street NW
6th Floor
Washington, DC 20001

Joyce.CarrSchwab@associates.ice.dhs.gov
www.devtechnology.com
Direct: 703-657-7455
Mobile: 703-675-9749

**Comment by KSmithO** [comment]
I *think* Cliff was working on language-was it submitted to Carney?

**Comment by drewnielson** [comment]
Subsumed by issue #205. Closing this issue now as duplicate.
