### ISSUE TITLE
ANDI Install 

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#119]
Good Morning, 

I am enrolled in the Trusted Tester Web course for 508 compliance testing and I attempted to get ANDI installed on my favorites bar. I was using IE but I keep getting an error message when I attempt to add it to my browsers favorites bar. 

 

Do I need to do update my browser settings or something? Any advice or assistance would be greatly appreciated. Thank you! 

Megan Furman 
Training Specialist, Resources & Support  
VCS Central Office, St. Louis, MO
314-845-1468 ph

**Comment by normanbrobinson** [comment]
What error was displayed?

**Comment by drewnielson** [comment]
@normanbrobinson, I'll work with Megan directly. I don't think the issue actually belongs here, since it doesn't relate directly to the Trusted Tester training content. Sounds more like the person might just need a couple pointers to resolve the issue.

**Comment by drewnielson** [comment]
Issue resolved.
