### ISSUE TITLE
Lesson 3

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#120]
reported by manzoor Murshed 

![image](https://user-images.githubusercontent.com/51798183/59534093-4f2eb380-8ebb-11e9-8e38-7ee0b163de41.png)

**Comment by drewnielson** [comment]
Definitely need to fix, and this means we need to update both the Word and PDF versions.

**Comment by AnnMarieDavis** [comment]
Kristen has made these changes on the 5.0 version and it is ready to be substituted in the course.  I also made the change to the new 5.1 draft.
