### ISSUE TITLE
 Textual Error  

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#121]
Reported by Manzoor 
Murshed
The same textual error is seen in all 3 Passing Examples and 3 Failing Examples under Lesson 3: Auto-updating.
It looks like the error is sourced from page 16 of the Trusted Tester Section 508 Conformance Test Process for Web 
document. It should be corrected in the document as well. Here the topic is about Auto-updating – not moving/blinking/scrolling.

**Comment by drewnielson** [comment]
Related to Issue #120

**Comment by KSmithO** [comment]
Corrected
