### ISSUE TITLE
Test ID 1.E needs to be added to Practice and Final exam "enter results"

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#122]
Test ID 1.E is not listed for results for both Practice and Final exam:

![image](https://user-images.githubusercontent.com/34742733/59608720-fd1ca680-90e3-11e9-8d3a-65f138ae347d.png)

Test Name: non-interference
Test ID: 1.E
Test Condition: Content in the non-conforming version(s) meet Conformance Requirement 5.

**Comment by cliffbert** [comment]
All the 1's were DNA in the exams, but we do need to add 1.E to all answer pages

**Comment by drewnielson** [comment]
I'm less sure about this one, but I think this was already on Carney's list of fixes, based on our changes.

**Comment by Tonylayton1** [comment]
This is on our radar, but it does not affect the incremental exams as there is no topic 1.

**Comment by mikebarklage** [comment]
I have added 1.E along with the new 5.A on Dev.

**Comment by AnnMarieDavis** [comment]
I verified that both 1.A and 1.E were added to the test results page.  

Still needed is to REMOVE the FAIL column on the answer sheet. This Topic is a little different than ALL the others.  **There should be only a column for DNA or Pass.**  In this case if the Test condition is a FAIL, then the result is DNA - there is not a compliant version.

So check that (1) all correct answers are DNA and that (2) the FAIL column is removed from the test answer sheet.

**Comment by AnnMarieDavis** [comment]
Consulted with Andrew and the Test Results for Topic 1 should not be provided at all to students.  Remove this from the pages presented on the Practice and Final exam. **Replace the "Enter Results" button with "Omitted from Exam" text.**  (much like the text you have for 3 Flashing and 20 Parsing, but do not use "not tested")

**Comment by drewnielson** [comment]
Before taking action on above comment, let's discuss during our meeting later today (7/11).

**Comment by AnnMarieDavis** [comment]
Request is to hide the radio button from FAIL column for 1.A - 1.D.  It should only be presented for 1.E

**Comment by mikebarklage** [comment]
But 1.A - 1.E are always DNA? (Assuming we've ensured something else on the exam fails.)

**Comment by drewnielson** [comment]
Yep, assuming something else always fails, then 1.A-1.E would be DNA.

**Comment by mikebarklage** [comment]
I just thought of a possible if unlikely edge case:

Student fails attempt 1
On one of the 3 pages, the only incorrect responses were in topic 1
Attempt 2 randomizes topic 1 for that page, with no options for other failed IDs

**Comment by drewnielson** [comment]
ugh - yeah, that could be a problem

**Comment by cliffbert** [comment]
Is it too much trouble to test them on 1.A-E with a multiple choice question instead?

**Comment by mikebarklage** [comment]
Given the above, it's probably best to just skip Topic 1 on the practice/final exams, same as 3 and 20.

**Comment by drewnielson** [comment]
Yeah, I tend to agree. I'll discuss with Nic and others and will confirm one way or another.

**Comment by AnnMarieDavis** [comment]
The agreed fix that should be implemented for this issue is:
A Test Results answer sheet for Topic 1 should **not** be provided to students on the Practice or Final exams. Replace the "Enter Results" button with the text "Omitted from Exam". (This should be _styled_ like the "Not tested" text for 3 Flashing and 20 Parsing)

**Comment by mikebarklage** [comment]
I removed Topic 1 from the Practice and Final exams, as far as I can tell so far. If you encounter any issues with it, please follow up here.

**Comment by mikebarklage** [comment]
Also note that I haven't changed anything on the admin side yet and I'm not sure if anything needs to be updated.

**Comment by Tonylayton1** [comment]
Verified that topic 1 has been removed and scoring appears to be correct.

On the admin instructor view side, it still highlights the topic 1 group as yellow. I would expect it to be white like topic 3.

**Comment by mikebarklage** [comment]
I've adjusted the admin view for topic 1.

**Comment by Tonylayton1** [comment]
Verified on Dev (note: this requires an exam status reset and the browser cache to be cleared to verify)

**Comment by AnnMarieDavis** [comment]
OBE - students should not be presented with an answer sheet for Topic 1. We have since decided to replace the Enter Results button and accompanying answer sheet with a "bye" statement. Students will not test Topic 1 on the practice and final exam.
