### ISSUE TITLE
Test IDs listed incorrectly when in Final Cert Exam

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#124]
If you miss Test IDs, the test ID numbers are incorrect within the Final exam:

![image](https://user-images.githubusercontent.com/34742733/59613653-458c9200-90ed-11e9-8d9d-686ec4cd12ba.png)

**Comment by drewnielson** [comment]
I believe this is already on Carney's list of fixes, based on our changes.
