### ISSUE TITLE
Update test name for Topic 5, SC 1.3.1 in results for Incremental, Practice and Final

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#125]
Several of the form test names were changed recently (this is in addition to the creation of an additional test condition). Below is the additional change (not sure if this was previously recorded):

1) Old Test Name: 1.3.1-form-labels-cues. New Test name: 1.3.1-programmatic-label

![image](https://user-images.githubusercontent.com/34742733/59621182-bbe4c080-90fc-11e9-8746-c302286ac1bd.png)

**Comment by drewnielson** [comment]
I believe this is already on Carney's list of fixes, based on our changes

**Comment by Tonylayton1** [comment]
will be addressed by #55 when new ID is added to topic 5.

**Comment by drewnielson** [comment]
Closing this issue since it is a duplicate among issues covered under #55
