### ISSUE TITLE
Topic 15: ALT Description requires more information

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#13]
Within Topic 15 > Lesson 2: Lesson 2: Content Order and Meaning (CSS position) > How to test page, the ALT description needs to include that the 'Advanced Settings' menu is displayed with 'Elements Highlights' and Linearize Page' selected.
![Top15_ALT Desc (Lesson2-How to Test page)](https://user-images.githubusercontent.com/34749031/58200500-e92a8400-7ca0-11e9-82e0-17654d27db1a.jpg)

**Comment by drewnielson** [comment]
Fixed. @vprentice please verify.

**Comment by drewnielson** [comment]
Sorry, meant to say @HD508Github please verify fix.

**Comment by HD508Github** [comment]
ALT description was re-tested and the issue has been resolved.
![Corrected_Top15_ALT Desc (Lesson2-How to Test page)](https://user-images.githubusercontent.com/34749031/58266608-04a09800-7d50-11e9-822c-8f5f4065f6ae.jpg)

**Comment by drewnielson** [comment]
re-test closes #13
