### ISSUE TITLE
Answer for 13 A. 1.4.1 - may not be correct

### ISSUE THREAD

**Issue by cdizon5** [Section508Coordinators/DHSA-TT-200-A#130]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Testing for color-meaning.  Page shows a chart that uses color to convey meaning (blue = workbalance, brown = lifecheck). 

## Location
Incremental exam for topic 13 Sensory Characteristics and Contrast

## Actual Behavior / Observation
1.4.1 Answer needed = Pass

## Expected Behavior / Recommendation
1.4.1 Recommended answer = Fail.
Color is the sole method to convey meaning in the chart.  

## Steps to Reproduce the Issue (if applicable)
Incremental exam for topic 13 Sensory Characteristics and Contrast. Test the page.  Chart should appear.  Answered needed to complete the topic incremental = pass.  Recommend reviewing as I believe answer should be fail.

[13 1.4.1.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3298243/13.1.4.1.docx)

**Comment by drewnielson** [comment]
@cdizon5, good thinking in general. If we were limiting our test to the graph alone, then you would be right. However, there are a couple pieces of other information on the web page that would lead us to give it a pass for 13.A, 1.4.1-color-meaning:
1. The text just above the graph gives us a hint that the line in the graph with the steeper slope belongs to "Workbalance." This could maybe squeeze by the test, but still feels a little shaky; therefore, see the next item.
2. The text below the graph describes in detail the same information that is presented in the graph. That detailed text means that a user does not have to rely on the color in the graph (or the graph at all) to obtain the same information.

Feel free to give me a call if you want. I'd be happy to chat through it further, if necessary. Closing the issue for now, but feel free to comment again if you still think there is something fishy going on.
