### ISSUE TITLE
Topics are not listed in Sequential order

### ISSUE THREAD

**Issue by CLAMBne508** [Section508Coordinators/DHSA-TT-200-A#131]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [X ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
"Topic 1: Conforming Alternate Version and Non-Interference" is listed after Topic 20.

## Location
https://training.section508testing.net/course/view.php?id=78, Course Home Screen.

## Actual Behavior / Observation
When looking through the Topics on the course home page I noticed that Topic 1 is not located as the first Topic the user is trained on.  Instead it is Topic 2.  As I scrolled through the list of Topics I found it after Topic 20.

## Expected Behavior / Recommendation
I would expect the Topics to be listed 1-20.

## Steps to Reproduce the Issue (if applicable)
Login to training site.
Select DHSA TT 200 A and enter training.  
Scroll through list of topics.
![Topic order](https://user-images.githubusercontent.com/51926667/59626515-16384e00-910a-11e9-817c-199cda3828d6.png)

**Comment by drewnielson** [comment]
@CLAMBne508, this is intentional, though obviously could be confusing for some. We attempted to address by adding language in the Introduction and directly under Topic 2 and Topic 1 on the course main page. Do you have another suggestion for how to more clearly convey that?

**Comment by CLAMBne508** [comment]
I didn't even realize that text was there until you mentioned it.  Maybe making part of the text Bold to draw a user's eye to it.  But otherwise it's probably done the best it can be.

**Comment by drewnielson** [comment]
OK. Added some bold to the text on the main course page. Closing the issue for now, but if any other ideas/recommendations occur to you, feel free to comment again.
