### ISSUE TITLE
Incorrect sections listed in incremental exam results

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#133]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [X ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The sections (5.x) don't match the text in the test results, which is confusing to the student about what the problems are. 

## Location
http://3.217.25.10/dhsv5/scormapi/lesson1.php?SCOInstanceID=195&studentName=Joyce%20CarrSchwab&ltiUserId=4413&studentEmail=joyce.carrschwab@associates.ice.dhs.gov&examId=5
Section 5 Incremental Exam
![IncorrectSectionsDon'tMatch](https://user-images.githubusercontent.com/51755970/59631264-65d04700-9115-11e9-9525-6a453c596df3.PNG)

**Comment by drewnielson** [comment]
Apologies @jcarrschwab. This was noted in our [Known Issues](https://github.com/Section508Coordinators/DHSA-TT-200-A/wiki/Known-Issues), but still admittedly confusing. If you are stuck and can't get past the incremental, give me a call or reach out to the Accessibility Helpdesk (202-447-0440; accessibility@hq.dhs.gov), and I'll make sure you get past it.

**Comment by Tonylayton1** [comment]
Unsure what issue is being described. Could someone supply more information on this one?

**Comment by AnnMarieDavis** [comment]
This is related to issue #55.  If you fix that, you will fix both issues.  The test IDs in the incremental do not line up to the change made in the course for test ID in section 5.
