### ISSUE TITLE
Typo/grammar: revel vs reveal

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#135]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Typo/grammar: revel vs reveal

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2676
Topic 4: Keyboard Access and Focus
Keyboard Access and Focus
Lesson 1: Keyboard Access
Failing examples
Example 4
2a explanation

## Actual Behavior / Observation
Explanation text contains "revel" vice "reveal" (emphasis added):
"You are using Firefox for your testing, and it does not **_revel_** title attributes."
	revel - verb to rejoice, party, or celebrate
	reveal - verb to expose, disclose, or divulge

## Expected Behavior / Recommendation
"You are using Firefox for your testing, and it does not **_reveal_** title attributes."

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
Fixed
