### ISSUE TITLE
Possible issue with Incremental for Links/Buttons (6B)

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#136]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Incremental exam for Links/Buttons (Section 6) is not passing.

I realize that the test page changes with each retake, but I can't get 6B to pass with any combination of obvious DNA, Pass, or Fail. Is there an issue with this exam?

## Location
http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=joyce.carrschwab@associates.ice.dhs.gov&SCOInstanceID=200&examId=6

**Comment by drewnielson** [comment]
@jcarrschwab , let's walk through this together. Could you reach out to Doug at the Accessibility Heldesk (accessibility@hq.dhs.gov; 202-447-0440) to schedule a 1 on 1 session with me?

**Comment by drewnielson** [comment]
Question/issue resolved via phone conversation.
