### ISSUE TITLE
Content Addition Suggestion 4.B Passing Example 1

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#137]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x] Other, specify... Content Suggestion

## Description
Content Suggestion: add text to 4.B Passing Example 1.

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2683
Topic 4: Keyboard Access and Focus
Lesson 2: Keystroke Timing
Passing examples
Example 1

## Actual Behavior / Observation

Regarding the Example text: 
>>"Alternatively, users can select the question type, then hold down Ctrl + arrow keys to drag the question to the survey palette."

I thought "drag" referenced a mouse action and wasn't sure what this function was or how it was supposed to work until I read the text contained in parenthesis in the explanation section:
>>"(holding both keys down until the question type moves into the palette)"

The explanation is good because that is where I came to understand this is a "timing" issue:
>>"Holding the Ctrl + arrow keys to drag the question to the palette DOES require specific timing of the keystroke (holding both keys down until the question type moves into the palette)."

## Expected Behavior / Recommendation
Suggest adding quotation marks to "drag" and adding text "by holding both keys down until the question type moves into the palette" into the Example text (emphasis added):
>>"A web page allows users to create a simple web survey. The survey can be created with questions allowing multiple answers (using checkboxes) or questions only allowing one answer (using radio buttons). Instructions to add a question to the survey allow users to drag and drop the type of question desired from the menu to the survey palette. **_Alternatively, users can select the question type, then hold down Ctrl + arrow keys to "drag" the question to the survey palette by holding both keys down until the question type moves into the palette_**. A final option allows users to select the question type, then press Ctrl + C and then Ctrl + P to add the question to the palette. Let’s look at the test results of each test step for this page."

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
Good suggestion. Thanks. Implemented as suggested.
