### ISSUE TITLE
Possible Typo: "tab to the button, tab to the button," 4.B

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#138]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Possible Typo: "tab to the button, tab to the button,"

## Location
https://dev.section508testing.net/html/4B_Fail3.html
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2683
Topic 4: Keyboard Access and Focus
Lesson 2: Keystroke Timing
Failing examples
Example 3

## Actual Behavior / Observation
Possible Typo: "tab to the button," repeated twice in image and test page (https://dev.section508testing.net/html/4B_Fail3.html).
![image](https://user-images.githubusercontent.com/19952958/59640681-d6369280-912c-11e9-9378-7cda8b09ceb7.png)

## Expected Behavior / Recommendation
Review to determine which is correct:
>>To change the button from **Request Password Reset** to **Request User Name**, tab to the button, tab to the button, press and hold the space bar for 3 seconds, and release the spacebar. 
Repeat the steps to change it back again.

OR
>>To change the button from **Request Password Reset** to **Request User Name**, tab to the button, press and hold the space bar for 3 seconds, and release the spacebar. 
Repeat the steps to change it back again.

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
Thanks. Fixed.
