### ISSUE TITLE
Incremental Exam Topic 2

### ISSUE THREAD

**Issue by knpmartin** [Section508Coordinators/DHSA-TT-200-A#139]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The Course Introduction states that the incremental exam can be taken as many times necessary to obtain a passing score. However, the incremental exam for Topic 2 states there are only 3 attempts:
![image](https://user-images.githubusercontent.com/51921606/59678913-95c22d80-919b-11e9-9bd2-df20fc43f488.png)

## Location
Topic 2: Auto-Playing and Auto-Updating Content; submit answers page after failing attempt
http://3.217.25.10/dhsv5/scormapi/lesson1.php

## Actual Behavior / Observation
Unable to verify actual behavior. I attempted to fail the test 3 times, but wound up passing 2nd attempt.

**Comment by drewnielson** [comment]
@knpmartin, sorry for the confusion. The language for the instructions in the actual exam pages is under revision. Those changes just haven't been pushed to the production server yet.

**Comment by Tonylayton1** [comment]
We identified this issue on our end while doing the other text changes. is the following text okay? It no longer says "certification", and the final line about attempt limits is removed.

"You have tested all pages of this incremental exam topic and recorded your results.

You may return to previous screens to check over and modify your answers if you wish. When you are satisfied with your testing results, select Submit My Answers to receive your incremental exam score."

**Comment by drewnielson** [comment]
Verified in dev
