### ISSUE TITLE
Topic 15: Color Contrast Issue for iFrame Content

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#14]
Within Topic 15 > Lesson 2: Lesson 2: CSS Content and Positioning > Lesson 2: Content Order and Meaning (CSS position) > Passing examples page, the iFrame text for 'Example 1 - Interactive Sample' (Products and Locations) have a color contrast ratio (4.0:1) that is less than 4.5:1.
![Top15_Color Contrast iFrame Text (Lesson2 - Passing Examples page)](https://user-images.githubusercontent.com/34749031/58202516-c8186200-7ca5-11e9-96b6-99f2e48a0a26.jpg)

**Comment by drewnielson** [comment]
Fixed. @vprentice , you may need to refresh the cache for the page when you verify the fix (ctrl + F5). Please verify when you have a chance.

**Comment by vprentice** [comment]
Thanks I will check it out to see!

**Comment by drewnielson** [comment]
Sorry, meant to say @HD508Github please verify.

**Comment by HD508Github** [comment]
Re-tested the text within the iFrame and the issue has been resolved.
![Corrected_Top15_Color Contrast iFrame Text (Lesson2 - Passing Examples page)](https://user-images.githubusercontent.com/34749031/58267730-331f7280-7d52-11e9-9a06-15c6da150c16.jpg)

**Comment by drewnielson** [comment]
It looks like CCA and ANDI might be providing slightly different results. If you use the ANDI tool that is built into the iframe, pretty sure the ratio is at 4.5:1. Must be a rounding issue. Either way, this should close #14.
