### ISSUE TITLE
TTv5 Q&A: Headings required

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#140]
Location: Dashboard
Issue: Headings are required for the 'Tuesday Session Topics' and 'Thursday Session Topics' sections.
![Session Topics Headings (Dashboard page)](https://user-images.githubusercontent.com/34749031/59683314-f3f40e00-91a5-11e9-80ad-e2a9cf5ee648.jpg)

**Comment by drewnielson** [comment]
Not sure I totally agree that they have to be headings, but added them anyway. @HD508Github please re-test.

**Comment by HD508Github** [comment]
Issue re-tested and the correction has been made.

![Session Topics Headings_Corrected (Dashboard page)](https://user-images.githubusercontent.com/34749031/59765559-5283bf80-926c-11e9-9397-360061e83719.jpg)
