### ISSUE TITLE
TTv5 Q&A: Reading Order Issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#141]
Location: Dashboard
Issue:  During keyboard navigation under the 'Tuesday Session Topics' section, the reading order is illogical between the last 'Trusted Tester Q&A - Tuesday Webinar' session and the 'Sign-up for an available upcoming sessions' section.  The same issue exist under the 'Thursday Session Topics' section.

![Reading Order - Session Topics (Dashboard page)](https://user-images.githubusercontent.com/34749031/59684767-b0e76a00-91a8-11e9-99ac-dad27f94dd27.jpg)

**Comment by drewnielson** [comment]
Removed the activity completion checkboxes. @HD508Github please re-test.

**Comment by AnnMarieDavis** [comment]
Tested and passes reading order.
