### ISSUE TITLE
Possible incorrect content 4.F "four" keyboard-accessible interface components

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#143]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [x] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Possible incorrect content

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2715
https://dev.section508testing.net/html/4F_Pass1.html
Lesson 6: Focus (Order)
4.F 2.4.3-focus-order-meaning
Passing examples
Example 1

## Actual Behavior / Observation
Example explanation states there are "four" keyboard-accessible interface components, but there are 3 Sections containing a total of 12 components (2 different types: text boxes and check boxes).  Not sure what "four" references (emphasis added):

>>This PASSES for 2.4.3-focus-order-meaning because each of the **_four_** keyboard-accessible interface components are in a focus order that preserves both the meaning and operability of the web page.
![image](https://user-images.githubusercontent.com/19952958/59689900-78e32580-91ae-11e9-8e1e-7866fec05554.png)

## Expected Behavior / Recommendation
Seeking clarification

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
Just removed "four" from the sentence. Corrects the statement, so the reference no indicates that all of the interactive interface components are in a logical focus order.
