### ISSUE TITLE
ANDI

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#144]
I've recently been enrolled in the pilot version of a brand new TT5 course. I think I'm supposed to give feedback to someone when I find something confusing (or potentially wrong).

I've found a problem in the first quiz

My location is here: https://training.section508testing.net/mod/quiz/attempt.php?attempt=26447 • Tool Installation o Introduction to Trusted Tester Tools  Tool Installation: ANDI The first quiz question asks:

Locate the two element navigation arrows under the word “ANDI.” Select the right arrow (“Inspect Next Element”) until the “Homeland Security” area of the banner is outlined in pink, as shown below. You may use the mouse or the TAB key to advance the key.

What text is shown in the ANDI Output section of the ANDI window?

Select one: ( )a. DHS Seal ( )b. Home ( )c. DHS Logo ( )d. Homeland Security

I know how to use ANDI, but I'm confused. Am I supposed to be using ANDI to inspect next element on the quiz page itself? Or am I supposed to be on a different URL to test? The question doesn't even tell me what module to pick in ANDI. By default, ANDI started on "focusable elements"...but I think the question needs to clarify exactly what we should do.

I'm guessing that the question assumes I know to go to this web page https://www.dhs.gov/ to answer this question...but it doesn't say that anywhere. Even when I go to that dhs.gov page and run ANDI and navigate to the seal...the text in the ANDI Output section says "U.S. Department of Homeland Security Seal" (and that is not one of the available multiple choice answers in the quiz.

Screenshot of Quiz Question:

Screenshot of me guessing that I should answer this question while using ANDI on the dhs.gov home page.

Can you help me figure out what to do? As a pilot participant...do I need to assume the quiz questions are not really ready? If so...how do I handle getting past this quiz questions?

Thanks so much, Glenda glenda sims, cpwa | team a11y lead | 512.963.3773

    deque systems  accessibility for good

**Comment by drewnielson** [comment]
@douglaszak, this issue is related to the Tools course, not the Trusted Tester course itself. I still don't want to lose track of it, but could you forward the email to Tonya and Nic specifically (and copy me, Ann Marie, Cliff, and Brandon)?

**Comment by douglaszak** [comment]
@drewnielson sent to tonya and Nic

**Comment by AnnMarieDavis** [comment]
Cliff has clarified the instructional text. It now states:
If you haven't already opened the test page, click here to open it, then launch the ANDI tool.
Locate the two element navigation arrows under the word “ANDI.” Select the right arrow (“Inspect Next Element”) until the “Homeland Security” area of the banner is outlined in pink, as shown below. You may use the mouse or the TAB key to advance the key.

Example 2 instructions state: 
Locate the two element navigation arrows under the word “ANDI.” Select the right arrow (“Inspect Next Element”) until the “National Threat Advisory” area of the banner is outlined in pink, as shown below. You may use the mouse or the TAB key to advance the key.
