### ISSUE TITLE
Focus Order 4.F - User can navigate away from demo page modal dialog box

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#145]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [x] 508 issue (something "extra" is accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Passing Example 2 states (emphasis added):
>>This PASSES for 2.4.3-focus-order-meaning because the **_visible focus stayed within the modal dialog box_** and was in logical order, preserving both the meaning and operability of the web page.

However, the user is able to navigate away from the demo page modal dialog box while it is still open.

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2715
https://dev.section508testing.net/html/4F_Pass2.html
Lesson 6: Focus (Order)
4.F 2.4.3-focus-order-meaning
Passing examples
Example 2 demo page

## Actual Behavior / Observation
Tested and observed in the following browsers: Chrome, Firefox, IE, and Edge.
After opening and subsequently closing the Windows "open file" modal dialog box, the user is able to navigate outside the demo page "Upload File Details" modal dialog box.
![image](https://user-images.githubusercontent.com/19952958/59693185-7f749b80-91b4-11e9-8c73-cfaa36b9fde8.png)

## Expected Behavior / Recommendation
"Focus needs to stay in the box until the information is complete. Users should not be able to navigate away from the modal dialog box while it is still open."

## Steps to Reproduce the Issue
1. Open the demo page: https://dev.section508testing.net/html/4F_Pass2.html
2. Select the "Upload File Details" button.
3. When the modal window opens, select the "Choose File" button to open the Windows "open file" modal dialog box.
4. When the Windows "open file" modal dialog box opens, either select a file to open or cancel the action (Open or Cancel buttons) which will close the Windows "open file" modal dialog box and return the user to the demo page.
5. Navigate on the demo page using the keyboard only - the user is able to navigate away from the modal dialog box to the browser chrome controls and back to the modal dialog box.
6. Subsequently closing and opening the demo modal dialog box does not restore proper keyboard navigation controls - the user is able to navigate outside any subsequently opened modal dialog boxes.
7. Proper modal navigation functionality can be restored by refreshing the demo page.

**Comment by drewnielson** [comment]
Hmmm - I'll need to look into this a little more. I'm not sure it is possible to prevent a user from being able to return to the address bar or from being able to refresh the webpage with a modal dialog.

**Comment by Ailikekaus** [comment]
yeah, this might be a case where devs can't prevent, but the user should be able to tell where they are based on URI info.  They are still in a captive loop, just a bit bigger loop, that can only be closed by the dialog box close functions.

**Comment by AnnMarieDavis** [comment]
Retested the results of using the keyboard TAB through the dialog in Chrome, Firefox and Edge.  Focus remains in the dialog box as intended (using the TAB key), although there was a loss of focus in Firefox on the New Folder button.

The example is not intended to show refresh behavior. 

No further action or course modification is recommended at this time.
