### ISSUE TITLE
Practice and Final Exam scoring issue for 17.E and 17.F-needs a double check and possible inquiry in to results

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#146]
SCO ID: 109, Student Data:  Web Practice | submitted 2019-06-18 15:01:52
Page 1, results for 17.E and 17.F may be wrong.

Below is media player:
![image](https://user-images.githubusercontent.com/34742733/59696515-227be400-91ba-11e9-9019-d5d907b70d59.png)

results are telling me 17.E and 17.F should be C but there is no volume adjustment nor program selection, so these should be DNA
![image](https://user-images.githubusercontent.com/34742733/59696568-40e1df80-91ba-11e9-9692-bc46ef545080.png)

**Comment by KSmithO** [comment]
This is also an issue in the Final Exam, Web page: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-final/testPages/signup.php?KeyID=1313

**Comment by AnnMarieDavis** [comment]
The answer sheet appears to have been changed for the Incremental. Expected result was DNA in dev moonami site.
