### ISSUE TITLE
Practice Exam scoring issue for Multiple Ways

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#147]
SCO ID: 109, Student Data:  Web Practice | submitted 2019-06-18 15:01:52, pages 1-3, web page: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=1305 

I believe there is only one way to reach different pages, via the links in the header (and the exact same links are provided in the footer). There are no other options, such a search, site menu, other menu, etc. It was my understanding that two DIFFERENT techniques need to be provided, not just the same link shown twice. When I select NC b/c the only technique is the link in header/footer, I get the answer wrong. Double check my logic/sanity on this one.

![image](https://user-images.githubusercontent.com/34742733/59697017-1e9c9180-91bb-11e9-801e-f3dc71bd4028.png)

![image](https://user-images.githubusercontent.com/34742733/59697113-48ee4f00-91bb-11e9-979d-68416e232997.png)

**Comment by AnnMarieDavis** [comment]
Yes, there must be 2 different ways locate a page withing a set of web pages.  Providing the menu at both the top and the bottom of the page are not 2 different ways to locate a page. 

A change is needed on the answer key.

**Comment by drewnielson** [comment]
Added the exam-final label, assuming we likely have the same issue there. Remove if not the case.

**Comment by Tonylayton1** [comment]
this issue in the practice is covered in #271 so I removed the practice label from this issue.

**Comment by AnnMarieDavis** [comment]
Issue fixed in Practice Exam
