### ISSUE TITLE
Slightly confusing result for 13.A (Practice Exam)

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#148]
There are two instances where color is used to convey meaning: 
1) in the text explaining what the colors mean
2) in the table where the color is used

The answer key only has the text in the table as a correct result. If you select the text in the key, you will get it wrong. I think it is arguable that the key text is also conveying information, which is then being implemented in the table. I suspect people will answer this incorrectly (easy enough for them to go back and re-take it) but we may be delivering the wrong message?

Item from page:
![image](https://user-images.githubusercontent.com/34742733/59700177-d54f4080-91c0-11e9-9d7e-380a62d8be9e.png)

Answer key:
![image](https://user-images.githubusercontent.com/34742733/59700158-cb2d4200-91c0-11e9-9bb8-87b3b5f67617.png)

Was using SCO ID :109, Web practice iteration line 2, Data and Security page

**Comment by drewnielson** [comment]
Hmmm, I don't think the text in the legend/key really is color dependent. In other words, I don't need the color there to understanding the meaning that the text is conveying. The color helps make the connection visually, but I don't need the color in the key to understand the message that "Green indicates secure, red indicates unsecure." Therefore they text in the key is not color-dependent. However, without the color in the table itself, I can't tell which ones are secure and which ones are unsecure. So in the end, I think I agree with the current scoring.

**Comment by KSmithO** [comment]
Fair enough!
