### ISSUE TITLE
Topic 15: ALT Description requires modification

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#15]
Within Topic 15 > Lesson 2: Content Order and Meaning (CSS position) > Failing examples page, the ALT description for Example 2's image should read "Shipping Information..." instead of "Shipping Address...".
![Top15_ALT Desc for Example 2(Lesson2-Failing Examples page)](https://user-images.githubusercontent.com/34749031/58277513-e2b30f80-7d67-11e9-96fb-73e6d14db716.jpg)

**Comment by drewnielson** [comment]
Fixed. @HD508Github please verify.

**Comment by HD508Github** [comment]
Re-tested and the issue is fixed.
![Corrected_Top15_ALT Desc for Example 2(Lesson2-Failing Examples page)](https://user-images.githubusercontent.com/34749031/58341228-bfe23300-7e1b-11e9-895d-011a8f596f14.jpg)

**Comment by HD508Github** [comment]
Re-tested and issue is resolved.

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D4D4A9.1E4A3BD0]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.
