### ISSUE TITLE
Unclear/Confusing content, Failing Example 1, 4.H 

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#150]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [x] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Unclear/Confusing content (2 Issues):
1. Example text doesn't contain any indication the user closes revealed content.
2.  Example text states the focus moves to the "Site Links" link while the Evaluation text states focus moves to "Home" button.

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2732
Lesson 8: Focus (Order Return)
4.H 2.4.3-focus-order-return
Failing examples
Example 1

## Actual Behavior / Observation
**Issue 1**
Example 1 text states:
>> "An agency’s website lists Freedom of Information Act (FOIA) exemptions and examples. With the Tab key, you land on an expand/collapse button; pressing the Enter key reveals content hidden under the menu. Below is the revealed content for “Exemptions.”

There is an accompanying image to the above text with the ALT of:
>> "Collapse button shown to collapse revealed content under the "Exemptions" heading."

Subsequent text and accompanying image indicates the focus has moved:
>> "Advancing one keystroke (a Tab or arrow key) moves the focus to “Site Links” in the navigational breadcrumbs menu."

* However, there is no text indicating action was actually taken by the user to collapse the revealed content and the state of the visible focus at that point.

**Issue 2**
The Example text states (emphasis added):
>> "Advancing one keystroke (a Tab or arrow key) moves the focus to _**“Site Links”**_ in the navigational breadcrumbs menu."

The image ALT states (emphasis added):
>> Keyboard focus moves to the element next to _**"Home."**_ Home is the _**"Site Links"**_.

The Evaluation text states condition 1 is false, that the focus "automatically appears on the **“Home”** button" (emphasis added):
>> If any of following is TRUE, then the content PASSES:
>>1.	Keyboard focus automatically returns to the logical sequence of focus order before the content was revealed.
This is FALSE. Keyboard focus automatically appears on the _**“Home”**_ button, which is in a different section of the web page. This is not a logical sequence and could disorient a user

* This example and explanation is confusing, and seems to indicate 2 different scenarios:
1. Where the user closes the revealed content with the focus staying on that control until the user advances one keystroke to the "Site Links" link.  
2. Where the user closes the revealed content with the focus automatically moving to the “Home” button.

## Expected Behavior / Recommendation
* Add text to indicate user closes or collapses the revealed content.
* Clarify state/movement of the visible focus upon closure of the revealed content.

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by AnnMarieDavis** [comment]
Text in 1st paragraph changed to: An agency’s website lists Freedom of Information Act (FOIA) exemptions and examples. With the Tab key, you land on an expand/collapse button. The button is collapsed and you press the Enter key to reveal content hidden under the menu. Below is the revealed content for “Exemptions” after selecting the expand button.
Changed the alt text on the first image to alt="Breadcrumbs at top of page are: Home button, Site Links, FOIA, FOIA Exemptions. The Exemptions section is expanded showing headings that link to Exemption 1 and Exemption 2. A context menu displays: How to Submit a Request, Submit a Request, Library, Component Libraries, Contact information, Exemptions (highlighted), FOIA Appeals Mediation, FOIA and the Privacy Act." 
Text in second paragraph changed to: After expanding the content under "Exemptions,"  the keyboard focus automatically moves to the "Home" icon in the navigational breadcrumbs menu. Advancing one keystroke (a Tab or arrow key) moves the focus to “Site Links” in the navigational breadcrumbs menu. 
Changed alt text on the second image to: Keyboard focus moves to Site Links, the element next to "Home".
Text in Evaluation result #1 is changed to: This is **FALSE**. After expanding the "Exemptions" content, keyboard focus automatically appears on the “Home” button, which is in a different section of the web page. This is not a logical sequence and could disorient a user. A user expects to remain in the Exemptions section where the content was revealed and be able to continue navigating from that point.
