### ISSUE TITLE
TTv5 Q&A: Color Contrast Issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#152]
Location: Trusted Tester Q&A - June 18, 2019 page
Issue:  The 'Help with search' question mark has a color contrast ratio (4.4:1) that is less than 4.5:1.  This issue needs to be corrected globally.

![Color Contrast Issue_Search Question Mark (TT5 6-18 page)](https://user-images.githubusercontent.com/34749031/59767729-f0798900-9270-11e9-862e-31fe6e41ffe5.jpg)

**Comment by drewnielson** [comment]
Fixed
