### ISSUE TITLE
Exam Final Issue for 16.A-incorrect answer

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#153]
Final Exam Web page:
http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-final/testPages/index.php?KeyID=1313 

This page, for me, Fails 2.A b/c the bird chirping audio plays automatically (and scored correctly). However, the score says 16.A is DNA.  Since there is audio-only, 16.A should NOT be scored DNA. There should either be a text-based alternative for the audio, or not.

**Comment by drewnielson** [comment]
Agreed. Passing example could include some simple text on the page: "Page audio: chirping birds." Failing example would provide no text alternative.

**Comment by Tonylayton1** [comment]
I didn't think about the implications of 16.A since it's background audio. Where would it be appropriate to add the transcript for this?

**Comment by AnnMarieDavis** [comment]
That’s a great question!  Off the top of my head, I have NO idea.  Let me confer with Andrew and some other folks.

Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by AnnMarieDavis** [comment]
Talked with Andrew and we think you could just add a transcript button right next to the audio on/off button. Just need something simple in the transcript like: Page audio: birds chirping

**Comment by Tonylayton1** [comment]
I'll add this is jira. moving this to review in GitHub.

**Comment by AnnMarieDavis** [comment]
This is a JIRA issue - not for GitHub
