### ISSUE TITLE
Keyboard trap Dialog box does not match content

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#154]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [x ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2691
Keyboard trap 
Passing Example 1
https://dev.section508testing.net/html/4C_Pass1.html

## Actual Behavior / Observation
Modal window displayed when link is selected is very different from the text and graphic in the example.

**Comment by drewnielson** [comment]
Sorry - still not quite sure what the issue is. The screenshot is of the interactive sample page after activating the "Upload File Details" button/link. What I see in the sample is the same as displayed in the screenshot. Is the issue due to differences in browser rendering, or are you saying that the functionality is different than described? Please give me a little more information.

**Comment by smh243** [comment]
I will get back to you on this one.
Thanks,
Mark

Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>
or email the EES Customer Service Center<mailto:EESCSC@va.gov>
[cid:image006.jpg@01D5274D.38B15B10]

**Comment by drewnielson** [comment]
@smh243, have you had a chance to get back to this? Definitely want to get to the bottom of whatever the issue is. Thanks!

**Comment by smh243** [comment]
Please see attached.
It may be that I am overly picky. 😊
Thanks,
Mark

Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>.
[cid:image006.jpg@01D537C3.12BEC420]

**Comment by drewnielson** [comment]
Hey Mark (@smh243), your attachment didn't come through in the GitHub comments. Can you send it directly to my dhs email: andrew.nielson@associates.hq.dhs.gov

**Comment by drewnielson** [comment]
Thanks @smh243. Including screenshots from attachment (below). Looks like we just need to update the screenshot in the body of the course topic.

Dialog box example from course:
![image](https://user-images.githubusercontent.com/29068131/61056202-e440a180-a3c0-11e9-9e72-b7c71889d048.png)

Actual pop up after mashing Upload Files details button:
![image](https://user-images.githubusercontent.com/29068131/61056247-f589ae00-a3c0-11e9-9ed0-a2138491440e.png)

**Comment by drewnielson** [comment]
fixed
