### ISSUE TITLE
TTv5 Q&A: Color Contrast Issue for Required Text.

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#156]
Location: Trusted Tester Q&A - June 18, 2019
https://dev.section508testing.net/mod/forum/post.php?forum=33
Issue:  The following text items have color contrast ratios that are less than 4.5:1.  This issue also exists on the 'Sign-up for Trusted Tester Q&A - Tuesday Webinar page as well.  Wherever this text is used within the application, it should be fixed globally.

- red asterisk (*) [4.1]
- 'Required text' [3.94:1]

![Color Contrast Issue_Required Text (TT5 6-18 page)](https://user-images.githubusercontent.com/34749031/59786158-98ed1480-9294-11e9-8f89-1dba671e97e8.jpg)

![image](https://user-images.githubusercontent.com/34749031/60452854-8ad8b580-9bfd-11e9-8d9e-c124138df00c.png)

**Comment by drewnielson** [comment]
fixed
