### ISSUE TITLE
Change of context

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#157]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x ] Other, specify...Test numbering reference
## Description
Text says "This section describes how to test 4.E for 3.2.1-on-focus."

from the TT process
Continue Test 4.D.
Should this be Continue Test 4.E? 4.D should be done

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2704
Lesson 5
How to test

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
Thanks. Typo in text. Should be "Continue ***from*** Test 4.D." rather than "Continue Test 4.D." Fixed.
