### ISSUE TITLE
Typo Lesson 5 Eval content

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#158]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [x ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2705
Lesson 5 Evaluation Content.
from the TT process
 < in front of PASSES

**Comment by KSmithO** [comment]
Thanks! This has now been fixed!
