### ISSUE TITLE
order return

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#159]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ x] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2732
Lesson 8 Focus Order Return
Failing Example 1

Text says Advancing one key stroke moves focus to Site links.... 
Eval results says focus appears on Home button.

**Comment by drewnielson** [comment]
Added some additional language to clarify observed behavior.
