### ISSUE TITLE
Topic 10: ALT description requires additional text

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#16]
Within Content Structure > Lesson 2: Determinable Heading > Identifying content page, for the image under 2.b. the ALT description needs to include all the headings identified within the image (e.g., 'Intent of this Success Criterion', etc.).
![Top10_ALT Desc (Lesson2-Identifying content page)](https://user-images.githubusercontent.com/34749031/58335549-cec2e880-7e0f-11e9-940d-bc75616bedf8.jpg)

**Comment by KSmithO** [comment]
Not a 508 issue-properly describes intent of the image.
