### ISSUE TITLE
Auto-Playing and Auto-Updating Content - Incremental Practical Exam

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#160]
How do you pass the Auto-Playing and Auto-Updating Content - Incremental Practical Exam if the video doesn’t play? Issue occurs on GFE might be firewall 
Issue raised by Dominique Wheeler

**Comment by drewnielson** [comment]
Known issue. Seemed to happen when we moved the exams from the Dev to a clone environment. Carney is investigating.

**Comment by drewnielson** [comment]
Closing this issue as duplicate. Issue described in #105.
