### ISSUE TITLE
Topic 4 Knowledge Check check box is not showing checked?

### ISSUE THREAD

**Issue by vprentice** [Section508Coordinators/DHSA-TT-200-A#161]
Description Trusted Tester Review - June 19, 2019
Keyboard Access and Focus-Knowledge Check is not marked and completed when it has been .
Location: https://training.section508testing.net/mod/quiz/view.php?id=1230
Topic-4 

## Actual Behavior / Observation
Keyboard Access and Focus-Knowledge Check is not marked and completed when it has been completed?

Expected Behavior / Recommendation
Check mark of completion should be shown.

I could not attach the images that I have of issue.

Vince

**Comment by drewnielson** [comment]
@vprentice, I don't think that the knowledge check activities will display the completion checkmark for you when logged in as a course manager/editor/teacher. You can change your role to "student" under the admin panel, but it will only save your progress/completion status for that particular session while you are emulating the student role.

**Comment by vprentice** [comment]
I will take a look to see if that is the case, this was  just very weird to me.

Vince
