### ISSUE TITLE
keyboard access 

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#162]
I’m a participant in TT5 pilot. I found an issue as shown below. The relevant section has the following description:

Using the keyboard, you successfully execute the interactive elements that are keyboard accessible by doing the following:
•	Using the keyboard (Tab or arrow key), you navigate to: Web Mail Access, Enterprise Vault, Outlook Mobile App video, What is New in office 365, and Office 365 FAQ, and press the Enter key to successfully activate each element.
I did not see indication of activation in any of the five links with the Enter key.
Issue raised by Manzoor.Murshed@uscis.dhs.gov

![image](https://user-images.githubusercontent.com/51798183/59848421-1c5d4300-9333-11e9-8c89-61fb00064fb2.png)

![image](https://user-images.githubusercontent.com/51798183/59848600-8fff5000-9333-11e9-9516-1fa4ee6c707c.png)

**Comment by drewnielson** [comment]
Although the links were functional with a keyboard, it wasn't obvious, since they just point back to the same page. Added a dummy page as the destination for each of the links.
