### ISSUE TITLE
TTv5 Q&A: Question Mark image focus is faint

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#163]
Location: Trusted Tester Q&A - June 18, 2019
URL: https://dev.section508testing.net/mod/forum/view.php?id=1449
Issue: Recommend making the question mark interactive image visual focus more prominent.  Currently, it is very faint.  This should be corrected globally throughout the application.

![Question Mark_Focus Issue (TT5 6-18 page)](https://user-images.githubusercontent.com/34749031/59935769-8bfb2d00-941c-11e9-8533-6e6e28054e05.jpg)

**Comment by drewnielson** [comment]
Observation is made based on browser rendering. Still passes the requirement, though we could improve the contrast. Focus is more visible in some browsers. May still want to address, but a little easier said than done for specific elements.
