### ISSUE TITLE
Practice Page Links difficult to identify

### ISSUE THREAD

**Issue by CLAMBne508** [Section508Coordinators/DHSA-TT-200-A#165]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X ] Other, specify...[the links in the text for the practice/interactive pages are difficult to identify as links.]

## Description
I've picked up on it a few times, but the links in the text for the practice/interactive pages are difficult to identify as links.  On my machine at least the links are not underlined and are a dark blue text which does not stand out against the black text of the page.

## Location
[https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2676, Topic 4, Lesson 1, Failing Examples]  Although I have noticed this throughout this Topic and assume it is probably throughout the course.

## Actual Behavior / Observation
I've picked up on it a few times, but the links in the text for the practice/interactive pages are difficult to identify as links.  On my machine at least the links are not underlined and are a dark blue text which does not stand out against the black text of the page.

## Expected Behavior / Recommendation
If the link text cannot be underlined I would suggest making it a color that is not as close to black.  

## Steps to Reproduce the Issue (if applicable)
Reading through content.  I missed the link under the first example.  I noticed it on the second example.  Then I went back to see if the first example had

**Comment by goodwitch** [comment]
+1  this issue is a failure of WCAG 2.0 SC 1.4.1 Use of Color.  See documented Failure F73:  Failure of Success Criterion 1.4.3 due to creating links that are not visually evident without color vision  https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F73

**Comment by drewnielson** [comment]
@katbecker, I assume this is something you can fix with the stylesheet, but let me know if otherwise. Let's maybe just try to differentiate the color a little more and add an underline to the `<a>` element.

**Comment by drewnielson** [comment]
@katbecker, I added a style for ".book_content a" that differentiates the color a little better and adds underline just to the links that show up in books.
