### ISSUE TITLE
Course completion status not indicating completion

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#166]
Although student completed course and obtained course completion certificate, the student's course completion status on the student dashboard still displays as "Enrolled" rather than "Completed."
Submitted by Kathy Jenkins

**Comment by drewnielson** [comment]
Might have something to do with the Exam Admin tool, which students cannot access but may still be affecting the total cumulative "score" for the course. Tonya will create a separate "Exam Admin" course to host the Exam Admin activity, which we can continue to use to view student exam data.

**Comment by drewnielson** [comment]
Hey, @katbecker, would you mind taking a look at the course settings to see if  you have any insights. Tonya thought it might have had something to do with the Exam Admin Tool somehow being included in the course grade, so I moved that out into its own standalone course. I've tried to play around with the other course completion settings, but haven't been able to get to the bottom of it.

**Comment by Ailikekaus** [comment]
I also noticed when I enrolled in my very first course.  Each course I enrolled in has had "Not avaliable" listed until I completed the course.  I actually received an email from OAST asking why I had not started a course - I was waiting until it said something other than Not available.
![image](https://user-images.githubusercontent.com/19952958/60509234-6ed72180-9c9a-11e9-9461-4265f97b0fde.png)

**Comment by drewnielson** [comment]
Fixed!
