### ISSUE TITLE
TTv5 Q&A: Drop-down list menu does not have markup.

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#167]
Location: Trusted Tester Q&A – Tuesday Webinar page > Export Attendance section
URL: https://dev.section508testing.net/mod/facetoface/view.php?id=1464
Issue:  The ANDI Output does not identify an appropriate markup for the 'Select' element (i.e., accessible name, label or title attribute) for the ‘Format’ drop-down list.

![Drop-down List_No MarkUp (Tuesday Webinar page)](https://user-images.githubusercontent.com/34749031/59936966-3d9b5d80-941f-11e9-930d-d9652ec145ef.jpg)

**Comment by drewnielson** [comment]
Deferring for now. Not an issue for students, since it is only available to admins/teachers. Will still need to fix, but we can release to public without risk of creating an accessibility issue for students.
