### ISSUE TITLE
TTv5 Q&A: Instructions are not associated with form elements.

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#168]
Location: Search page
URL: https://dev.section508testing.net/mod/forum/search.php?search=&id=89
Issue: Instructions are not programmatically associated to the form input elements via the Accessibility Component or ANDI Output (i.e., aria-describedby, label, etc.).

![Input Text FIeld (Search page)](https://user-images.githubusercontent.com/34749031/59938499-28c0c900-9423-11e9-8cbe-f71317121f27.jpg)

**Comment by drewnielson** [comment]
Don't agree that the text in question should be associated with each field as instructions. Simple introductory text. Omitting the text from each field would not cause an detriment in understanding or ability to complete the form.
