### ISSUE TITLE
Topic 5: Incremental Exam (incorrect test IDs)

### ISSUE THREAD

**Issue by dderouchey** [Section508Coordinators/DHSA-TT-200-A#169]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The Test IDs B-G are incorrectly labeled and 5B is missing.
![topic-5-incremental-exam-incorrect-IDs](https://user-images.githubusercontent.com/51759875/59938641-cfe93480-9412-11e9-95e8-16f829151aa1.png)

## Location
Topic 5, Incremental Exam

## Actual Behavior / Observation
I believe 5B is missing and then what is shown as 5B-5G are incorrect.

## Expected Behavior / Recommendation
Add test ID 5B and then change test IDs 5B-5G to be 5C-5H.

## Steps to Reproduce the Issue (if applicable)
Select the Enter Results button.

**Comment by AnnMarieDavis** [comment]
Text changes needed on Topic 5 answer sheets:
1. Change current 5.A  3.3.2-label-provided   
Labels or instructions are provided for form elements.
2. _Insert a new 5.B_  2.4.6 –label-descriptive    
Each form label is sufficiently descriptive. 
3. Change current 5.B to 5.C 1.3.1-programmatic-label  
(no change needed for the associated description )
4. Change current 5.C to 5.D
5. Change current 5.D to 5.E
6. Change current 5.E to 5.F
7.  Change current 5.F to 5.G
Remove "Additional" from the Test Condition (the first word currently). Capitalize "Guidance" which will be the new first word.
8.  Change current 5.G to 5.H

**Comment by mikebarklage** [comment]
Added new 5.A and 1.E, currently undergoing QA.

**Comment by mikebarklage** [comment]
Also: same as #55

**Comment by Tonylayton1** [comment]
Addressed by issue #55 , which is verified on dev

**Comment by AnnMarieDavis** [comment]
Verified the answer sheet has changed.
