### ISSUE TITLE
Topic 10: Color Contrast Issue within image

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#17]
Topic 10 > Lesson 2: Determinable  Heading > DNA examples > Example 1 image, the light-blue text within the image has a color contrast ratio (4.3:1) that is below 4.5:1.
![Top10_CCA Issue (Lesson2-DNA examples page)](https://user-images.githubusercontent.com/34749031/58347499-03449d80-7e2c-11e9-93ca-75e7fdf7bce9.jpg)

**Comment by KSmithO** [comment]
Questions: do we really need this fixed (links have no impact on purpose of the image and convey no real meaning for image purpose)? links are a browser default we can't control either... so worth fixing and LOE?

**Comment by drewnielson** [comment]
I'd say we don't need to fix this. Agreed that the content in question is not pertinent to the overall purpose of the image or lesson. Closing the issue, but will re-open if someone has a strong objection.
