### ISSUE TITLE
Topic 6: Lessons 1 & 2 - How to test (extra text on page may need to be deleted)

### ISSUE THREAD

**Issue by dderouchey** [Section508Coordinators/DHSA-TT-200-A#172]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ X ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
I believe there is extra text on two "How to test" pages that may need to be deleted.

## Location
https://training.section508testing.net/mod/book/view.php?id=1235&chapterid=2816
Topic 6, Lesson 1, How to test
Topic 6, Lesson 2, How to test

## Actual Behavior / Observation
In Lesson 1 the 1st sentence states "This section describes how to test 6.A for 1.2.1 for 2.4.4-link-purpose".
![topic-6-lesson1-how-to-test-error](https://user-images.githubusercontent.com/51759875/59949943-d509ac00-9431-11e9-9e05-e2b6404e7918.png)

In Lesson 2 the 1st sentence states "This section describes how to test 6.B for 1.2.1 for 4.1.2-change-notify-links".
![topic-6-lesson2-how-to-test-error](https://user-images.githubusercontent.com/51759875/59949981-e9e63f80-9431-11e9-8ddd-a1639b20e3d0.png)

## Expected Behavior / Recommendation
On both pages I think the text "for 1.2.1" may need to be deleted.

## Steps to Reproduce the Issue (if applicable)
1. Go to Topic 6
2. Go to Lesson 1 > How to test > 1st sentence
2. Go to Lesson 2 > How to test > 1st sentence

**Comment by AnnMarieDavis** [comment]
thank you for this catch!  
Changed completed.
