### ISSUE TITLE
Topic 7, Lesson 5, Evaluating content page, incorrect Test ID listed

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#174]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Test ID 5.E is listed instead of Test ID 7.E on the Topic 7 Images, Evaluating content page.

## Location
https://training.section508testing.net/mod/book/view.php?id=1238&chapterid=2861
Topic 7
Lesson 5: Images of Text
7.E  1.4.5-image-of-text
Evaluating content page

## Actual Behavior / Observation
Test ID 5.E is listed instead of Test ID 7.E on the Evaluating content page.
![image](https://user-images.githubusercontent.com/19952958/60023973-e4bd0680-9664-11e9-98b7-69ddea10de32.png)

## Expected Behavior / Recommendation
Change text from "5.E" to "7.E"

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
Thanks! Fixed.
