### ISSUE TITLE
Topic 4 Incremental - answer inputs for kb trap and focus order

### ISSUE THREAD

**Issue by CLAMBne508** [Section508Coordinators/DHSA-TT-200-A#175]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X ] Other, specify...[No instructions on how to select non-compliant options for kb trap and focus order. ]

## Description
[While taking the incremental I found that KB trap and focus order were NC.  However there was no instruction on what to select as an NC response.  The KB trap in my example trapped me in section 2.  I selected the two elements I couldn't get to in that section as possible answers but they were apparently not correct.  I didn't think they would be, but was guessing at that point since there was no option to select a keyboard trap was found.  Additional instruction on how to report findings in the incremental would be helpful.  I looked through the section for Topic 4 in the course and could not find anything I also read through the test process document.  The same with focus order.  I felt that the focus order was confusing, it's possible that was incorrect.  But even if it was instructions on how to answer that would be helpful.  As in do you select the last element that properly received focus or the element that should have received focus?  I know these notes were useful in the previous version of the training.  I think this would also be helpful for other tests done in this section and possibly others.  I went back the next day and the remaining test ID's were then compliant so I was able to move forward.  

## Location
[URL, Topic 4, Incremental Exam, Subchapter]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
Provide instruction on how to input non compliant responses.

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
Issue subsumed by issue #205. Clarified instructions to be provided for each of the topic/section 4 tests on the Add/Edit results page(s) of the exams. Closing this issue since it is now covered under #205.
