### ISSUE TITLE
Incremental Exam Headings

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#176]
##Issue Type (put an X between the brackets to indicate issue type)
- [x] Typo/grammar
- [x] Incorrect content

## Description
 Incremental Practice Exams banners contain incorrect information:
1. Large blue banner currently states "Section 508 Trusted Tester Certification Exam" -- This needs to be changed to "Section 508 Trusted Tester Incremental Practice Exam"
2. Grey banner currently states "Certification Exam"  -- This needs to be changed to "Incremental Practice Exam"

## Location
This is a global issue for all incremental exams:

## Expected Behavior / Recommendation
Change banners on Incremental Exams to state "Incremental Practice" everywhere in states "Certification"

**Comment by mikebarklage** [comment]
I updated the titles for the incremental exams on Dev - with the longer title, I had to reduce the font size a little in the blue banner. FYI, since this was in an HTML file shared across all exams, I had to replace the titles dynamically via JS, only for applicable exams.

**Comment by Tonylayton1** [comment]
name change has been verified on all 16 incremental practice exams on Dev.

**Comment by AnnMarieDavis** [comment]
Verified
