### ISSUE TITLE
Incremental Exam Q7A: Carney Fix (Company Logo image)

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#177]
Location: Incremental Exam Q7A: Company Logo image
URL: http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=392
Issue: This is a grey area for the incremental exam, Question 7A.  Currently, the ALT attribute is not descriptive and the correct exam answer is marked as compliant (C).  Instead, it should be marked as non-compliant (NC).

![Company Logo Image (7A IncrementalExam page)](https://user-images.githubusercontent.com/34749031/60045150-21532700-9692-11e9-8fff-ab3c5d5592fc.jpg)

**Comment by drewnielson** [comment]
Agreed that for the passing example(s) we should probably be a bit more descriptive, just to make the example a clear pass. Suggest revising alt to "Work Balance scale company logo" or something close to that.

**Comment by mikebarklage** [comment]
Alt text is updated on all 3 pages.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
ALT text is now correct.
![2019-07-08_ANDI WorkBalanceLogo](https://user-images.githubusercontent.com/31414225/60827546-74db6f80-a17e-11e9-804a-253a32148770.png)
