### ISSUE TITLE
Topic 9, KC Quiz, Question 2, Test Names incorrect.

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#179]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Topic 9, Knowledge Check Quiz, Question 2, all questions list the Test Name incorrectly.
Listed as "2.1.1-bypass-function" instead of "2.4.1-bypass-function".

## Location
https://training.section508testing.net/mod/quiz/attempt.php?attempt=28934&page=1&scrollpos=0#q2
Topic 9, Repetitive Content - Knowledge Check Quiz, Questions 2.

## Actual Behavior / Observation
![image](https://user-images.githubusercontent.com/19952958/60113651-43a37e00-9740-11e9-82d3-768bad9fa422.png)

## Expected Behavior / Recommendation
Update Test Name to "2.4.1-bypass-function".

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
Thanks! Fixed.
