### ISSUE TITLE
Topic 10: Color Contrast issue within a image.

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#18]
Topic 10 > Lesson 2: Determinable Heading > Passing examples > Example 2 image, the light-blue heading text within the image has a color contrast ratio (2.9:1) that is below 4.5:1.
![Top10_CCA Issue (Lesson2-Passing examples page)](https://user-images.githubusercontent.com/34749031/58348203-f759db00-7e2d-11e9-91ab-94cb5c0c9e55.jpg)

**Comment by KSmithO** [comment]
Questions: do we really need this fixed (text itself hasno impact on purpose of the image and convey no real meaning for image purpose)? if we want this fixed, how much of an effort would it be?

**Comment by drewnielson** [comment]
Given that the text that immediately follows the image also describes the pertinent information relayed by the image, I would argue that all users have equal access to the information we are presenting via the text and the image. I recommend not spending the time to fix this issue. Closing issue, but can re-open if someone has a strong objection.
