### ISSUE TITLE
12.D scored incorrectly on incremental exam

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#180]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Incremental test for 12.D scoring incorrectly

## Location
http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?studentEmail=joyce.carrschwab@associates.ice.dhs.gov&SCOInstanceID=280&examId=12

## Actual Behavior / Observation
Tab index is -1 for the frame identified. This means that the test for 12.D is DNA. 

## Expected Behavior / Recommendation
Submitted this answer, and the system rejected this as a correct response. 

![image](https://user-images.githubusercontent.com/51755970/60138290-d57aad80-9777-11e9-974d-6fda473f855a.png)
![image](https://user-images.githubusercontent.com/51755970/60138294-d9a6cb00-9777-11e9-82a7-6ef63ae78f01.png)

**Comment by jcarrschwab** [comment]
When I passed this condition on the incremental, the system accepted the answer.

**Comment by michaelasalter** [comment]
I also experienced this.

**Comment by drewnielson** [comment]
Thanks! Duplicate with issue #95. Fixed in last Friday's deployment to incremental exams.
