### ISSUE TITLE
Improper scoring for Incremental Exam 12.B

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#181]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Page has no title. When I failed this, I noted the following:
- Page title not defined.
- Other pages in the site collection had titles, so this is the only page that is not defined. In other words, it is uniquely identified, but blank.

## Location
http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?studentEmail=joyce.carrschwab@associates.ice.dhs.gov&SCOInstanceID=280&examId=12

## Actual Behavior / Observation
Failed in multiple circumstances that weren't accepted with the reasons:
- The page title is not defined
or
- The page title does not describe the content
or 
Both of the above

All 3 failed.

## Expected Behavior / Recommendation
I expected 1 of the above to be the correct description of the issue, which is that a blank title can't describe the content and therefore fails 12.B.

In this circumstance, what is the proper justification? Is this a system issue or my understanding of the reason to fail? My understanding is that this can never be DNA.

**Comment by drewnielson** [comment]
Thanks! Also addressed in issue #95, and should be fixed as of last Friday's deployment to the incremental exams.
