### ISSUE TITLE
Topic 9; Test tools, methods, and references page; content suggestion

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#182]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x] Other, specify...Suggested content addition for training course

## Description
Suggest adding to the "Test tools, methods, and references" page:
* ANDI: structures > “tab order” enabled.

## Location
https://training.section508testing.net/mod/book/view.php?id=1244&chapterid=2890
Topic 9 Repetitive Content; Lesson 2: Consistent Navigation, 9.B; Test tools, methods, and references page 

## Actual Behavior / Observation
The "How to test" page (https://training.section508testing.net/mod/book/view.php?id=1244&chapterid=2892) 2a notes the use of "ANDI’s “tab order” feature", but this is not listed as a test tool on the "Test tools, methods, and references" page, or the "Summary What was covered in this topic" page (https://training.section508testing.net/mod/book/view.php?id=1244&chapterid=2906), "Making test decisions" section.

![image](https://user-images.githubusercontent.com/19952958/60173074-faa10780-97db-11e9-89a7-31a24a7a36df.png)

## Expected Behavior / Recommendation
Suggest adding to the "Test tools, methods, and references" page:
* ANDI: structures > “tab order” enabled.

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by AnnMarieDavis** [comment]
Added text below and image of the focusable element.tab order:
The ANDI tab order is show to the left of each element in yellow, in the image below.
