### ISSUE TITLE
Topic 10; Test tools, methods, and references page; content suggestion

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#183]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x] Other, specify...Suggested content addition for training course

## Description
Suggest adding to the "Test tools, methods, and references" page:
* Manual inspection of the page content

## Location
Topic 10 Content Structure; Lesson 2 10.B; Test tools, methods, and references page https://training.section508testing.net/mod/book/view.php?id=1247&chapterid=2918

## Actual Behavior / Observation
The "Identifying content" page (https://training.section508testing.net/mod/book/view.php?id=1247&chapterid=2919) contains:
* "Identify all _visually apparent headings_…" from Item 1
* "...where there are no _visual headings_..." from "When this test does not apply" section 

This indicates "Manual inspection of the page content" should be listed on the "Test tools, methods, and references" page.
![image](https://user-images.githubusercontent.com/19952958/60174926-2d4cff00-97e0-11e9-88a0-99aa62a37996.png)

## Expected Behavior / Recommendation
Suggest adding to the "Test tools, methods, and references" page:
* Manual inspection of the page content

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by AnnMarieDavis** [comment]
Currently 10.C testing tools are: 
1. Manual page inspection for visual heading structure.
2. ANDI: structures > headings > view outline button.

Consider changing 10.B testing tools to include #1 below: 
1. Manual page inspection for visual heading structure. 
2.  ANDI: structures > headings

**Comment by drewnielson** [comment]
@AnnMarieDavis agreed with the addition/change to the training content

**Comment by AnnMarieDavis** [comment]
Completed
