### ISSUE TITLE
Fix needed to 13.B Failing Example 2 in course

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#184]
## Issue Type 
- [x] Incorrect content

## Description
Failing example 2 for 10.B, 1.3.3-sensory-info cites just shape (check or x)  to indicate if an item is in stock.  However, the visual adds color.

## Location
https://training.section508testing.net/mod/book/view.php?id=1258&chapterid=3016

## Needed Remediation
Modify the picture to make the color of the checkmarks and x marks black. Otherwise this will not be a failing example since color and shape are used, not just shape.

**Comment by drewnielson** [comment]
Fixed
