### ISSUE TITLE
Topic 6: Links/Buttons Interactive examples seem to work differently

### ISSUE THREAD

**Issue by sbikmal20** [Section508Coordinators/DHSA-TT-200-A#185]
## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Interactive Example 4 in Passing example and Interactive Example 2 in Failing Examples seem to work differently from how it is explained. 
Example 4 - The screenshot describes 'Ambiguous link: same name/description.....' but when I follow the interactive example, that message doesn't appear. Is this a issue or am I doing something incorrectly?
Example 2 in Failing Examples - For this Interactive Sample, it displays that no links were found. 

## Location
 Interactive Example 4 - Passing Example, Links/Buttons https://training.section508testing.net/mod/book/view.php?id=1235&chapterid=2811

Interactive Example 2 - Failing Examples, Links/Buttons 
https://training.section508testing.net/mod/book/view.php?id=1235&chapterid=2812

![Example2](https://user-images.githubusercontent.com/51759859/60260803-618bf280-98a8-11e9-8ac5-3972b98cdf79.png)
![Example4](https://user-images.githubusercontent.com/51759859/60260818-6a7cc400-98a8-11e9-8e29-89f0d10aa762.png)

**Comment by drewnielson** [comment]
Thanks @sbikmal20! For the issue related to Example 4, we need to update the screenshot image that comes before the interactive sample. That is the result of an update to ANDI, which will not display the ambiguous link warning in that specific situation any longer. Basically, ANDI got smarter and will consider list hierarchy to determine the uniqueness of a link, whereas previously (when the screenshot was originally taken) it did not.

For the interactive sample under Example 2, that is working as expected. There are no links in that sample. You just need to click the "buttons" link at the top of the ANDI pane after launching the links/buttons module.

**Comment by drewnielson** [comment]
Fixed. Image replaced.
