### ISSUE TITLE
Topic 14 Tables, 14.A, Passing Example 1, possible Interactive Sample error

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#188]
## Issue Type 
- [x] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
possible Interactive Sample error -
Interactive Sample does not display the same results as shown in the course example.

## Location
https://training.section508testing.net/mod/book/view.php?id=1262&chapterid=3035
Topic 14 Tables, 14.A, Passing Example 1

## Actual Behavior / Observation
Example 1 shows innerText Accessibility Component, and ANDI Output of:
`Homework Exams Projects 1 2 Final 1 2 Final 15% 15% 15% ...`

The Interactive Sample shows:
No accessibility markup found for this Element, and blank ANDI Output.

![image](https://user-images.githubusercontent.com/19952958/60349583-e56cda00-998f-11e9-80f4-c9ea8232865c.png)

I get the same results when opening the iFrame in a new tab and running ANDI there.

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
Run the Interactive Sample ANDI tool.

**Comment by AnnMarieDavis** [comment]
The interactive table is properly marked. However, I was unable to replicated the screen shot provided in the course either.  Update is needed to the text and image.

**Comment by AnnMarieDavis** [comment]
Update to screen shot showing table identification.
