### ISSUE TITLE
Topic 15, CSS Content and Positioning, Lesson 2, erroneous Failing interactive Example 1

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#189]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [x] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Erroneous Failing interactive sample for Topic 15, Failing Example 1.
"Example 1 - Interactive Sample" displays the interactive sample for Example 2.

## Location
Topic 15, CSS Content and Positioning, Lesson 2, Failing examples
https://training.section508testing.net/mod/book/view.php?id=1266&chapterid=3072

## Actual Behavior / Observation
"Example 1 - Interactive Sample" displays the interactive sample for Example 2.

![image](https://user-images.githubusercontent.com/19952958/60365013-afdae780-99b5-11e9-85cb-985710244247.png)

## Expected Behavior / Recommendation
The interactive sample for Example 1 should display the interactive sample for Example 1.

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by AnnMarieDavis** [comment]
Correction made to replace Failing example 1 to page.  Done in production.
