### ISSUE TITLE
TTv5 Q&A: Inaccessible Link

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#191]
Location:  Trusted Tester Q&A - June 18, 2019 page
URL: 
https://dev.section508testing.net/mod/forum/post.php?forum=33
Issue:  Under the 'Attachment' section, the 'Files' link next to the folder image is not accessible via keyboard or mouse.

![image](https://user-images.githubusercontent.com/34749031/60366790-8cff0200-99ba-11e9-828a-81a58aab2ff9.png)

**Comment by drewnielson** [comment]
@HD508Github, I am confused about your findings. Just tested in Chrome and IE. I observe keyboard focus with both browsers, and the mouse works as well. With that said, why would you fail something that is NEITHER keyboard NOR mouse accessible?
