### ISSUE TITLE
TTv5 Q&A: Table Issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#192]
Location: Participants Page
URL: https://dev.section508testing.net/user/index.php?contextid=10109&roleid=5
Issue:  Table does not have any table headers.

![image](https://user-images.githubusercontent.com/34749031/60430779-23564200-9bcc-11e9-98ec-cf214a00702d.png)

**Comment by drewnielson** [comment]
@HD508Github, this is a layout table. Layout tables should NOT have table header elements. Not a fail under TT4 or TT5.

**Comment by HD508Github** [comment]
Andrew,

My apologies, In my haste I forgot to add more text to this issue to suggest that it should be marked up as a layout table (e.g., role=”presentation”).  It’s probably not a big deal as this will not be a student functionality; but, as I get more familiar with the course content, I want to make sure I understand the appropriate markup for layout tables using ANDI.  Currently, ANDI shows there are no presentation tables on the screen, but clearly it is (see screenshot below).

Since ANDI recognizes the element as a table, but the element is not marked up using the attribute role’=”presentation”, should we advise students to fail Test ID 14.C because the table does not have the role=”presentation” attribute?  Please advise.

Thanks.

[cid:image004.jpg@01D530BE.5D9E42B0]

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D3A09F.E6927B00]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.

**Comment by drewnielson** [comment]
Please review the Evaluate results section of test ID 14.C again, and we can discuss further outside of GitHub. Also, in the future, when you are responding via email to the GitHub issues, please delete your footer and the message that is copied below your reply. All of that text is added as a comment in GitHub, but it is not necessary.

**Comment by HD508Github** [comment]
Okay, will do.
Thx.

**Comment by drewnielson** [comment]
Again, when you reply via email to the GitHub issues, your reply gets added as a comment to the issue in GitHub, INCLUDING the message you are replying to that is copied in the body of your email. In the future, please remove that text before you hit send just to help us avoid the clutter in the comments.
