### ISSUE TITLE
TTv5 Q&A: Keyboard access issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#193]
Location: Trusted Tester Q&A - June 18, 2019 > Add a new discussion topic page
URL: https://dev.section508testing.net/mod/forum/post.php?forum=35
Issue:  Formatting buttons that are not included in the tab order (indicated by the 'x'), are not keyboard accessible.

![image](https://user-images.githubusercontent.com/34749031/60431668-4eda2c00-9bce-11e9-81e8-2478a7158edd.png)

**Comment by drewnielson** [comment]
@HD508Github, once keyboard focus moves to the position labeled with tab stop 10, try using your arrow keys to move across the buttons. This normal behavior for a toolbar item.
