### ISSUE TITLE
TTv5 Q&A: Loss of focus issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#194]
Location: Add a new discussion topic > File Picker window
URL: https://dev.section508testing.net/mod/forum/post.php?forum=35
Issue: Loss of keyboard focus between the ‘Close’ button and the ‘Server Files’ link.

![image](https://user-images.githubusercontent.com/34749031/60437054-784d8480-9bdb-11e9-9b73-2da8a589db1d.png)

**Comment by drewnielson** [comment]
Focus is moving to the "repository items" div. Focus is visible in Chrome, IE, and Edge. Not currently able to replicate with Firefox (my Firefox browser is not working in general). If Firefox really is not displaying the focus, then we'll have to chalk it up to browser difference, not a content/508 issue.
