### ISSUE TITLE
TTv5 Q&A:  Keyboard Access

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#195]
Location: Add a new discussion topic > File Picker window
URL: https://dev.section508testing.net/mod/forum/post.php?forum=33
Issue: Display folder buttons (e.g., Display folder with file icons) are not keyboard accessible.

![image](https://user-images.githubusercontent.com/34749031/60449095-ea7e9300-9bf4-11e9-9c56-c9ea4d22f722.png)

**Comment by drewnielson** [comment]
The icons depicted in your screenshot are disabled. When buttons are disabled, they should not be included in the tab order. If you select one of the items on the left-side menu (e.g., "Server Files"), then the buttons become enabled, and they are keyboard accessible.
