### ISSUE TITLE
TTv5 Q&A: Unable to use ANDI Structure Module

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#196]
Location: Add a new discussion topic > File Picker window
URL: https://dev.section508testing.net/mod/forum/post.php?forum=33
Issue: Unable to use the ANDI Structure module to determine if the 'File picker' window is included in the 'Live Region'.

![image](https://user-images.githubusercontent.com/34749031/60449271-46e1b280-9bf5-11e9-810c-6219dad72dac.png)

**Comment by drewnielson** [comment]
This is not a Q&A or course issue. This is a limitation of ANDI.
