### ISSUE TITLE
Incremental exam security issue

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#197]
The incremental exams appear to NOT be using HTTPS.  This should be fixed for security reasons.

 Issued raised by Al Hoffman

**Comment by drewnielson** [comment]
Really not sure this is an issue. Will need to address with Moonami.

**Comment by drewnielson** [comment]
Moonami is in the process of adding the security certificate, which should resolve this issue.

**Comment by drewnielson** [comment]
Moonami added SSL certificate to servers.
