### ISSUE TITLE
TTv5 Q&A: Live Region Issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#199]
Location: Trusted Tester Q&A - June 18, 2019 > Add a new discussion topic page
URL: https://dev.section508testing.net/mod/forum/post.php?forum=33
Issue:  Unable to access the ANDI Structures module > Live regions function; Pop-up window has a ‘hidden’ attribute—Are these exempt from Live regions function

![image](https://user-images.githubusercontent.com/34749031/60453144-4bf72f80-9bfe-11e9-98ce-828718fda4fb.png)

**Comment by AnnMarieDavis** [comment]
Not able to reproduce.

**Comment by drewnielson** [comment]
Misapplication of the test. The error message does not need to be in a live region; it is provided as a modal dialog alert. That in itself would pass the requirement for providing notification of a change in content, assuming it passes other applicable tests.
