### ISSUE TITLE
TTv5 Q&A: Checkbox issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#202]
Location: Adding a new session in Trusted Tester Q&A - Tuesday Webinar > General section
URL: https://dev.section508testing.net/mod/facetoface/sessions.php?f=15
Issue:  The checkbox does not have markup (i.e., an accessible name, label or title).

![image](https://user-images.githubusercontent.com/34749031/60453707-ddb36c80-9bff-11e9-8452-faadd1598910.png)

**Comment by drewnielson** [comment]
Not a student issue. Would still affect admins/teachers when adding sessions. Deferring issue, pending discussion with Moonami.
