### ISSUE TITLE
2.B scored incorrectly for Video when method exists to pause video

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#203]
## Issue Type (put an X between the brackets to indicate issue type)
- [X] Incorrect content

## Description
2.B is scored incorrectly. 

For this page: http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=45

...the exam is scoring this page as a Fail for the video (http://3.217.25.10/dhsv5/scormapi/admin.php?SCOInstanceID=163&KeyID=45&ExamID=3), however, because there is a mechanism to pause the video within three elements of the video, this should be a PASS for the video. 

## Location
Test page: http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=45
Results: http://3.217.25.10/dhsv5/scormapi/admin.php?SCOInstanceID=163&KeyID=45&ExamID=3

**Comment by drewnielson** [comment]
@Tonylayton1, it looks like Mike has still not accepted the invitation to join this organization, so I can't assign it directly to him. Assigned it to you instead.

**Comment by Tonylayton1** [comment]
I am seeing this as well. When the button at the top of the page was added for 2.A, it looks like the pause/play button under the video is no longer removed in the NC version. 

When 2.A/2.B fails, the pause button at the top of the page should be missing - as well as (as opposed to instead of) - the play/pause button under the video.

**Comment by mikebarklage** [comment]
Fixed so now the video pause button is also missing when 2.A fails.

**Comment by Tonylayton1** [comment]
Verified on Dev

**Comment by AnnMarieDavis** [comment]
Retested http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=annmarie.davis@associates.hq.dhs.gov&SCOInstanceID=100&examId=3 and both 2.A and 2.B are correctly marked C.
