### ISSUE TITLE
Changes for “Fail”answer sheets in Incremental Exams.

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#205]
## Issue Type (put an X between the brackets to indicate issue type)
-  [ x] Typo/grammar
- [x ] Oxther, specify...[language does not match the current test process. NC is no longer used.]
- [x ] Oxther, specify...[instructions are not clear for students to know which checkbox to select to provide the answer in the "key: when they have properly identified the failure.]

## Description
Changes for “Fail” Answer sheets in Incremental Exams.
1.	Change text in ALL headings from: Not compliant [NC] Details. 
**New Text:** FAILING Details 
2.	Change text on 4.A instructions from: Select all Elements that are Not Compliant with Test ID 4.A.
**New Text:** Select the checkbox for any item below that FAILS test condition 4.A.
3.	Change text on 4.B instructions from: Select all Elements that are Not Compliant with Test ID 4.B. 
**New text:** Select the checkbox for any item below that FAILS test condition 4.B.
4.	Change text on 4.C instructions from: Select all Elements that are Not Compliant with Test ID 4.C.
**New text:** Select the checkboxes for the first and last elements that define any keyboard traps found for test condition 4.C. 
5.	Change text on 4.D instructions from: Select all Elements that are Not Compliant with Test ID 4.D.
**New text:** Select the checkbox for any item that FAILS test condition 4.D.
6.	Change text on 4.E instructions from: Select all Elements that are Not Compliant with Test ID 4.E.
**New text:** Select the checkbox for any item below that FAILS test condition 4.E.
7.	Change text on 4.F instructions from: Select all Elements that are Not Compliant with Test ID 4.F.
**New text:** Select the checkbox for each item below that last received the expected focus order when test condition 4.F FAILS.
8.	Change text on 4. G instructions from: Select all Elements that are Not Compliant with Test ID 4.G.
**New text:** Select the checkbox for any item that FAILS test condition 4.G is NC.
9.	Change text on 4. H instructions from: Select all Elements that are Not Compliant with Test ID 4.H: 
**New text:** Select the checkbox for any element that should have received focus when test condition 4.H FAILS.

## Location
[Topic 4, Incremental Exams, Answer sheets for FAILING test conditions 
http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=111&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=4. , ]

**Comment by mikebarklage** [comment]
This is currently generated dynamically with a variable, something like this:
"Select all Elements that are Not Compliant with Test ID [$VARIABLE]."

It would be easy enough to change that to:
"Select the checkbox for any item below that FAILS test condition [$VARIABLE]."

Adding unique descriptions for certain IDs would be tougher - unless it's just for 4.C, 4.F, and 4.H, and no other Topics/IDs, in which case I should be able to just add a few lines of exceptions. If it's more like 20-30 exceptions I should put more thought into how to do it, possibly with a new field in the DB.

**Comment by Tonylayton1** [comment]
Verified that all failure details pages use the following format:
Select all Elements that fail Test ID X.

There is a brief description of the ID's requirements below this, which has always been there. If specific IDs need exceptions to the above format, please reopen and specify which ones, otherwise this is verified on Dev.

**Comment by AnnMarieDavis** [comment]
Verified text has been changed for all answer sheets removing the NC text and using FAILS.
Issue [#221] has been opened for keyboard answer sheets that require more detailed instructions.
