### ISSUE TITLE
Video not loading in Incremental exam for topic 4

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#207]
## Issue Type (put an X between the brackets to indicate issue type)
- [x ] System Bug (the course doesn't function properly)

## Description
[Video not loading in incremental exam. This impacts students ability to complete the exam due to a failure that needs to be noted in the expected behavior of the media player controls]

## Location
[Topic 4, Incremental Exam, http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page3_main.php?KeyID=840]

**Comment by drewnielson** [comment]
Duplicate with issue #105.
