### ISSUE TITLE
Training Dashboard page, "enrol vs "enroll"

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#208]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
British "Enrol" is used vice American "Enroll"

## Location
Training Dashboard page
https://training.section508testing.net/my/

## Actual Behavior / Observation
"Enrol" is used instead of "Enroll".
![image](https://user-images.githubusercontent.com/19952958/60509975-46e8bd80-9c9c-11e9-9169-c9eb0dbaf1ca.png)

## Expected Behavior / Recommendation
https://grammarist.com/spelling/enrol-enroll/
https://www.merriam-webster.com/dictionary/enrol displays results for "enroll" 

## Steps to Reproduce the Issue (if applicable)
N/A

**Comment by drewnielson** [comment]
@katbecker, do you have any insight as to how easy/difficult this would be to fix? Is it something we can address, or do we need to go through Moonami?

**Comment by katbecker** [comment]
Yes, it does have to be corrected in the ELIS plug in (and I'd addressed this with Moonami last Fall but it was deemed less important). I will see if there is a solution without creating a hook.

**Comment by katbecker** [comment]
Yes, can be edited from the front end (Language customization -> en_us -> choose and edit strings). I customized the elis set of strings. Since "enrol" is widely used (and correct option is supplied on many strings) this may show up elsewhere. This particular instance ready for review.

**Comment by drewnielson** [comment]
Verified. Thanks @katbecker.
