### ISSUE TITLE
VIDEO using Snag is needed for keyboard example 2 in Topic 4. 

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#21]
VIDEO has not been developed and needed for https://dev.section508testing.net/mod/book/edit.php?cmid=1245&id=2024

Transcript available http://dhsconnect.dhs.gov/org/comp/mgmt/ocio/oast/authoring/TT%20Course%20Images%20and%20Videos/Forms/AllItems.aspx?RootFolder=%2Forg%2Fcomp%2Fmgmt%2Focio%2Foast%2Fauthoring%2FTT%20Course%20Images%20and%20Videos%2F4%20Keyboard%20and%20Focus%2F4%2Ec%2E3%20Pass%20Video%20and%20transcript&FolderCTID=0x012000EC2E8A35DA0BF14BADE8CC8E6C48B47F&View=%7B0621FAE2%2DA5A5%2D4610%2DBE66%2D7B835CAA833A%7D

**Comment by KSmithO** [comment]
Video created, dropped in, and 508 tested
