### ISSUE TITLE
Certification Exam Unable to open the iframe

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#211]
## Issue Type (put an X between the brackets to indicate issue type)
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Unable to open the iframe to test it for the certification exam in either Firefox or Chrome. Not attempted in Edge or IE.

## Location
Final Certification Exam [http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?studentEmail=annmarie.davis@associates.hq.dhs.gov&SCOInstanceID=159&examId=2]

## Steps to Reproduce the Issue (if applicable)
I tried opening the iframe from ANDI in a new tab in both Google and Firefox.  Also tried copying the iframe address and pasting it in the URL field for both browsers. iframe will not open.

**Comment by AnnMarieDavis** [comment]
issue noted on the About Registration page. Not tested on other pages of the exam.

**Comment by drewnielson** [comment]
Tried in Chrome, IE and Edge and was able to open fine.

**Comment by AnnMarieDavis** [comment]
Just clicking the link opens it... users should not select open in a new window
