### ISSUE TITLE
Topic 4: Lesson and Test Name discrepancy

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#212]
Location: Topic 4 > Lesson 5
URL: https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2701
Issue:  The name for Lesson 5 is different than the 3.2.1 Test Name within the course content.  Currently, the Lesson name reads, Lesson 5: Focus (Change of context) and the Test name reads 3.2.1-on-focus.  The Test Name in the knowledge check is consistent with the Test Name within the  course.  This issue also exists for Lesson 6 and potentially throughout other parts of the course (see attached screenshots).

![image](https://user-images.githubusercontent.com/34749031/60616199-f1490980-9d9e-11e9-918c-c32bdee4b60c.png)

![image](https://user-images.githubusercontent.com/34749031/60616740-26a22700-9da0-11e9-80e5-823e075f1371.png)

**Comment by drewnielson** [comment]
The lesson names are not intended to match the the test names exactly. The names are more of a shorthand reference to the concept.
