### ISSUE TITLE
Trusted Tester Training for Web does not change to completed on my dashboard.

### ISSUE THREAD

**Issue by CLAMBne508** [Section508Coordinators/DHSA-TT-200-A#213]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
On my dashboard screen The Trusted Tester Training for Web on Windows course does not change the status to Passed or show a completed date.

## Location
[https://training.section508testing.net/my/, Dashboard, My Learning Plan]

## Actual Behavior / Observation
The other courses as I completed them changed the status to Pass and showed the date it was completed.  The Trusted Tester Training for Web on Windows still says Enrolled and a completion date as Not available.

## Expected Behavior / Recommendation
Since the Practice Exam and Exam are different courses I would expect it to show this course as completed one I completed all of the tasks in the training.

## Steps to Reproduce the Issue (if applicable)
Log in to my user account.

**Comment by drewnielson** [comment]
Thanks @CLAMBne508. We are already aware of this and working on resolving. Marking this issue as closed - not because it is fixed yet, but because we have already documented this issue in issue #166.

**Comment by drewnielson** [comment]
Fixed (via issue #166 ). @CLAMBne508, you should see the "Passed" status on your dashboard now.
