### ISSUE TITLE
Topic 13.C Table contrast in iframe

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#214]
## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The page contains an iframe with a table. ANDI finds a table header has a failure for contrast in the column headers. This is not properly marked as a needed answer.

![13 C contrast in iframe table 2019-07-08](https://user-images.githubusercontent.com/31414225/60824773-380c7a00-a178-11e9-8802-a60f8d41ec38.png)

![Topic 13 c test result 2019-07-08](https://user-images.githubusercontent.com/31414225/60824797-46f32c80-a178-11e9-8b5d-df8fcad14327.png)

## Location
[http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_iFrame1.php?KeyID=1035, Topic 5, Incremental exam]

**Comment by mikebarklage** [comment]
I darkened the grey bg color so it passes the contrast test. You may need to refresh your local cache to see the change to #707070.

**Comment by Tonylayton1** [comment]
verified on dev, it is now 4.95:1

**Comment by AnnMarieDavis** [comment]
Contrast in iframe now passes
