### ISSUE TITLE
Exam Administration - Student Results

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#215]
## Issue Type 
- [X] System Bug (the course doesn't function properly)

## Description
Student results do not always display for administrators. Student was able to submit answers and see Test Conditions that did not pass. Administrator unable to see expected results to determine why the the answers were incorrect. 
This was observed today for Topic 5, but has happened sporadically for the admin tool.
![Admin Exam Tool 2019-07-08](https://user-images.githubusercontent.com/31414225/60826876-e1556f00-a17c-11e9-8a97-db6b18c22ab5.png)

## Location
[http://52.23.182.152/dhsv5/scormapi/admin.php?SCOInstanceID=148&KeyID=1463&ExamID=5, Moonami Section 508 Exam v5 - Admin Tool]

## Actual Behavior / Observation
Exam results submitted for Topic 5 by student. 
Results displayed to student for topics answers that were incorrect.
When administrator attempted to view the answers, no answers display.

**Comment by AnnMarieDavis** [comment]
Browsers used in testing this issue: Chrome and Firefox.

**Comment by drewnielson** [comment]
I think this could have happened due to the update two Fridays ago. If you had started an incremental exam before the update but hadn't cleared the exam results in the admin tool before completing the exam or starting a new one. Let's make sure we clear the results for any exam before starting a new one and then try to see if we can replicate.

**Comment by AnnMarieDavis** [comment]
I had this happen again today (7/10/2019) while I was retesting Topic 5. I saw results (as a student) after submission, but then could not pull up the results in the Admin Tool.

**Comment by drewnielson** [comment]
This usually happens for me only when I have opened a new exam but have not
yet saved any answers. Let’s walk through this together on your computer.

**Comment by drewnielson** [comment]
I'm seeing the same issue in the admin tool:
* http://52.23.182.152/dhsv5/scormapi/admin.php?SCOInstanceID=61&KeyID=1563&ExamID=5
* http://52.23.182.152/dhsv5/scormapi/admin.php?SCOInstanceID=61&KeyID=1564&ExamID=5

**Comment by mikebarklage** [comment]
Seems like it's displaying attempt 1 fine but having trouble with attempt 2+.

**Comment by mikebarklage** [comment]
I missed one instance of moving 5.G --> 5.H on this admin page, so it was failing, but only when 5.G was NC. I made the fix.

**Comment by Tonylayton1** [comment]
This is the same issue as #232

**Comment by AnnMarieDavis** [comment]
Verified fixed and closed
