### ISSUE TITLE
Topic 17 Incremental Exam typos

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#216]
## Issue Type (put an X between the brackets to indicate issue type)
- [X] Typo/grammar

## Description
Two small typographical errors:
1. In the Advantages of certification section. change "it" to "is" so the second sentence is "After an audit is performed, your..."
![2019-07-08_change it2is](https://user-images.githubusercontent.com/31414225/60835154-701fb700-a190-11e9-8d27-2195ab2eee72.png)

2. In the Contact Us section, add a period to the last sentence so it states: Play it to receive the address.
![2019-07-08_period](https://user-images.githubusercontent.com/31414225/60835221-93e2fd00-a190-11e9-9934-aaee45a6b56f.png)

## Location
[http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?KeyID=1035, Topic 17, Incremental Exam]

**Comment by mikebarklage** [comment]
Typos are fixed on dev.

**Comment by mikebarklage** [comment]
Note that change #1 affects topics 10-15, not topic 17.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified.
