### ISSUE TITLE
Topic 13.B Change to all answer sheets 

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#217]
## Issue Type (put an X between the brackets to indicate issue type)
-- [x ] Other, specify...[clarify test instructions for how to mark answers]

## Description
[Students are confused about what to mark when they have a failure for 13.B. Some are marking the element being referred to using sensory characteristics.  Students need to mark the INSTRUCTIONS that rely solely on sensory characteristics.]

## Location
[http://3.217.25.10/dhsv5/scormapi/lesson1.php?SCOInstanceID=380&studentName=Ann%20Marie%20Davis&ltiUserId=3382&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=13, Topic 13.B, ALL EXAMS]

## Expected Behavior / Recommendation
Change the instructions for marking failures on ALL EXAMS (Incremental, Practice and Final) to: 
**Select the _instructions_ that FAIL Test ID 13.B. (Do not mark the element being referenced in the instructions.)**

**Comment by Tonylayton1** [comment]
recommend closing, as this is covered now in #221

**Comment by AnnMarieDavis** [comment]
Applied to incremental, practice and final.
