### ISSUE TITLE
Topic 13 Incremental Exam changes for clarity

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#218]
## Issue Type (put an X between the brackets to indicate issue type)
- [ X] Other, specify...[clarify page issues that are causing confusion with students]

## Description
Students are not selecting the correct answer and sample needs to be more clear cut. 

## Location
[http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?studentEmail=annmarie.davis@associates.hq.dhs.gov&SCOInstanceID=380&examId=13, Topic 13, Incremental Exam]

## Actual Behavior / Observation
1. Use of "below" is NOT considered an instruction that relies on sensory characteristics of the components. In the Certified members section, add a sentence: The list on the right provides companies with a lifetime certification.
2. Students are testing the TEXT in the Unique Searches graph using a color contrast analyzer and it does not pass on the horizontal axis and the vertical axis(it is just below that now).

## Expected Behavior / Recommendation
1. In the Certified members section:
A. Add a sentence: The list on the right provides companies with a lifetime certification.
B. Change the answer sheet to 13.B from 4 answers (Standard - certified list header, Standard - certified list, Super- certified list header, Super- certified list ) to ONLY "Over 1000 companies... body text"
2. Sharpen the contrast for the text on the horizontal axis and the vertical axis to clearly meet the the 4.5:1 expected ration (it is just below that now)

**Comment by Tonylayton1** [comment]
1: Added these to the randomization document. I'm assuming that this sentence should be randomized though. Failure if it is present, DNA if it is not? please advise if this is not correct.

implications: 
13.B is no longer linked to 15.B and 10.D, and randomized by itself
New randomized sentence
new correct answer for 13.B when failed: r4e03

2: Mike, I made a new png for the line graph. please replace the one currently on the website with the new one. I'll email you the network link.

**Comment by mikebarklage** [comment]
This is mostly done, except I've kept the 13.B randomization choices as C, not DNA.

I removed the NC options from topic 10 and 15 since they are no longer linked. As of now, 13.B is either C or NC for Topic 13, and always C for all other incrementals.

What if anything should change?

**Comment by Tonylayton1** [comment]
Correction: the correct answer for 13.B should be r4_02, not r4_03 as I mistakenly identified above. 

Question to OAST: If the line of text which specifies a positional meaning is not present, would 13.B be DNA or C?

**Comment by drewnielson** [comment]
If there is no line of text referencing position/location/orientation (or
other sensory characteristics), then should be DNA. It would be a pass in
cases where there is text that references the location etc. but ALSO uses
another method (e.g., additional explanatory text, labels) to provide the
same information that the location reference provides.

**Comment by Tonylayton1** [comment]
the failure is working now, but the alternative should be changed to DNA, not C as per above.

**Comment by Tonylayton1** [comment]
To add to the above, I updated the default results sheet this effect

**Comment by mikebarklage** [comment]
OK, updated from C to DNA.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Sorry if directions were unclear. Please replace the text "See below for some well known examples" with "The list on the right provides companies with a lifetime certification." This impacts the answer sheet as well.  You can randomize having the text appear (FAIL) or not be presented (DNA). I didn't see that being presented in two attempts. 

I'm going to add an example to the DNA for 13.B that clarifies that "below" is not considered a directional instruction.
