### ISSUE TITLE
Video autoplay in Chrome and Firefox

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#219]
Issue Type (put an X between the brackets to indicate issue type)
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

Description
The autoplaying video function used for testing 2.A/2.B is countered by certain browsers, specifically Chrome and Firefox. This is known but there was no specific issue for it yet.

**Comment by Tonylayton1** [comment]
To address incremental topic 2: 
Add a mute button to the multimedia video to the right of the AD button. This may require the buttons to be repositioned slightly. Change the video auto play so that it starts the video muted. Lastly, remove the "Pause Autoplay" button that was recently added. This was to address the passing version of 2.A, which is no longer applicable.
- 2.A answer will now always be DNA, as audio will never autoplay
- 2.B answer will remain the same, as the video will always autoplay, and only sometimes have a pause button.

To address the practice exam: 
Will implement background audio and move the autoplay feature to the silent video while updating the practice exam website. This will be updated along with many other issues logged for the practice exam, and will need specifications before it is addressed. 

Please close this issue when then incremental portion of the issue is addressed.

**Comment by mikebarklage** [comment]
This is finished on Dev but should be QAd concurrently with #220 .

**Comment by mikebarklage** [comment]
I also removed the 2.A/2.B link so 2.B will randomize on its own.

**Comment by Tonylayton1** [comment]
Issue with 2.B:
When 2.B is supposed to fail, the play/pause button should be missing. Currently it is always present.

**Comment by mikebarklage** [comment]
Ahh, right. Re-added that for 2.B.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Closed. The video plays automatically, but is muted. The Autoplay button that presented to users upon opening the page has been removed. 

Fingers crossed this will solve the issue!    :0)
