### ISSUE TITLE
Topic 9: ALT and ANDI Output requires modification

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#22]
Location: Lesson 2: Consistent Navigation > Passing examples > Example 1 image
The ALT and ANDI Output reads that there’s only one interface component on the page; but there are actually two additional ones.
![Top9_ALT Desc (Lesson2-Passing examples page)](https://user-images.githubusercontent.com/34749031/58573903-be927b00-820c-11e9-83e1-4f592bc066e9.jpg)

**Comment by KSmithO** [comment]
The "opens the document..." does not need to be included since it is not a navigational interface. Fixed alt to include "prior page". ready for retesting.

**Comment by HD508Github** [comment]
Re-tested and the ALT and ANDI Output have been corrected. Issue resolved.
