### ISSUE TITLE
Unique Exam Instructions

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#221]
This is opening a new issue per Mike Barklage's comments for: Changes for “Fail”answer sheets in Incremental Exams. #205

## Issue Type (put an X between the brackets to indicate issue type)
- [X ] Other, specify...[students do not know how to appropriately mark answer sheets for the correct answer]

## Description
Students often can verbally identify the failure, but are missing the test condition on many keyboard tests because of confusion about how to mark the answer sheet. 

## Location
[Topic 4, Incremental, Practice and Final exams]

## Expected Behavior / Recommendation
**Unique descriptors are needed as follows** on ALL EXAMS for the Topic 4 answer sheets:

1. Text for 4.C instructions:  Select the checkboxes for the FIRST and LAST elements that define keyboard traps that FAIL test condition 4.C.
1.  Text for 4.D instructions: Select the checkbox for the LAST item that received visible focus when test condition 4.D FAILS.
1.  Text for 4.F instructions:  Select the checkbox for the LAST item receiving the expected focus order when test condition 4.F FAILS.
1. Text for 4.G instructions: Select the checkbox for the item that INITIATED the unexpected focus that FAILS test condition 4.G.
1. Text for 4. H instructions: Select the checkbox for the element that SHOULD HAVE received focus when test condition 4.H FAILS.

**Comment by mikebarklage** [comment]
Adding from ticket #217:

Change the instructions for marking failures on ALL EXAMS (Incremental, Practice and Final) to:
**Select the instructions that FAIL Test ID 13.B. (Do not mark the element being referenced in the instructions.)**

**Comment by mikebarklage** [comment]
Are there any unique instructions I'm missing, or is it just these six?

**Comment by mikebarklage** [comment]
I have updated the instructions for these IDs on dev.

**Comment by Tonylayton1** [comment]
Currently, both 4.G and 4.H are handled the same way for scoring - the correct answer is the button that initiated the unexpected focus. It seems strange that they should be reported differently. 

That said, assuming the above instructions, the following answers should be updated:
4.F: correct failure answers should change from r2_06, r2_09, and r3_01 to r2_05, r2_09, and r3_01 (remove r2_06 and add r2_05)

4.H: correct failure answer should change from r3_01 to r4_02

**Comment by AnnMarieDavis** [comment]
According to the test process, the response for 4.H: should remain r3_01 (it returns to the element that closed the revealed content)


Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by Tonylayton1** [comment]
Oh I see, I was thinking it would be the next object but you're right it wouldn't force focus like that. 

Mike, if you haven't made that change yet, only 4.F should be updated (see above) - the correct answer for 4.H should remain r3_01. I'll update the documents accordingly.

**Comment by mikebarklage** [comment]
OK, I changed the 4.F answer from r2_6 to r2_5.

**Comment by Tonylayton1** [comment]
Verified on Dev

**Comment by drewnielson** [comment]
verified on dev
