### ISSUE TITLE
Data Table language change Lesson 3.

### ISSUE THREAD

**Issue by vprentice** [Section508Coordinators/DHSA-TT-200-A#222]
Issue Type - [X ] Incorrect content

Description
I noticed this morning while going through the Data Tables Lesson 3: Layout Table section how to test that there seems to be slight issue with the text that  is shown in the directions.  Below the ANDi output , the note states that the
 “ You are looking for “Element: role=table, ”Not “Element:<table>.”

![image](https://user-images.githubusercontent.com/34749872/60987207-20b3c500-a30f-11e9-94c8-1f4809ea89b5.png)

The problem with this is that when you test Data Tables, the ANDi output normally shows:
Element: <table>.

For this reason the text needs to be modified or removed.
![image](https://user-images.githubusercontent.com/34749872/60987232-30330e00-a30f-11e9-81cf-f1afeeae6184.png)

Location
https://training.section508testing.net/mod/book/view.php?id=1262&chapterid=3048

**Comment by AnnMarieDavis** [comment]
Both data tables and layout tables may use the element of <table> alone.

Modified the text for clarity adding sentences in parenthesis below in layout tables lesson. 
**Note**: You are looking for “Element: role=table,” not “Element: <table>.” (The use of the ARIA  "role=table"  is used to identify a data table. This element should never be used on a layout table.)
