### ISSUE TITLE
TTv5: Topic 17: Grammatical Error

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#224]
Location: Topic 17 > Summary
URL: https://training.section508testing.net/mod/book/view.php?id=1274&chapterid=3146
Issue:  Under the 'Identifying content' section, under the third bullet, there is a grammatical error. The word 'is' should be removed.  The sentence should read: "...This control allows the user to choose what presentation, or portion of a longer presentation,..."

 
![image](https://user-images.githubusercontent.com/34749031/60999385-0981d100-a329-11e9-971f-12cbb62b3211.png)

**Comment by drewnielson** [comment]
Fixed
