### ISSUE TITLE
Closed captioning text in Firefox

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#225]
The displayed captions when the CC button is activated vary in size and position depending on the browser. Specifically in Firefox, they are very small and significantly below the video player.

**Comment by mikebarklage** [comment]
I noticed that today, but wasn't sure if it was a new bug or had always appeared that way in Firefox...

**Comment by mikebarklage** [comment]
There was some very odd CSS styling applied to it that I think IE and Chrome were ignoring. I commented it out and it looks correct on Firefox.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
@AnnMarieDavis, could you verify this one? Firefox currently isn't working for me on my DHS computer.

**Comment by AnnMarieDavis** [comment]
I am having this issue with the Practice Exam in Firefox - in fact the video did not load until I first click the Pause button and then the Play button. A black screen displayed - so there appear to be some issues with this video in particular.
![Github issue 122 Firefox CC size_Practice Exam](https://user-images.githubusercontent.com/31414225/61140954-79fc2f80-a49a-11e9-8fb7-831ce916dc1a.png)

It is not an issue in topic 2 using Firefox. The cc shows just fine there.
![Github issue 122 Firefox CC size](https://user-images.githubusercontent.com/31414225/61140940-72d52180-a49a-11e9-9535-a47ee80f72ba.png)

I did not test in the final exam....

**Comment by AnnMarieDavis** [comment]
Update with the Final Exam in Firefox...
One CC captioning was a little small, but on the screen and readable...

![Github issue 122 Firefox CC size_Final Exam](https://user-images.githubusercontent.com/31414225/61141513-bed49600-a49b-11e9-819a-c00aaed344a1.png)

The other video's play was quirky - again I had to toggle between Play and Pause to get the video to play all the way through. It would just stop mid-video. but the captions were fine...
![Github issue 122 Firefox CC size_Final Exam2](https://user-images.githubusercontent.com/31414225/61141460-a795a880-a49b-11e9-9775-58caca5ee5be.png)

**Comment by mikebarklage** [comment]
I didn't change anything on the Practice or Final exams because I didn't know we were QAing those.

**Comment by AnnMarieDavis** [comment]
I’m a tad early in looking at those – we are definitely focusing on QA of the practice exams next week as they are planned to be opened up (the 22th ) to people who have completed the class

Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by drewnielson** [comment]
@AnnMarieDavis, let's keep this issue confined just to the incremental exams. If you can confirm that the cc text size is fine in Firefox, then go ahead and close the issue.

**Comment by AnnMarieDavis** [comment]
For the record - No issues with incremental exam video in Firefox.
