### ISSUE TITLE
Force students to identify at least ONE failure on any given exam attempt

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#226]
## Issue Type 
- [X] Other, specify...[ensure students must identify at least ONE failure on any specific exam attempt]

## Description
To ensure that Answers to Topic 1 are always DNA and that students cannot "game" exam attempts, by continually submitting every answer as  "PASS", for any specific **Practice** or **Final** exam attempt, logic should be provided where at LEAST ONE failure is presented that the student must identify. This does not apply to Incremental Exams.

## Location
[Practice Exam and Final Exam only]

**Comment by mikebarklage** [comment]
I believe we're dropping this request in favor of not testing Topic 1.

**Comment by Tonylayton1** [comment]
Please close this if Mike is correct.

**Comment by AnnMarieDavis** [comment]
This was primarily due to the issue with Topic 1. 

But before I close this issue, let me get Andrew to weigh in since there may still be a concern that students will "game" the exam, by repeatedly putting PASS or DNA on every answer until that is true to avoid having to identify failures.

**Comment by drewnielson** [comment]
@mikebarklage is correct - we decided to exclude the Topic 1 tests from the practice and final. Rather than displaying "Not Tested" in the column where you would normally enter results, I think we want the text "Excluded from Exam."

**Comment by drewnielson** [comment]
I see the language is already "Omitted from Exam" which is fine.
