### ISSUE TITLE
Topic 9: Image on-screen text requires modification

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#23]
Location: Lesson 2: Consistent Navigation > Passing examples > Example 2, second image
Other interactive links that are part of the tab order are not included in the on-screen text (i.e., Related, Active Shooter, Avalanche and Bioterrorism).
![Top9_Image On-Screen text (Lesson2-Passing examples page)](https://user-images.githubusercontent.com/34749031/58574830-e84ca180-820e-11e9-95ef-8fc93a76c85a.jpg)

**Comment by KSmithO** [comment]
Not an issue. The menu highlighted is not part of the repetitive navigational elements being shown in this example and do not have any meaning here (other than we couldn't crop them out).
