### ISSUE TITLE
Practice Exam identification and "attempts"

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#230]
## Issue Type
- [X ] Typo/grammar

## Description
[Practice exam template needs updating:
1. The practice exam answer sheets, page title and messages incorrectly identify it as the certification exam.
![Practice Exam Answer Sheet](https://user-images.githubusercontent.com/31414225/61311991-84ce0180-a7c5-11e9-9da8-bbbfb8b14c6c.png)

2. The submission confirmation message incorrectly tells students they have 3 attempts.
![Practice Exam Attempts](https://user-images.githubusercontent.com/31414225/61312004-8bf50f80-a7c5-11e9-8675-248d132b66ee.png)
 ]

## Location
[Section 508 Trusted Tester Course Practice Exam; all answer sheets and messages
http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=159&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=2]

## Expected Behavior / Recommendation
[1. Change web page name to: Section 508 Trusted Tester Practice Exam.
2. Change page title in blue banner to: Section 508 Trusted Tester Practice Exam.
3. Change grey banner to: Practice Exam.
4. Change confirmation text message so every instance of "Certification" is changed to "Practice".  
5. Change any incomplete confirmation messages as needed.
6 .  Remove sentence: Selecting **Submit My Answers** uses one of your three exam attempts.  ]

**Comment by mikebarklage** [comment]
These are all done but the HTML title, because I'm not yet sure where that's set.

**Comment by Tonylayton1** [comment]
Verified what has been updated above.

Similar updates are needed on the Scoring page, but I'm not sure to what extent the text there needs to change. Certainly every mention of "Certification Exam" should instead be "Practice Exam". It also has instructions beginning with a line written in red that appear in the certification exam. do those review instructions need to be in the practice?

**Comment by mikebarklage** [comment]
Issue #231 covers the Scoring page and is waiting for new text to be provided.

**Comment by Tonylayton1** [comment]
Okay then, sounds like it's just the window title that still needs to be updated for this issue.

**Comment by mikebarklage** [comment]
Done for Practice and Incrementals.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified. Will work on providing wording for scoring page and update issue #231
