### ISSUE TITLE
Exam Admin Tool

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#232]
## Issue Type 
- [x ] Other, specify...Admin tool truncates results.

## Description
Admin tool truncates results for pages which makes instructors unable to fully view all the errors a student has made. Even after a page refresh, I was unable to see the results past page 2 topic 5 of the practice exam.

## Location
http://52.23.182.152/dhsv5/scormapi/admin.php?SCOInstanceID=159&KeyID=1566&ExamID=2
Admin Tool to review students answers

## Expected Behavior / Recommendation
There should be no character/line limitation on the failure report.

**Comment by AnnMarieDavis** [comment]
Exam results cut off and are not displayed beginning at page 2 Topic 5 Forms in the Exam Admin module.

Results need to support showing ALL results for a student's first attempt 66 rows of data, 20 table headers, 20 topic headings for 3 pages of the test.   

- To save on space, we can consider removing tables (and headings) for 1 Alternate Version, 3 Flashing, and 20 Parsing since students are not providing responses for these topics.
  

-  This fix also needs to be applied to the Final Exam.

**Comment by mikebarklage** [comment]
I missed one instance of moving 5.G --> 5.H on this admin page, so it was failing, but only when 5.G was NC. I made the fix.

**Comment by Tonylayton1** [comment]
Still seeing this issue. I took the exam multiple times. the admin view on my first 2 attempts is fine, but the admin view on my third attempt breaks when it gets to page 2, topic 5. the admin view for my 4th and 5th attempt both only show the collapsed topic 1. 

the score on all of these is correct however.

Mike, I'll leave my attempts for this one up so you can look through them on the admin tool.

**Comment by mikebarklage** [comment]
The problem here was not number of attempts, but the fact that an entire page was previously answered correctly. The code didn't know how to handle that. I think it's fixed now.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified
