### ISSUE TITLE
Practice page 2 audio only file

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#233]
I just realized the audio file playing here is incomplete. Mike, could you replace it? I'll send you the network link.

**Comment by mikebarklage** [comment]
The correct MP3 file was there, but the code was still playing an old one. It's fixed now.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Can you clarify the location of this file so I can QA the fix?
I think you mean the file on this page (http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?studentEmail=annmarie.davis@associates.hq.dhs.gov&SCOInstanceID=159&examId=2#)

There are 2 audio sounds provided for the successful and unsuccessful connection, but no sound after "...accompanied by 1 long vibration" or "..accompanied by 2 short vibrations." Are we supposed to hear a vibration noise?

**Comment by Tonylayton1** [comment]
No, what you are hearing is correct. Prior to this update, the success and failure tones were not present.

**Comment by AnnMarieDavis** [comment]
Verified
