### ISSUE TITLE
2.A/2.B in practice exam, page 1

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#235]
On page 1, update the auto playing multimedia video to be muted upon loading the page so that auto play will work. Add a mute button to the video player. 

2.A will now be DNA in all instances on page 1 (will add a randomized 2.A in page 2 in a separate issue)

2.B will remain the same, Passes if the play/pause button is present, Fails if it is not. 

Documentation is updated.

**Comment by mikebarklage** [comment]
Code is updated.

**Comment by Tonylayton1** [comment]
video doesn't appear to be updated. does not start muted and has no mute button.

**Comment by mikebarklage** [comment]
Hmm, looks like I lost track of this item and just removed the autoplay. Looking into it now.

**Comment by mikebarklage** [comment]
This also has CC/AD instead of full words, which I don't think is on our list yet but was a change we made to the incrementals.

**Comment by mikebarklage** [comment]
OK, hopefully this is done for real now.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev

**Comment by drewnielson** [comment]
Re-opening. Just noticed that on this version, audio-described version of the file is playing automatically. Video plays automatically, not muted.

Observed here: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?studentEmail=andrew.nielson@associates.hq.dhs.gov&SCOInstanceID=104&examId=2

**Comment by Tonylayton1** [comment]
Good catch. 

Mike, is it possible to have the AD audio be muted and unmuted in step with the standard audio track?

**Comment by mikebarklage** [comment]
I'm checking, but I'm not sure when I'll have an answer. I only mention that because it's 5:30 on a Friday, your time.

**Comment by mikebarklage** [comment]
I have to tentatively answer this with a "no." The videoPlayerAD.js code we're using has interfaces for stop, pause, and resume, but no state for "playing but muted." And I don't see a way to force it from outside the code - it's using the same video element that is marked as "muted" and ignoring that.

It might help if I knew where we got the code? Maybe it has some documentation. Otherwise we might want to think of alternative solutions.

**Comment by Tonylayton1** [comment]
What about forcing the AD to be off when the main audio is muted?

**Comment by mikebarklage** [comment]
That's possible, assuming it doesn't interfere with testing scenarios.

**Comment by Tonylayton1** [comment]
As long as it knows to check whether AD is toggled on or off whenever you unmute, and functions accordingly, it should not interfere with any other tests

**Comment by mikebarklage** [comment]
Currently, a 17.D failure means AD is on by default with no button. Since the video always starts muted, AD will now always be off by default. When 17.D is NC, should clicking Unmute turn on AD? Or should the AD button now appear?

**Comment by Tonylayton1** [comment]
for the 17.D failure, clicking unmute should turn on the AD yes. While the AD is technically off, there is no way to control it independently of the main track, which would still fail 17.D.

**Comment by mikebarklage** [comment]
OK, I've rewritten it so, if AD is off, the code also stores the reason why it is off, and toggles AD accordingly. Give it another try.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
