### ISSUE TITLE
Practice exam group 5 on page 2

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#238]
move all existing failures in group 5 one letter up (5.A becomes 5.B and so-on). 

Add a new failure for 5.A
The "Black" radio button has no visual text label (but does have an aria label of "Black")

Documentation is updated.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
verified
