### ISSUE TITLE
Practice 18.A on page 1

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#239]
Update the transcript zoom failure as was done on the incremental exam topic 18. The transcript text is in a div which causes text clipping when zoomed.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
Mostly good, but I can't see all of the text at 100% in IE and Chrome. Student should be able to see it all at 100%, and the cut off when zooming sometime before 200%

**Comment by mikebarklage** [comment]
It was fine on my browser, so I'm flying a little blind here, but I added another 20px to the height, hopefully that fixes it.

**Comment by Tonylayton1** [comment]
I see the issue now, the width of the div changes with the width of the window. Can it be a set width instead?

**Comment by mikebarklage** [comment]
No, because that changes the div width in an equal ratio to the font size, so the whole text is always visible.

Hmmm...

**Comment by mikebarklage** [comment]
Well, THAT was a journey.

I added some jQuery to automatically resize the div based on the pixel width of the browser window.

If the width is over 1200px, then the transcript div is the default 15% width.

If it's under 1200px, then it's a percentage based on this: (((180/window width)*100) / zoom ratio), where zoom ratio is (current zoom / default zoom).

If you resize the window, it recalculates.

Let me know if that works.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
I'm sorry to report that in Chrome, the Practice Exam is showing the transcript FAILS for resize text. 
![TranscriptZoomChrome](https://user-images.githubusercontent.com/31414225/61971269-a771ce80-afac-11e9-8916-ad507a7f081e.png)

Whatever you did also appears to have broken the default size, too - as it is also cutting off text at the bottom.
![TranscriptDefaultSize](https://user-images.githubusercontent.com/31414225/61971279-ad67af80-afac-11e9-8dc2-29d1a085dacb.png)

**Comment by mikebarklage** [comment]
It's supposed to fail when you're zoomed in that far, as in the 1st image.

For the 2nd image, what's your default zoom level? If someone's default zoom level is 200%, shouldn't they be required to zoom out to 100% to see if the whole text fits?

Although this does imply that I should just assume a default level of 100% and not try to read it from the browser...

**Comment by mikebarklage** [comment]
I've changed the default zoom variable to always be 125%. Does it look any better now?

**Comment by drewnielson** [comment]
Looks good to me. Even if someone's default zoom level is something greater than 100% (and the transcript displays with clipped text), 18,A would still be a fail. I think this is good to go.
