### ISSUE TITLE
Topic 16:Pre-Recorded

### ISSUE THREAD

**Issue by vprentice** [Section508Coordinators/DHSA-TT-200-A#24]
It was noticed yesterday that two of the videos in the course did not play when activated in Internet Explorer 11.0 ; however when testing the same page with Mozilla Firefox the videos played with no problems at all.

https://dev.section508testing.net/mod/book/view.php?id=907&chapterid=1560

**Comment by drewnielson** [comment]
Played around with this and followed a few Microsoft answers/help articles to no satisfactory conclusion. Can't figure out why certain videos will not load or will only load after IE browser refresh. I'm not really inclined to troubleshoot any further. My recommendation would be to direct students to use another browser if they experience the same issue in IE11.
