### ISSUE TITLE
Practice exam 17.E and 17.F on page 1

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#240]
Update these 2 IDs to always be dna regardless of randomization. documentation has been updated.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
Both IDs still showing up as "c"

**Comment by mikebarklage** [comment]
There was still a link between 17.D and 17.E/F, I've now removed it.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
