### ISSUE TITLE
Practice exam 4.F order swap on Page 3

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#243]
On page 4, remove the randomized tabbing order swap on the header links. When 4.F fails, remove r1e04 and r1e05 from the list of failure reasons

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
I don't thin that the "show video checkbox" should be included as a failure for 4.F in this case. When navigating through the page (without selecting/un-selecting the checkbox), the focus order is fine. Suggest removing r4e03 from list of failure reasons for 4.F as well.

**Comment by Tonylayton1** [comment]
4.F should no longer fail when the checkbox toggle forces focus to the top of the screen. Remove r4e03 from the list of failure reasons for 4.F. 

This also means that 4.G and 4.H can be independent of 4.F, 4.A, and 4.C (the three of which are still dependent on each other)

**Comment by mikebarklage** [comment]
Currently, 4.A, 4.C, and 4.F are linked only on pages 1 & 2.

On page 3, the link is between 4.A, 4.F, 4.G, and 4.H. They are all either C or NC together.

Should this become 4.A, 4.G, and 4.H?

**Comment by Tonylayton1** [comment]
No, the only reason 4.A was in the mix is because 4.F was the common factor. 4.F was failing when 4.A failed and also failing when 4.G and 4.H failed. Because the latter is no longer true, 4.A + 4.F are independent of 4.H + 4.G

**Comment by mikebarklage** [comment]
OK, this is updated.

**Comment by Tonylayton1** [comment]
I have 4.F failing by itself now, which shouldn't be possible. It should only fail when 4.A fails.

**Comment by mikebarklage** [comment]
I took the above to mean 4.A and 4.F were independent of each other as well. I've re-added their link on page 3.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
