### ISSUE TITLE
Practice exam 4.G and 4.H on page 3

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#247]
Update the 4.G and 4.H failures on this page to use the same method as in the incremental. Change the "Show video" button to be a checkbox with an appropriate label. Checking it reveals the video and controls, unchecking it hides them.

When 4.G and 4.H fail on page 3, checking or unchecking the checkbox sends focus to the top of the page. 

The failure reason for both 4.G and 4.H should be r4e03.

This will also affect 4.F but I will open a separate issue for that.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
