### ISSUE TITLE
Topic 9: iFrame - Aria-label and ANDI Output have incorrect content

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#25]
Location: Repetitive Content > Lesson 3: Consistent Identification > DNA examples > Example 2 - Interactive Sample iFrame
Both the aria-label and ANDI Output have incorrect content for the iFrame.  It should read: "Repetitive DNA **Example 2** - Interactive Sample"
![Top9_iFrame (Lesson3-DNA examples page)](https://user-images.githubusercontent.com/34749031/58579575-66ae4100-8219-11e9-99e1-c2c733e0aec1.jpg)

**Comment by KSmithO** [comment]
Fixed. ready for re-test

**Comment by HD508Github** [comment]
Re-tested and the Aria-label and ANDI Output are correct for the iFrame. Issue resolved.
