### ISSUE TITLE
Practice exam 12.B page 1

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#251]
When 12.A passes but 12.B fails, update the page title to say "page 1" instead of just "page". 

Any time 12.B fails (whether it is with or without 12.A failing), update the failure reason to just g1e15

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
