### ISSUE TITLE
12.B admin page issue

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#252]
When 12.A passes but 12.B fails, update the page title to say "page 2" instead of just "page". 

Any time 12.B fails (whether it is with or without 12.A failing), update the failure reason to just g1e15

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
None of the pages on my first practice exam had page titles (all failed 12.A), but the correct logic was in the answer sheet that 12.B must also then be a fail.

My second exam attempt appears to have this correct logic, but there is still ONE ERROR on the answer sheet for page 2 (http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=1601 ). The answer is correct, but it is highlighted as incorrect.
![12 B answer sheet false error](https://user-images.githubusercontent.com/31414225/61749728-72c60300-ad71-11e9-84c5-a4ef02c5dbb0.png)

**Comment by mikebarklage** [comment]
According to the docs, the correct response is rO_15 and you chose rO_16, so this is a correct output.

**Comment by Tonylayton1** [comment]
Please verify. The two NC elements shown above are easy to mistake as the same but they are different answers.

**Comment by AnnMarieDavis** [comment]
Verified that both answers are not being required for the same issue.
