### ISSUE TITLE
Practice exam 13.C on Page 3

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#254]
Remove the 13.C contrast failure from the paragraph starting with "With the ZipChip original...", i'm going to use this paragraph for a new issue, and contrast is already covered in 2 other places on this page. 

the failure reasons for 13.C will be just r2e02 and r2e09 (remove r2e04)

**Comment by AnnMarieDavis** [comment]
I don't have an issue with you removing this contrast but I also identified a contrast issue with the skip nav link in the banner on this page with manual testing.  ANDI indicates that the Skip nav link has a failure... 
![13 C Skip nav link contrast](https://user-images.githubusercontent.com/31414225/61469647-93dfbb80-a94d-11e9-9c74-1e513b980bf8.png)

The skip link is not offered as a choice on the answer sheet - different issue that also needs fix...
![13 C Skip to content contrast answer](https://user-images.githubusercontent.com/31414225/61469892-03ee4180-a94e-11e9-9f1c-07bf515b27ae.png)

**Comment by mikebarklage** [comment]
I've updated the 13.C randomizations, not yet dealt with the Skip Nav.

**Comment by Tonylayton1** [comment]
The original issue is verified on dev. Opening a new issue for the skip nav link contrast.

**Comment by AnnMarieDavis** [comment]
The page I tested had a contrast issue with paragraph starting " With two-factor authentication...." The exam correctly identifies this as a FAIL. Not seeing a paragraph "With the ZipChip original...".  Closing the issue.
