### ISSUE TITLE
Practice Exam 13.B on Page 3

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#255]
I was counting 13.B incorrectly, and it does not fail for the same reason as 15.B. 

Update the "With the ZipChip original..." body text with randomizing text as described in the randomization document for page 3. 

When 13.B fails, it should display the alternate text, and the failure reason should just be r2e04

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
this is working, but I should have foreseen that the relevant checklist array item name would need to change. update the checkbox for r2e04 to "Paragraph text under Two-Factor-Options"

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
