### ISSUE TITLE
Incremental Exams not working in Google Chrome 

### ISSUE THREAD

**Issue by douglaszak** [Section508Coordinators/DHSA-TT-200-A#257]
Incremental Exams not working in Google Chrome . Exam fails to launch in Chrome. Student used IE and was able to launch. 
Issue reported by Toya Poudyal

**Comment by AnnMarieDavis** [comment]
Danny Guzman at NE HQ also reported this issue on 7/16 at about 4:00 pm ; the phone call from Toya as as 4:50 pm on 7/16/19 from .  I was unable to replicate the issue even after clearing my cache. Following up with both.

**Comment by drewnielson** [comment]
Thanks @douglaszak and @AnnMarieDavis. Additional information that might be helpful:
* Which incremental(s)?
* Description of actual behavior/observation (e.g., no new window opened, a new window opened but nothing displayed, received some error message, something else?)

**Comment by douglaszak** [comment]
@drewnielson and @AnnMarieDavis  Toya's Reply  Thank you Ann. I got an error on CSS incremental exam. Got an error with connection issue. It is running okay this morning.
Thank you,

**Comment by douglaszak** [comment]
@drewnielson and @AnnMarieDavis . Danny's issue was with the topic 2 exam. He took the topic 2 exam once failed and could not retake the exam . This only occurred in chrome See Danny's reply  Hi Ann Marie, 

Yes, I believe there was a glitch with chrome.  I used internet  explorer and the incremental exam was working properly.

Thanks,

Danny

**Comment by drewnielson** [comment]
Thanks for the follow up. I'm going to close the issue and consider this resolved or a one-time glitch, since both students have been able to move past it, and we don't really have enough info or ability to replicate the issue.
