### ISSUE TITLE
Practice Exam Answer Sheet for ZipChip Data and Security

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#260]
## Issue Type 
- [X] Incorrect content

## Description
In Region 4 of the answer sheet, "Show video" is described as a checkbox, but appears as a button on the page.
![4 E answer sheet Region Practice Exam](https://user-images.githubusercontent.com/31414225/61404563-b0c0b400-a8a5-11e9-8f2e-585c5c2322b1.png)

## Location
http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=159&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=2
ZipChip > Data and Security answer sheet > Topic 4.E > Region 4 

## Expected Behavior / Recommendation
Rename answer choice to Show video button.

**Comment by Tonylayton1** [comment]
It has been changed to a checkbox. New attempts after clearing your exam data should reflect this change.

**Comment by AnnMarieDavis** [comment]
Verified
