### ISSUE TITLE
Practice Exam message - table errors

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#262]
## Issue Type 
- [X] System Bug (the course doesn't function properly)

## Description
When students receive a message about the Test IDs they have missed, the description of the IDs does not match the test process.  

## Location
Practice Exam student notification

## Actual Behavior / Observation
Partway down the table identifying the student errors, the description of the errors does not match the test ID. Once that occurs, none of the Test IDs appear to match. 

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
This occurred both prior to the Practice Exam updates and when I retook the exam.
![StudentNotification](https://user-images.githubusercontent.com/31414225/61477452-45d2b400-a95d-11e9-98d8-7f3bf2c460d6.png)

**Comment by mikebarklage** [comment]
It's a little tough to test, but I think this is fixed. There was a bug in one of the sorting algorithms left over from v4, introduced when we switched from a 1.x.x ID format to 1.x.

**Comment by mikebarklage** [comment]
A good future enhancement would be to replace that whole section of JS code in the scoring section with something simpler than makes more sense. It's overly complicated right now.

**Comment by Tonylayton1** [comment]
Verified on Dev

**Comment by AnnMarieDavis** [comment]
verified
