### ISSUE TITLE
Birds_Sample.wav file missing (404 Error)

### ISSUE THREAD

**Issue by carlosandrews** [Section508Coordinators/DHSA-TT-200-A#264]
## Issue Type 
- [x] System Bug (the course doesn't function properly)

## Description
On this incremental exam page, the audio source for birds_sample.wav is missing (error 404).

## Location
Link: https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page3_main.php?studentEmail=<email omitted>&SCOInstanceID=487&examId=16

## Actual Behavior / Observation
When using Google Chrome web developer tools
The Console shows an error loading "audio/birds_sample.wav" file not found error.

## Expected Behavior / Recommendation
Either upload the "birds_sample.wav" file or remove the audio source.

**Comment by AnnMarieDavis** [comment]
Can you clarify the URL of the incremental exam or provide the topic # where you encountered this? I don't see a bird audio in the URL listed above.

**Comment by carlosandrews** [comment]
The examId=16 and the SCOInstanceId=487

**Comment by AnnMarieDavis** [comment]
This issue has been fixed,
