### ISSUE TITLE
Practice exam 5.A on page 1 and 3

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#265]
Related to issue #238 

the default answer for 5.A on pages 1 and 3 should be "dna"

**Comment by mikebarklage** [comment]
Updated.

**Comment by AnnMarieDavis** [comment]
Correction to this issue.

1. Page 1 (Page 1: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=1571) answer should be DNA for 5.A. 

2. Page 3 (http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=1571) answers for topic 5 should be:

- 5.A & 5.B & 5.D & 5.E should be PASS, 

- 5.C should be FAIL for the Show Video button,

- 5.F and 5.G should be DNA. The answer sheet marks all DNA except 5.A is C.

**Comment by Tonylayton1** [comment]
Good catch!

Mike, the Show video checkbox should be associated with the "Show video" label so that it doesn't fail 5.C.

I've updated 5.A, 5.B, 5.C, 5.D, and 5.E to default to C in the default answer doc. Please update those IDs on page 3 to reflect that.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
5.A fix is verified.
