### ISSUE TITLE
Practice exam multimedia control names

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#266]
Related to issue #236 please update the button names under the video. Fully spell out AD and CC, adding the on/off indicator to both the visual label and the accessible name for andi. the skip buttons should be called "Skip Back" and "Skip Forward". 

(should match the incremental exam)

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
