### ISSUE TITLE
Practice exam Transcript button on Page 3

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#267]
Possibly related to issue #247 

Tabbing away from the transcript button, either moving forward or reverse tabbing, is moving the middle frame to the top. When student reverse tabs from this button, it skips up to the top frame rather than tabbing through the other video buttons first.

**Comment by mikebarklage** [comment]
I still had the old 4.H failure applied to the Transcript button. I have removed it.

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by drewnielson** [comment]
verified on dev
