### ISSUE TITLE
Practice exam contrast for skip nav link

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#268]
Update the Skip nav link contrast to be above 4.5:1. ANDI is currently detecting a contrast of 3.6:1.

**Comment by mikebarklage** [comment]
I'm unable to replicate this issue - the Skip link appears black on a white portion of the background in my browsers. But I added a color attribute to the main Skip styling, not just when it's focused. Can you let me know if that helps?

**Comment by Tonylayton1** [comment]
ANDI does not flag this so it may have been caught in a previous update. Moving to DHS review to confirm.

**Comment by AnnMarieDavis** [comment]
This does seem to have been caught in a previous update.  I will open a new issue related to color contrast for the disable animation button that "disappears" when it receives focus.
