### ISSUE TITLE
Practice Exam Topic 7 answers  

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#269]
## Issue Type 
- [X] Incorrect content

## Description
Some answers in Topic 7 are not correct on the practice exam.

## Location
Page 1: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=1571
Page 2: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=1571
Page 3: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=1571

## Actual Behavior / Observation
Page 1 Answer sheet marks answer for 7.E as DNA.  The test process says in Evaluate Results “The image of text cannot be replaced with text” and test step 1 clearly indicates to check if the text image is part of the logo or brand name.  This answer should be PASS. 

Page 2 Answer sheet marks answer for 7.E as DNA. The correct response should be PASS due to   Captcha image and logo have text that cannot be replaced.

Page 3 Answer sheet marks answer for 7.E as DNA. The correct response should be PASS due to    the logo has text that cannot be replaced

## Expected Behavior / Recommendation
Change answer sheet to mark 7.E from DNA to C (PASS) for all 3 pages of the practice exam.

## Steps to Reproduce the Issue (if applicable)
Reviewed the test process with Andrew before opening this issue.

**Comment by Tonylayton1** [comment]
Update the default answer for 7.E to be PASS on all three pages.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
