### ISSUE TITLE
Practice Exam Topic 13 

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#270]
## Issue Type 
- [X] Incorrect content

## Description
"Below" is not considered a directional clue.  Pages that contain this word in the practice exam are expecting students to mark PASS for 13.B. This is not correct. When that is the only "directional" clue on the page, this answer should be DNA. 

## Location
Page 1: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=1571

Page 3: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=1571

## Expected Behavior / Recommendation
Page 1 - Change answer on Practice exam answer sheet for 13.B to DNA since the only "directional" clue is "below."
Page 3 - Change answer on Practice exam answer sheet for 13.B to DNA since the only "directional" clue is "below."

**Comment by Tonylayton1** [comment]
Updated the default answers spreadsheet. 

13.B on page 1 should now always be DNA
13.B on page 3 should now randomize between DNA and NC, as opposed to between C and NC

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by AnnMarieDavis** [comment]
Verified on pages 1 & 3
