### ISSUE TITLE
Practice Exam Topic 19 Answers

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#271]
## Issue Type 
- [X] Incorrect content

## Description
Providing links to other pages on a web site at the top and the bottom of the pages is considered ONE method to meet 19.A. In order to pass, another method must be provided: such as a search menu, site link, or TOC pane. 

## Location
Page 1: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=1571
Page 2: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=1571
Page 3: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=1571

## Actual Behavior / Observation
Practice exam answer sheets for pages 1-3 mark 19.A as C, but there are not multiple ways to navigate to other pages on the website.

## Expected Behavior / Recommendation
Change expected answer on the Practice exam to FAIL (or NC) for all three pages (unless another method is provided to these pages.)

**Comment by Tonylayton1** [comment]
In that case, having a compliant example would be a bit of an undertaking at this point. Changing the correct answer to NC would be easy. 

Update the default answer for 19.A on all three pages to FAIL for g1e19

**Comment by mikebarklage** [comment]
Updated.

I also removed an old link between 9.B => 19.A on page 2. We aren't randomizing 9.B there anymore anyway.

**Comment by Tonylayton1** [comment]
verified

**Comment by drewnielson** [comment]
verified on dev
