### ISSUE TITLE
Practice Exam Answer sheet for 5.G and marking 8.A

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#272]
## Issue Type 
- [X] Incorrect content

## Description
Practice exam answer sheet for 5.G is related to timeout issues, not Guidance to correct errors in form fields. The answer for 5.G should be PASS for Page 2.
Time limits are tested in 8.A, not 5.G. 

## Location
Answer sheet for Page 2: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=1571

## Actual Behavior / Observation
The answer sheet for Page 2 for 5.G was looking for students to mark this as NC and select: unable to extend the time limit 10x. Time limits are tested in 8.A, not 5.G. 

## Expected Behavior / Recommendation

1. We recommend grouping all the possible time-out issue for failure in 8.A as ONE possible answer rather than the 3 items listed in the evaluation steps of the test process.

2. The practice exam answer sheet needs to be corrected for 5.G for page 2 to PASS (C).

**Comment by Tonylayton1** [comment]
Could you clarify this issue? I don't understand how 8.A and 5.G are being related here as they randomly  fail independently of each other. 

Currently when 5.G fails, it is because the "get code" button failure for not following the correct text box format just says "ID error"

**Comment by AnnMarieDavis** [comment]
I'm including a picture of the answer sheet.  It shows the answer key for 5.G as NC and sites a reason that makes no sense.
![Clarify 272](https://user-images.githubusercontent.com/31414225/61969372-e9f5d400-afc9-11e9-9dfc-0eb277471e6f.png) 
Since 5.G is 3.3.3-error-suggestion, it makes no sense for the answer key to be looking for "the user cannot extend the time limit at least 10x." As we both have noted: 8.A is the only test ID that should be looking for an answer about time limits.

**Comment by Tonylayton1** [comment]
Okay I see now. This is counting the correct answer as correct, but it is showing up wrong on the admin view for some reason. 

![image](https://user-images.githubusercontent.com/52048615/61969963-c15de200-afa9-11e9-8bd5-1bfecb00d5fd.png)

Probably significant to point out that the correct answer is r4_08 from the page specific checkbox array, and the on it is being mixed up with in the admin view is g1_08 .

**Comment by mikebarklage** [comment]
This is fixed.

**Comment by Tonylayton1** [comment]
Verified on Dev

**Comment by AnnMarieDavis** [comment]
Verified
