### ISSUE TITLE
Practice exam answer for Topic 15.A

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#273]
## Issue Type 
- [X] Incorrect content

## Description
The answer for the Practice exam for topic 15 need to be corrected for the answer sheet for page 2.

## Location
Page 2: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=1571

## Actual Behavior / Observation
Page 2 for 15.A - The only pseudo elements marked by ANDI were the images for the pause and mute button.  So I marked the PASS since text also provided the same information.  The NC answer provided in the answer sheet was for “Enter your device type body text”, but ANDI did not markup that text.
![15 A Practice Exam marked NC](https://user-images.githubusercontent.com/31414225/61657967-49827580-ac92-11e9-814e-47e328ad99b0.png)

## Expected Behavior / Recommendation
Change answer to PASS or C on 15.A for page 2 of practice exam.

**Comment by Tonylayton1** [comment]
Actually, 15.A was supposed to fail in this instance but for some reason it isn't.

When 15.A fails on page 2, the sentence "Enter your device type and ID..." should be inserted via the ::before selector. For whatever reason this is not currently working.

**Comment by mikebarklage** [comment]
I had it marked as 15.B in the code for some reason. Fixed.

**Comment by Tonylayton1** [comment]
verified

**Comment by drewnielson** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
See page for an example that should fail for 15.A. Of the 3 items marked with ::before and ::after, the text associated with, "Enter your device type ID..." should fail  http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=1651
