### ISSUE TITLE
Practice exam Page 1 AD not working

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#274]
No AD is playing when it is toggled on. It also is not playing when it is supposed to play with no button. This is new, possible related to changing the video for the 2.A/2.B updates.

**Comment by mikebarklage** [comment]
I can't replicate this. AD plays when I unmute and turn it on, and it even plays when 17.D is false and the other audio track is muted.

**Comment by Tonylayton1** [comment]
This is only sometimes happening. Most recently, it was when there was no pause button, no CC button, and no AD button, but it happened to me when the CC and AD button were present as well. Could it be just when the pause button is missing? Here is the console error I get:

uncaught TypeError: Cannot read property 'addEventListener' of null
    at pauseOnPlayClick (videoPlayerAD.js:348)
    at getCurrentTime (videoPlayerAD.js:204)
    at HTMLVideoElement.<anonymous> (videoPlayerAD.js:187)

**Comment by mikebarklage** [comment]
I changed it so when 2.B fails, the pause button still exists but is hidden. Can you try it again?

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
I'm having trouble with audio description, the video is just freezing at that point.

**Comment by drewnielson** [comment]
Pretty sure that is the expected bahvior - the video pauses in order to
provide enough time for the audio description to catch up and describe the
video before moving on.

**Comment by AnnMarieDavis** [comment]
The AD is now playing again as expected and the bug I was experiencing with the video freezing seems to be resolved.  Though there used to be some AD at the very beginning of the video - guess it was decided to remove that since it's not crucial.

Closing this issue.

**Comment by mikebarklage** [comment]
There are 2 different versions of the AD depending on whether 17.B fails. One of them is missing the first audio segment.
