### ISSUE TITLE
13.C Contrast issue upon focus

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#275]
## Issue Type 
- [x] 508 issue (something is not accessible according to our own test process)

## Description
ANDI requires manual inspection, but identifies the font as black for the Disable Animation button on page 3 of the practice exam.  In Chrome, the text "vanishes" when focus appears on it.  The manual test tool cannot capture the text color using the eye dropper.  Using the font color identified by ANDI, the black text passes. 

![13 C contrast with focus](https://user-images.githubusercontent.com/31414225/61751181-7196d500-ad75-11e9-80a5-41c14b292fd9.png)

## Location
Practice Exam Page 3 Top iframe - http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_frame1.php?KeyID=1601

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
Specify the font color remain black onfocus

.

**Comment by Tonylayton1** [comment]
The button changes to white when focused, can it be updated to stay black when focused?

**Comment by mikebarklage** [comment]
Updated.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
