### ISSUE TITLE
Topic 7 - Image of text in WORKBALANCE logo should be scored as C not DNA

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#276]
## Description
Same logic as in issue #269 - currently answer is DNA for 7.E even though there is an image of text on screen in the WORKBALANCE logo. Result for that specific image of text should be C instead of DNA

## Location
Observed on:  https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=1583
For test result: https://exams-dev1-c.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=507&KeyID=1583&ExamID=7

## Expected Behavior / Recommendation
Change default answer to C

**Comment by mikebarklage** [comment]
Done.

**Comment by AnnMarieDavis** [comment]
Verified on Practice Exam for ZipChip logo (text)
