### ISSUE TITLE
Topic 6 Answer sheet issues PE page 1 

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#278]
## Issue Type 
- [X] Typo/grammar
- [X] Bug

## Description
Multiple issues on the answer sheet for Page 1 on Topic 6. 
1. A dummy link receives focus and would fail for 6.A, but is not a choice on the answer sheet.  Not sure what this is.
![dummy link - no name](https://user-images.githubusercontent.com/31414225/61953298-0a02a480-af84-11e9-89e4-000cefdc022b.png)

2. The buttons options on the answer sheet do not match the buttons on the page.
![Page 1 Answer sheet for buttons](https://user-images.githubusercontent.com/31414225/61953840-6ca87000-af85-11e9-93e3-9802ff2ae097.png)
![Page 1 buttons](https://user-images.githubusercontent.com/31414225/61953866-78943200-af85-11e9-8699-1b5706bb48dd.png)
 

## Location
http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?studentEmail=&SCOInstanceID=159&examId=2

## Expected Behavior / Recommendation
The dummy link may be on the page for use as a failure for CSS. It may need to be either removed or added to the answer sheet.
List correct names of buttons on the answer sheet and ensure the correct answer is being expected.

**Comment by Tonylayton1** [comment]
The dummy link is being used for the forced keyboard trap. 

The mute button did not exist before the most recent round of updates and it is never the correct answer. 

Mike can we add it to the end of the r2 list as r2e09? luckily this won't shift any numbers around. 

Edit- please also move mute to be the last button on the webpage so it matches the checkbox list. Currently it is to the left of the CC and AD buttons.

**Comment by drewnielson** [comment]
For the dummy links, just to avoid confusion for students, let's change the inner text to "dummy link - do not test"

**Comment by mikebarklage** [comment]
This is done.

I also put this on the wrong item, but it belongs here: With this structural change, you might also want to reset your exams on the Admin page.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Fix is noted for the dummy links, but the names of the buttons on the answer sheet still do not match the names of the buttons on the page.  As noted in the screenshots above, the media players buttons on the page being tested are: **Skip Back, Skip Forward**, Transcript and Mute/Unmute. However, Region 2 of the answer sheet presents to the student: **Play/pause button, Rewind button, Forward button,** Transcript button and transcript, **Accessibility  button, CC button, AD button** and Mute button.
Buttons names in bold font are not in sync with each other (between page and answer sheet).

**Comment by Tonylayton1** [comment]
I see, I missed the lede here. We updated the video player button names to match the changes made in the incremental, but I forgot to specify updating the checkboxes in kind. 

Checkbox document updated. Please update the checkbox labels to "Skip Back button", "Skip Forward button", "Closed Captions button" and "Audio Description button"

Lastly, remove the "Accessibility button" from the checkbox list. This will demote the CC, AD, and mute buttons to r2_6, r2_7, and r2_8 respectively. The only ID that is affected by this change is 17.D on page 1, whose correct answers will change to r2_6 and r2_7 (instead of 7 and 8)

**Comment by mikebarklage** [comment]
These changes are done, although it may take some time/effort to force your browser to recache the checkbox lists.

The only Test ID answers I needed to update for this page were 17.D.

Also note that the checkboxes are not dynamic and sometimes don't match the web page exactly, depending on whether certain IDs fail so buttons don't appear.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
