### ISSUE TITLE
8.A Answer Sheet typo

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#280]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar

## Description
1. Missing the word "to" in the answer sheet text
![Answer sheet typo 8 A](https://user-images.githubusercontent.com/31414225/61959384-45f03680-af91-11e9-92e9-0fdea1c2cfa2.png)

2. Text does not match for heading and may cause confusion to students.
![Page2 Answer sheet for heading](https://user-images.githubusercontent.com/31414225/61960547-ae401780-af93-11e9-8e1e-c637166f858d.png)

## Location
http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=159&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=2

**Comment by Tonylayton1** [comment]
1: Add "to" in the g1_07 checkbox label as shown above.

2: Update the webpage header text shown above to "Device Information".

**Comment by mikebarklage** [comment]
Done.

**Comment by mikebarklage** [comment]
With this structural change, you might also want to reset your exams on the Admin page.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
verified
