### ISSUE TITLE
Course Survey

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#281]
- [x ] Incorrect content

End-of-Course Survey
Please complete the end-of-course survey provided via the SurveyMonkey link. The survey is not required to receive credit for this course, but we welcome and encourage your feedback.

I exited the book and it says that I cannot get my completion certificate until the Survey is Marked complete. However I did get an email for OAST saying I had completed the course before I did the survey. :)

**Comment by drewnielson** [comment]
Fixed. course completion certificate availability now dependent on the course summary, not the survey.
