### ISSUE TITLE
4.E-H Incorrect Answers on PE Answer key

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#282]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The Answer Key for http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=1681 is currently presenting the wrong answers for 4.E - 4.H.  All answers are marked DNA on the key, but should PASS and be marked C.

## Location
Practice Exam http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=1681
![Answer sheet for 4 E-H](https://user-images.githubusercontent.com/31414225/62057646-04a89280-b1ee-11e9-84cc-c9825a8b45e8.png)

**Comment by Tonylayton1** [comment]
having difficulty replicating the rest of this issue, but can confirm that 4.E is counting the wrong NC reason as correct. when 4.E on page 3 is NC, the reason should be r4_5 (currently counting r4_3 instead)

**Comment by mikebarklage** [comment]
Updated to r4_5.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified
