### ISSUE TITLE
Form Title element on Student Answer sheets

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#283]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X ] Other, specify...Use of outdated terms in title attribute for forms 
## Description
On hover, the title element displays outdated terms (compliant or not-compliant) instead of what is on the table headers (new terms - Pass and Fail)
![Answer sheet Title attribute vs TH](https://user-images.githubusercontent.com/31414225/62058169-f60eab00-b1ee-11e9-8a7c-d6dd3f30d886.jpg)
This is not a show stopper since students should be able to figure this out, but we should remove the old terms. Considering this an "enhancement" for update after we open the practice exam to students. Other issues are more critical. 
## Location
Student Answer Sheets on Practice Exam

**Comment by Tonylayton1** [comment]
addressed by #308

**Comment by AnnMarieDavis** [comment]
Yes, this is a duplicate of #308  and we will track it there.
