### ISSUE TITLE
practice exam 17.E page 3 default answer

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#285]
for some reason 17.E is showing as c on the answer sheet, but this ID is not tested on this page. It should always be dna on page 3.

**Comment by mikebarklage** [comment]
Fixed.

**Comment by Tonylayton1** [comment]
17.E is fixed but now 17.F is showing as C. it should also always be dna

**Comment by mikebarklage** [comment]
Updated 17.F as well.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
