### ISSUE TITLE
Exam results screen minor issues

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#286]
There are currently 2 minor issues with the results screen:

email links found in the results don't do anything when clicked
the images show up fine in the results screen, but not in emailed results

**Comment by mikebarklage** [comment]
I had used legacy functionality to populate the email link, but now I've replaced that JS call with a simple href mailto element. It had been working for me previously, but check it again and see if it works for you now.

Can you copy the image link here as it appears in your email? My web email app is not cooperating.

**Comment by Tonylayton1** [comment]
the image in the email doesn't grab anything when I copy it and has no properties. It is showing up as the typical red X indicating a missing or broken image.

**Comment by mikebarklage** [comment]
It's worth noting that the text on the results page is exactly what is sent via email, so the new image there is used in both places. Most email readers will block that image for security purposes unless the user allows it to be displayed.

**Comment by Tonylayton1** [comment]
Ah you're right. I had to allow the image and that's working fine now. missing image is a non issue.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
