### ISSUE TITLE
19.A Multiple Ways passing example for PE

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#288]
## Issue Type 
- [X] Other, specify...no randomization example provided for 19.A

## Description
The answer to 19.A is always the same on the Practice Exam.  The only method to navigate to the web pages is by using links that appear at the top and bottom of the page. This is only one method and is always a failing answer for the practice exam.

## Location
Practice Exam, Topic 19

## Expected Behavior / Recommendation
A passing example needs to be provided for at least one page/iteration of the Practice Exam by adding a navigational menu, search feature, or site index.

**Comment by mikebarklage** [comment]
This was implemented and deployed a couple of weeks ago - all 19.A Practice answers are False.
