### ISSUE TITLE
5.G Incremental - incorrect elements noted in fail

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#289]
Incorrect page elements noted in NC result:
![image](https://user-images.githubusercontent.com/29068131/62149008-c633d600-b2c8-11e9-90af-2a336009c221.png)

Correct NC element should only be "The user cannot reverse the submission, was not presented with an option to review, confirm, or correct information before finalizing the submission, and the page did not check for data input errors or allow the user to correct any errors."

Observed here: 
* https://exams-dev1-c.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=551&KeyID=1801&ExamID=5
* https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page3_main.php?KeyID=1801

**Comment by Tonylayton1** [comment]
mike, this looks very similar to issue #272 from the practice exam. same ID too.

**Comment by drewnielson** [comment]
Sorry, I think I confused 5.G with 5.H. The first element ("The user cannot reverse the submission...") would make sense as a correct response for 5.H, but not 5.G. Is the wrong answer sheet being presented to students? Can you confirm correct answer sheet and correct elements?

**Comment by drewnielson** [comment]
@mikebarklage and @Tonylayton1 if possible, let's try to expedite this fix. It is creating a fair amount of confusion for students/instructors.

**Comment by drewnielson** [comment]
Looked at this again, and it appears that the admin tool is presenting correct answers that are not even available to students on their answer sheet, so it might just be that the admin tool is pulling from the wrong response set, even if the answers are scored correctly for students.

**Comment by Tonylayton1** [comment]
I can confirm. The correct answers are r2_5, r2_6, and r2_11 from the page 3 checkbox array, and the answers being displayed are rO_5, rO_6, and rO_11 from the global checkbox array

**Comment by mikebarklage** [comment]
The answers are in the DB correctly, it does seem to be a display issue.

**Comment by mikebarklage** [comment]
The fixes I made to the admin page on Dev should have propogated over on Wed and probably fixed this. However, I don't have permission to view the admin page on Pilot Dev. Can someone check and see?

**Comment by drewnielson** [comment]
Sorry Mike, I just added you to the admin tool in production. You should see it on your dashboard now when you go to https://training.section508testing.net.

Looks fine in dev, but in production, still seeing the elements from the global checkbox array for 5.G:

![image](https://user-images.githubusercontent.com/29068131/62390981-989d9580-b531-11e9-8eee-a9ef4e6c6d56.png)

**Comment by mikebarklage** [comment]
It has the correct answers in my browser. Maybe a cache refresh?

**Comment by drewnielson** [comment]
Doh - yep, that did it. Sorry to blow it out of proportion. Closing the issue.
