### ISSUE TITLE
11.A answer sheet

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#292]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X] Other, specify...Confusing text for students on answer sheet

## Description
Students are confused by the options on the answer sheet for 11.A and 11.B. 
**Current for 11.A:** The default primary language is not correctly specified per IANA.
**Suggested Change to:**  No primary language is specified for the page or the specified language is not a valid code from IANA.

**Current for 11.A:** The identified language in the lang attribute does not match the default human language for the page.
**Suggested Change to:** The IANA code is valid, but is not the correct code for the language that is the primary language on the page.

For 11.B we are really should be asking students the same questions for a specific part of the page, but the answer sheet is not presented that way.  Instead students are asked to just identify the section of page with the failing language part. They are not being asked the 2 evaluation questions in the test process -  WHY it fails.
 

## Location
Incremental Practical Exam and Practice Exam

**Comment by Tonylayton1** [comment]
the issue with 11.A seems straightforward and we can change the text on those checkboxes. Please clarify the issue with 11.B

**Comment by AnnMarieDavis** [comment]
The answer sheet for 11.B is currently asking students to identify the phrase that fails. However, when there is a language that is different from the default language of the page, the test conditions are the "same" as for the language of page.  1. the language of the segment is correctly specified per IANA and 2. the identified language matches the language of the segment.

**Comment by AnnMarieDavis** [comment]
Suggested wording for 11.B answer sheet:
- The language for the content _segment _that differs from the primary language of the page is correctly specified per IANA.
- The identified language in the lang attribute correctly matches the human language for the content segment.

**Comment by Tonylayton1** [comment]
I added issue #312 based on the final exam issue for 11.B. This also changes the wording of those 2 checkboxes on the checkbox list to be simpler and to apply to both 11.A and 11.B. Please confirm that #312 addresses the issue adequately.

**Comment by AnnMarieDavis** [comment]
In looking at this again, I'm concerned that the language will still be confusing to students. We get a lot of complaints about not understanding the distinction between the answers. Not your fault, since I know the language comes from the test process, but can we change this across the board to:
Page language
There is no specified language of the page or segment or it is not correctly specified (a valid code) per IANA

The identified language in the lang attribute is a valid IANA code, but does not match the language for the page or segment
