### ISSUE TITLE
Length of answer sheet

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#293]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X] Other, specify...some answer sheets are too lengthy and include NA options

## Description
Some answer sheets are too lengthy and include multiple columns of text that students must read. The options include many things that do not pertain to the question being evaluated. 

## Location
Incremental Practical, Practice, Final Exams

## Expected Behavior / Recommendation
Break these answer sheets into smaller pieces and provide 5 or less reasonable options

**Comment by Tonylayton1** [comment]
Is this the same as #303 ?

**Comment by AnnMarieDavis** [comment]
OAST verified
