### ISSUE TITLE
13.B Failing Example of Shape alone

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#294]
## Issue Type 
- [X] Other, specify...Confusing Example

## Description
Good morning Ann Marie and Andrew,
I have a comment/suggestion about Use of Sensory Characteristic, example 2, FAIL.  I think this sample is a little ambiguous, and it would be really helpful it if is revised

The explanation about the FAILS says:
When a pamphlet title is in stock, it is marked with an image of a check mark. When it is temporarily out of stock, it is marked with an image of an X. 

There is also some text saying check mark means available, and X means out of stock right below the table with all the items.

See my comments below with the reason why this could be confusing:
•	Shapes are clearly different, so if ALT TEXT has meaningful meaning, this would be OK for AT users (blind users)
   o	If Alt Text for check mark says: "Available" or even “ Check Mark, then this is OK. (On the text above it was clearly specified what CHECK Mark and X means)
   o	If Alt Text for X says: “Not available” or even “X”, then this would be ok. 
   o	AT users would be able to clearly distinguish each item
•	Sighted users can also clearly distinguish each shape:  “X” is completely different than the “V “(check mark).

So, I think this FAIL sample it is not very clear..

Thanks for looking into this! Regards, 
Rosana

## Location
Topic 13, Lesson 2, Failing Example 2
https://training.section508testing.net/mod/book/view.php?id=1258&chapterid=3016

## Expected Behavior / Recommendation
Italicized text added: The Centers for Disease Control and Prevention allows the purchase of bulk quantities of pamphlets about smoking. When a pamphlet title is in stock, it is marked with an image of a check mark. When it is temporarily out of stock, it is marked with an image of an X. There is no other indicator besides the shape to help users of AT identify if an item is available or out-of-stock. _The images do not include equivalent alternative text to distinguish them._ Testers should mark 1.3.3-sensory-info as FAIL.

We may consider adding a future example that uses button shape as appears in WCAG. (http://www.w3.org/WAI/WCAG21/Techniques/failures/F14.html#related)

A user is completing an on-line survey. There are three buttons at the bottom of the survey form. The instructions state, "Press the square button to exit the survey without saving, Press the triangle button to save in-progress survey results. You may return later to complete the survey. Press the round button to submit the survey results." A screen reader user or a user unable to distinguish shapes cannot determine which button is square, triangular, or round. The buttons must have additional information to indicate their functions or their shapes.

**Comment by AnnMarieDavis** [comment]
Andrew, please close once you verify the change made and determine it is sufficient.

**Comment by drewnielson** [comment]
Looks good. Thanks Ann Marie!
