### ISSUE TITLE
Practice Exam Confirmation dialog

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#295]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [X] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The confirmation message for the practice exam tells users to select "Yes", but the button is labled "OK"
![Practice submission confirmation](https://user-images.githubusercontent.com/31414225/62541364-a865f400-b827-11e9-9fe3-c2edc2f644e4.jpg)

## Location
Practice Exam confirmation dialog box

## Expected Behavior / Recommendation
Change text in message rather than button name. New sentence should read: Select OK to receive your score.

**Comment by drewnielson** [comment]
Does “Yes” or “OK” depend on what browser you are using?

**Comment by AnnMarieDavis** [comment]
It is the same behavior in Chrome and Firefox.

**Comment by mikebarklage** [comment]
It's also "OK" in IE.

I have updated this text in the Practice and Final exams.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
