### ISSUE TITLE
Practice Exam - Course Introduction Issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#296]
Location: Course Overview and Structure page
URL: https://training.section508testing.net/mod/book/view.php?id=1421&chapterid=3259
Issue:  Under the Test Process (Topics 2, 4-19) section, the third bullet reads confusingly.  It should read as: “…to determine when a test condition does not apply, passes or fails…”

![image](https://user-images.githubusercontent.com/34749031/62622419-4e7b3200-b8ec-11e9-9984-5c7da44293b3.png)

**Comment by drewnielson** [comment]
fixed
