### ISSUE TITLE
Practice exam  congrats

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#299]
Text runs off of the white area into the blue background where it is almost unreadable.

**Comment by drewnielson** [comment]
Doh - thought we fixed that. 

@mikebarklage, and @Tonylayton1, looks like we still have an issue with the text running into "off the page" into the blue background on the congrats screen.

**Comment by AnnMarieDavis** [comment]
I modfied the text since we want students to still know the items they missed. We will also need the results to display in these messages, just as they do for the "Nice Try" message
[Congratulations Practice.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3497927/Congratulations.Practice.docx)

**Comment by Tonylayton1** [comment]
Do we know if this student exited and returned to the course to get this error? This is what I was experiencing with issue #287 which is still unresolved, but I only experienced this after exiting the exam at the congrats screen and opening it again. Upon initially reaching the congrats screen, it displayed correctly.

**Comment by smh243** [comment]
I do not remember if I exited and came back in. I am thinking not, but would not swear to it.

It did not show up on the pages where I had not passed the exam. The missed questions feedback was there.

Once I passed the exam the missed questions info was not available.

Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>.
[cid:image006.jpg@01D55270.006484A0]
“It’s only when you make the process your goal that the big dream can follow.” Oprah Winfrey.

**Comment by AnnMarieDavis** [comment]
Mark,

To be honest, I don’t think the message when you pass the Practice Exam includes items you missed.  I realized earlier this week that students would need to know that information to be able to review those topics before taking the final exam. We are in the process of correcting that – and you will have this information for the Final Exam when you pass it as well.

I looked at your answer sheet for the Practice Exam and you had some errors in
4.A, 4.D
5.B, 5.C, 5.E
7.E (missed on 2 pages you tested)
10.B (missed on 2 pages you tested)
12.A, 12.B, 12.D
17.E, 17.F (be sure you are only testing synchronized media here, not audio only or video only content)
19.A  (missed on all pages you tested – Note that having links on the top and bottom of the page is only 1 method to access pages in the website. Even when that 1 method is applied in 2 places it is a FAIL -- you must have 2 methods of access to pass this.  Review that section to see what other navigation methods might be used.)

Hope this helps, Mark!

Kind Regards,
Ann Marie

Ann Marie Davis
Senior Section 508 Technical Specialist
Department of Homeland Security (DHS)
Office of Accessible Systems & Technologies (OAST)
Phone #: 202-815-5428
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>
Accessibility Helpdesk  |  Phone#: 202-447-0440  |  Fax #: 202-447-0582
accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited. If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.

**Comment by smh243** [comment]
Thanks so much,
That was very helpful!
Mark

Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>.
[cid:image006.jpg@01D5541F.21E73EA0]
“It’s only when you make the process your goal that the big dream can follow.” Oprah Winfrey.

**Comment by Tonylayton1** [comment]
I'll add this to issue #287 so there are not 2 issues tracking the same bug.

**Comment by AnnMarieDavis** [comment]
OK - we will track this with #287
