### ISSUE TITLE
Topic 4: Lesson 6: Failing examples missing hyperlinks

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#30]
https://dev.section508testing.net/mod/book/edit.php?cmid=1245&id=2091

Example 1
<p>Select this link to see why this page fails for 2.4.3-focus-order-meaning.</p>
http://dhsconnect.dhs.gov/org/comp/mgmt/ocio/oast/authoring/TT%20Course%20Images%20and%20Videos/Forms/AllItems.aspx?RootFolder=%2forg%2fcomp%2fmgmt%2focio%2foast%2fauthoring%2fTT%20Course%20Images%20and%20Videos%2f4%20Keyboard%20and%20Focus%2f4%2eG%2e%20Fail%201&FolderCTID=0x012000EC2E8A35DA0BF14BADE8CC8E6C48B47F

**Comment by drewnielson** [comment]
All code sample links added throughout Topic 4
