### ISSUE TITLE
Practice exam completion.

### ISSUE THREAD

**Issue by smh243** [Section508Coordinators/DHSA-TT-200-A#300]
I completed the Practice exam yesterday 8/12/2019. 
If I go into the course it shows all the boxes as check.
The dashboard still shows a status of Enrolled and completed Not available.
If my memory serves me correctly the other courses in the Dashboard updated almost real time.
Not sure if this is really an issue.

**Comment by drewnielson** [comment]
Yes, definitely an issue. Working on a fix, and will have resolved by the time the Final exam is ready.

**Comment by smh243** [comment]
Do you have a prospective ETA on the Final exam?


Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>.
[cid:image006.jpg@01D551C6.C8ADDE70]
“It’s only when you make the process your goal that the big dream can follow.” Oprah Winfrey.

**Comment by drewnielson** [comment]
Fixed original issue (completion status on dashboard). 

We're shooting for next Friday for the release of the final/certification exam.

**Comment by smh243** [comment]
Awesome, Thanks

Mark Hamrick
eLearning Producer
DHS Certified 508 Trusted Tester 300817
[JAWS Certified, 2019]<http://www.freedomscientific.com/Certification>
207 623 8411 x2291
EES eLearning Division
Department of Veterans Affairs

To learn more about EES, visit vaww.ees.lrn.va.gov<http://vaww.ees.lrn.va.gov/>.
[cid:image006.jpg@01D5528E.27ED8990]
“It’s only when you make the process your goal that the big dream can follow.” Oprah Winfrey.
