### ISSUE TITLE
Modify text for failure option on 7.E

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#302]
Current failure option: "Qualities table text"
Change to : "Qualities table text (all four instance of text next to the images)"

Some students have been confused about what item to select for the image of text failure. Students have been selecting each of the options for Qualities table Image 1, Image 2, etc.. Hopefully the above modification will clarify the text refers to all four instances.

**Comment by Tonylayton1** [comment]
Mike, this is for website 1 page 1, checkbox r2_6. Expand it to say "Qualities table text (all four instance of text next to the images)" as specified above. I've updated the relevant document.

**Comment by mikebarklage** [comment]
Updated for exam topics 2, 6, 7, 9, 17, and 18.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
