### ISSUE TITLE
Revise answer sheets that do not contain Regions

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#303]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X] Other, poor user experience particularly for users of screen readers

## Description
Answer sheets with multiple check boxes (but no regions to organize the choices) provide columns of possible answers. Students must read every long description provided by each checkbox label to find their answer. This is very daunting, confusing, and particularly unfriendly for students using screen readers.  

## Location
This impacts answer sheets for topic 2, 8, 9, 11, 12, 15, and 19 in the Incremental and Practice Exams

## Expected Behavior / Recommendation
One of the following solutions are requested to redesign the answer sheets:

- Only the applicable options displayed for the topic (for example on this image above, only the choices that apply to Topic 9)

- The choices organized in a data table or with navigable headings that group them by Topic to make them easier to find.

- Another option that is mutually agreeable.

**Comment by Tonylayton1** [comment]
This is the global checkbox list which is the same across all pages and exams. It is used for IDs where selecting the visual elements found on the webpage would not make sense to answer the question. 

Option 1 would likely be a huge effort (Mike please correct me if I'm wrong) but I imagine dividing the checkbox list up with headings like in the page-specific checkbox lists should be relatively straight forward. I've attached a word document attempting to break up the list a little bit, would this organization work?

[global_checkbox_list.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3498945/global_checkbox_list.docx)

**Comment by mikebarklage** [comment]
Option 2 might not be less work. The "r" values in the checkbox names are meaningful in the output of the page (r1, r2, etc). The checkbox page in question is rO, for Other. I'd have to add some other way of marking them into groups, in the data structure and/or in the JS code.

FWIW, aside from some tweaks, this is the same checkbox page as in the v4 exam.

**Comment by AnnMarieDavis** [comment]
Yes, I realized this was wrong when I was testing earlier, but it wasn’t a high priority… but we really should make it right.

Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by mikebarklage** [comment]
Updated as part of same task in JIRA.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev for practice and incrementals
