### ISSUE TITLE
instructions text for incremental and practice

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#306]
Issue in final exam was made to update the instructions found on each test ID list page to 

"Select Test This Page to open a new window with the content to be tested. You will need to open the ANDI tool to perform applicable tests. Report the test results for this topic using Enter Results (or Modify Results) below. When done, navigate to the next page to submit your results.

This was not made for the incremental and practice exams, but seems like it should apply. please advise.

**Comment by Tonylayton1** [comment]
mike I'm going to assume this should be the same. 

Make sure the instructions on the practice pages 1, 2, and 3 respectively match the updated instructions from the final. Each incremental should have the instructions from page 3 of the final. Note that incremental 9 has extra instructions below this, which should remain.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
Incrementals are good. Practice pages 1 and 2 still need the 1st and second sentences updated (where it mentions andi. They should be the same as page 3 except for the last sentence

**Comment by mikebarklage** [comment]
Ah, right - fixed.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Sometimes the button is named "In Progress"- perhaps we should change the sentence 
"Report the test results for this topic using Enter Results (or Modify Results) below."

Suggested change to that sentence only:
Report test results for this page using Enter Results; the button is alternately named In Progress or Modify Results depending upon your completion level.

**Comment by mikebarklage** [comment]
Is this a confirmed change? I only ask because it would involve updating 22 files...

**Comment by AnnMarieDavis** [comment]
OAST will accept this as is.

**Comment by AnnMarieDavis** [comment]
Too much effort for diminished return to implement the requested change.  Closed.
