### ISSUE TITLE
Title element for radio buttons on Answer Sheet

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#308]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [x] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
OAST **sampled** Practice and Incremental exam answer sheets. The title attribute is incorrect - still using C and NC (rather than PASS and FAIL) to identify radio buttons. This is currently known to be incorrect on:

- Incremental exams for Topic 13 and 17 and 

- Practice Exam topic 5 and 15

Was able to verify buttons are correctly identified on 

- Incremental Exam Topic 9 

## Location
All answer sheets for Incremental and Practice Exams

**Comment by Tonylayton1** [comment]
Please update the titles on the radio buttons in the incremental and practice to reflect their updated column names. (same thing that was done in the final)

**Comment by mikebarklage** [comment]
Are you still seeing this anywhere? This should have changed for all exams when it was originally updated, and this may have been caused by partially cached JS code.

**Comment by AnnMarieDavis** [comment]
Yes, I see this on almost every answer sheet.
![5 Title attributes on answer sheet](https://user-images.githubusercontent.com/31414225/63583220-93e46400-c568-11e9-8eed-2f46409223a7.jpg)

**Comment by mikebarklage** [comment]
I can't replicate it:

![5titles](https://user-images.githubusercontent.com/50433189/63610027-40d0d800-c58d-11e9-89ac-0bbc75a62fa9.jpg)

**Comment by Tonylayton1** [comment]
This looks okay on my end as well, please clear cache and reset exam and try again

**Comment by drewnielson** [comment]
Looks OK for me too.
