### ISSUE TITLE
interference

### ISSUE THREAD

**Issue by dderouchey** [Section508Coordinators/DHSA-TT-200-A#309]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [x] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
['How to test' steps #4 and#5 are missing or this is a typo.]

## Location
[https://training.section508testing.net/mod/book/view.php?id=1288&chapterid=3209, Topic 1, Lesson 5: Non-Interference, How to test]

## Actual Behavior / Observation
[The steps are numbered 1, 2, 3 and 6. There is not a number 4 or 5.

![topic-1-lesson-5-how-to-test](https://user-images.githubusercontent.com/51759875/63204002-9d456c00-c050-11e9-9d27-27d46f59c552.png)
]

## Expected Behavior / Recommendation
[Need to determine if this is a typo or if content is missing.]

## Steps to Reproduce the Issue (if applicable)
[Go to the page.]

**Comment by drewnielson** [comment]
@AnnMarieDavis, did you already fix this? I don't see the same issue.

@dderouchey, do you still see the numbering discrepancy?

**Comment by dderouchey** [comment]
Yes, I still see the discrepancy. The numbers 4 and 5 are missing in the step process as of 8/27/2019.

![topic-5-missing-step-numbers](https://user-images.githubusercontent.com/51759875/63790499-9e7b6200-c8b6-11e9-8147-53198953b58a.png)

**Comment by drewnielson** [comment]
Hmmm. @dderouchey , what browser and version are you using?

**Comment by dderouchey** [comment]
Firefox Quantum 68.0.2 (64-bit)

**Comment by drewnielson** [comment]
Strange. Hard coded the value for the list item number. Should be fixed now. @dderouchey, would you mind checking again? Might need to clear your cache.

**Comment by dderouchey** [comment]
The numbering is good now.
![topic-5-missing-step-numbers-02](https://user-images.githubusercontent.com/51759875/63811589-195b7180-c8e5-11e9-8b01-15c20e693086.png)

**Comment by drewnielson** [comment]
Great. Thanks for checking.
