### ISSUE TITLE
Practice exam: Autoplaying audio page 2

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#310]
In chrome, the auto-playing audio will not play if I open page 2 directly. If I navigate to page 2 from one of the other 2 pages it works fine. 

In firefox, the auto playing audio will not play at all. If I toggle play/pause a few times it will play.

**Comment by Tonylayton1** [comment]
Same issue with chrome and FF in Final, may need to add instructions.

**Comment by AnnMarieDavis** [comment]
Add text to the answer sheet page like image below.
![Topic  2 Answer sheet](https://user-images.githubusercontent.com/31414225/63700140-32362b00-c7f0-11e9-822e-bff24d6781aa.jpg)
The link should open a new tab or window with the following instructions.
[Topic 2 Auto-play.txt](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3541747/Topic.2.Auto-play.txt)
[Topic 2 Enable AutoPlay.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3541756/Topic.2.Enable.AutoPlay.docx)

**Comment by mikebarklage** [comment]
This has been added to the PHP script that generates these sub-menus.

**Comment by AnnMarieDavis** [comment]
Thanks for the quick turnaround on this.  The quotes are not displaying properly in the html... this version of the text file replaces the quotation marks with &quot;
[Topic 2 Auto-play.txt](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3542364/Topic.2.Auto-play.txt)

**Comment by mikebarklage** [comment]
Updated.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
