### ISSUE TITLE
5.E answer sheet error on Practice Exam

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#313]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The answer to 5.E is not correct.  The answer sheet for a student indicates the answer is C, but there are no form elements on the page.  the student's answer of DNA should be correct.

## Location
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=4174

https://exams-dev1-c.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=844&KeyID=4174&ExamID=2

**Comment by Tonylayton1** [comment]
Update default for 5.E on page 1 to "dna"

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
OAST verified.
