### ISSUE TITLE
4.G Error on Practice Exam answer sheet

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#314]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The answer expected for Page 2 of the practice exam is incorrect.  There is an unexpected change of content when focus lands on the Original radio button.  The answer sheet is expecting a PASS answer, but instead it should be: Original Text and associated radio button

## Location
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=4174

https://exams-dev1-c.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=844&KeyID=4174&ExamID=2

**Comment by Tonylayton1** [comment]
When 5.E fails for r4e04, 4.G should also fail for the same reason. 4.G wasn't used on this screen yet so it should just need to be linked to 5.E.

**Comment by drewnielson** [comment]
To me, it looks like Ann Marie might have just confused the behavior of the keyboard trap in the form elements above the radio button in question with the behavior of the radio button. I don’t think that the is an on-focus-related issue (so 4.E does not apply to the radio button behavior). I also disagree with the notion that 4.G would apply. The revealed content test is meant more for menus, pop-ups, dialogs, and I think this content would be too obscure to include for 4.G. I would say, just keep it a 5.E (form-related change in content) failure and do not add the link to 4.G (or 4.E). Closing issue and moving to "deployed."
