### ISSUE TITLE
17.B label on Answer Sheet for failure of AD

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#316]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
![17 B AD button desc issue](https://user-images.githubusercontent.com/31414225/63592986-e7fb4280-c580-11e9-847b-847cde160924.jpg)

Neither the Video checkbox nor the Audio Description button checkbox identifies a failure when the **content** of the AD is inadequate.

## Location
http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=160&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=1

## Expected Behavior / Recommendation
Change name of button from "Audio Description button" to "Audio Description button and description content"

**Comment by Tonylayton1** [comment]
updated to include content in the text label based on similar issue in jira.

**Comment by drewnielson** [comment]
verified on dev for both incremental and practice exam page 1
