### ISSUE TITLE
11.A and 11.B Language text

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#319]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [x] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Students continue to be confused by text on the answer sheet.

Change the Page language options for the checkbox

- There is no specified language of the page or segment or it is not correctly specified (a valid code) per IANA

- The identified language in the lang attribute is a valid IANA code, but does not match the language for the page or segment

**Comment by Tonylayton1** [comment]
documentation updated, please change the 2 checkboxes for language to match the text above.

**Comment by mikebarklage** [comment]
Updated, will appear upon re-caching.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified in Practice Exam
