### ISSUE TITLE
Practice page 1 17.A and B reasons

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#321]
When 17.A fails, change the reason to r2e06

When 17.B fails, change the reason to r2e07

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
I've tried to take the Practice Exam several times and cannot get a failing example to test this with the randomized options being presented.

**Comment by Tonylayton1** [comment]
These are both says 2_1 again on the answer sheet. not sure what happened.

**Comment by mikebarklage** [comment]
Fixed.

In the stream of tickets across 3 exams, I reset the practice exam answers because I thought I had changed them by mistake.

**Comment by Tonylayton1** [comment]
verified on dev again

**Comment by drewnielson** [comment]
verified on dev for incremental and practice exams
