### ISSUE TITLE
6.B Incremental Practical Exam answer

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#323]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The answer sheet is marking 6.B as PASS on the page version
http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=dummy@anywhere.com&SCOInstanceID=175&examId=6 

## Location
Topic 6 incremental practice exam
http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=dummy@anywhere.com&SCOInstanceID=175&examId=6 

## Expected Behavior / Recommendation
6.B should be DNA on the page version as there is no "disable updates" link on this version of the page.
http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=dummy@anywhere.com&SCOInstanceID=175&examId=6 

6.B should be C (Pass) when the version has a disable updates” link.
6.B should be NC (Fail) when the page displays the version where the “disable updates” link also causes a line of text to appear in addition to actually disabling the auto updates.

**Comment by Tonylayton1** [comment]
When the button is not present (when 2.C fails), 6.B should be "dna" instead of "c". documentation is updated.

**Comment by mikebarklage** [comment]
Done.

**Comment by drewnielson** [comment]
verified on dev
