### ISSUE TITLE
Remove page 3 background image as failure element in 7.A

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#325]
Related to issue #301 in incrementals. 

Quoting Tony's explanation/description:
When 7.C fails, it shouldn't fail 7.A, so these two IDs can be unlinked.

When the logo is a background image, 7.A should no longer be affected, and 7.C is "nc" just as it is now.

**Comment by drewnielson** [comment]
Specific to page 3 of practice exam. Not sure if it affects other pages.

**Comment by Tonylayton1** [comment]
As above, unlink 7.A and 7.C. The banner being background vs foreground should not affect 7.A on the answer sheet.

When 7.A fails, it should only be for r5_4

**Comment by mikebarklage** [comment]
Done.

**Comment by AnnMarieDavis** [comment]
OAST verified
