### ISSUE TITLE
7.C Answer sheet correction

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#327]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The ZipChip text logo is part of the background image on Page 3. 

Answer sheet marks 7.C as **DNA**.  The ZipChip text is a background image. This answer should be: 
•	**FAIL** because running man logo itself is not sufficient representation of the company for the website.

## Location
http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_frame1.php?KeyID=1974

**Comment by Tonylayton1** [comment]
when 7.A is "c" and 7.C is "nc", the background image does not include the zipchip banner like it is supposed to be. (7.C is dna in this case). 

pairs with Ann Marie's comment above, 7.C randomization appears to be broken.

this is related to issue #325 which was updated yesterday.

**Comment by mikebarklage** [comment]
Fixed.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
