### ISSUE TITLE
Final version of email text for practice exam

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#328]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
We eliminated the Q&A sessions and so needed to make updates. Since a change was already needed, other small edits were made.
[Congratulations Practice REVISED.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3551647/Congratulations.Practice.REVISED.docx)

[Nice Try Practice REVISED.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3551801/Nice.Try.Practice.REVISED.docx)

## Location
Practice Exam email messages for Nice Try! (not passed) or Congratulations! (passes) exam attempts.

**Comment by mikebarklage** [comment]
Updated.

**Comment by Tonylayton1** [comment]
verified on dev except the em-dash on the nice try message is missing. Is this okay? it says "Trusted Tester Q&A Question Board" instead of "Trusted Tester Q&A – Question Board"

**Comment by mikebarklage** [comment]
Should be re-added now.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
