### ISSUE TITLE
Keyboard trap

### ISSUE THREAD

**Issue by jrautio** [Section508Coordinators/DHSA-TT-200-A#329]
The video does not run.

**Comment by drewnielson** [comment]
Sorry for not getting to this sooner @jrautio. Just to clarify, are you referring to the video located in [Topic 4, Lesson 3, Failing Example 2](https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2691)?

Unfortunately, I can't identify any issue with the video on my end. Can you give me any more details? What browser are you running, and are you on a computer behind a government firewall/VPN?

**Comment by drewnielson** [comment]
@jrautio, closing this issue since I wasn't able to pin down the problem. Happy to re-open if you can give me a little more info to help identify the specific issue.
