### ISSUE TITLE
Question 9B answer sheet is wrong

### ISSUE THREAD

**Issue by kgreid-oast** [Section508Coordinators/DHSA-TT-200-A#331]
The form to select 9.B failures appears to be incorrect.  It says “Other Failure Condition Reasons.”  I can't continue until this is corrected.

[9B error.pdf](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3556402/9B.error.pdf)

**Comment by drewnielson** [comment]
@kgreid-oast, please clear your browser cache and view the answer sheet again. We pushed out an update just last night to revise how that answer sheet is presented.
