### ISSUE TITLE
7.E Incremental Exam - wrong answer

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#333]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
I am still seeing student incremental exams with the wrong answer.  When the Workbalance logo is a background image, then 7.E is DNA (barring any other images with text on the page). However, if it appear on the page, 7.E should be PASS.  Recent answer sheets expect an answer of DNA where it should be C.

## Location
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=9106

## Expected Behavior / Recommendation
Correct answer sheet for 7.E when Workbalance logo is on the page so DNA is not an option.  It will either PASS since there is no other image with text on the page or it will FAIL if there is another image with text (since we don't provide a way to customize text)

**Comment by AnnMarieDavis** [comment]
![7 E answer sheet](https://user-images.githubusercontent.com/31414225/64170732-d5a1c400-ce1e-11e9-87e9-503f76bb05c7.jpg)

**Comment by drewnielson** [comment]
This is related to issue #276. @AnnMarieDavis, it looks like you marked that as verified on dev, but you verified it was fixed for the practice exam, not for the incremental exam that the original issue related to.

**Comment by drewnielson** [comment]
@mikebarklage, we've had a couple students get tripped up on this one over the past couple days, so let's just deploy this one as soon as it is fixed and verified.

**Comment by mikebarklage** [comment]
OK, default changed from DNA to C on Dev Incrementals.

**Comment by drewnielson** [comment]
Thanks @mikebarklage. Verified on dev.

**Comment by mikebarklage** [comment]
This change has been deployed.

**Comment by drewnielson** [comment]
Thanks @mikebarklage!
