### ISSUE TITLE
5E

### ISSUE THREAD

**Issue by dduncan16** [Section508Coordinators/DHSA-TT-200-A#334]
I am having the same issue with this topic.  I scored a 88% and can't move any further I've read the topic for three days and still stumped please help.

**Comment by smustgrave** [comment]
Same issue here.

**Comment by drewnielson** [comment]
@dduncan16 and @smustgrave, I provided a response in the Q&A question board that might help:
https://training.section508testing.net/mod/forum/discuss.php?d=26#p238

I am also producing a demo to cover the same issue. Please take a look at the Q&A response and let me know (here) if you are still stuck.
