### ISSUE TITLE
Skip to Content link not present on 15.B failure details

### ISSUE THREAD

**Issue by sheribyrne** [Section508Coordinators/DHSA-TT-200-A#337]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
There is no option to select the "skip to content" link for test 15.B, therefore you know that isn't the correct answer

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
Acknowledged - the skip to content link is not available as an option for the 15.B, which would indicate it is not the correct answer. However, we do not intend to include it as a response option for that particular exam/page.
