### ISSUE TITLE
Change needed to answer sheet for 16.B

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#338]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [x] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
There is an issue with the adequacy of the transcript on this test page. The only options are Transcript button or Video.  

## Location
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=4150

## Expected Behavior / Recommendation
Change this answer sheet to provide checkbox labeled with following or similar text: "Transcript button and transcript content"

Please evaluate where this change may need to be applied in other exam versions. 
Consider whether there can be a global change to the answer sheets or whether this would introduce other issues.

**Comment by Tonylayton1** [comment]
inconsistency in the exact wording of transcripts across pages. For all three checkbox lists in website 2, update the name of the transcript checkbox to say "Transcript button and transcript window contents" - documents are updated

**Comment by mikebarklage** [comment]
Updated on Dev, change will appear when your exam data cache has refreshed.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
