### ISSUE TITLE
Topic 5: Border Displays after skip navigation

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#34]
Location:  Forms > Topic Introduction page
After the 'skip to main content' is selected, a border displays at the top of the main content prior to focus going to the first interactive element.  The border display did not occur in the DEV environment during 508 testing.  This issue exists globally throughout Topic 5.
![Top5_Border Display (Topic Introduction page)](https://user-images.githubusercontent.com/34749031/59045094-62070f80-884d-11e9-9d3c-f71867e10b40.jpg)

**Comment by drewnielson** [comment]
@HD508Github I'm not sure this is really an issue. What Test ID are you failing this under?

**Comment by HD508Github** [comment]
Agreed, not really an issue; but I noticed it didn’t appear while testing in the DEV environment.  It looks like some added code got inserted.

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D3A09F.E6927B00]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.

**Comment by drewnielson** [comment]
Pretty sure it was like that in Dev too. 

On Jun 7, 2019, at 6:20 AM, HDiallo <notifications@github.com> wrote:

Agreed, not really an issue; but I noticed it didn’t appear while testing in the DEV environment. It looks like some added code got inserted. 

Kind Regards, 
Halimatou(Halima)Diallo 
Sr. Accessibility Technician 
Supporting the Department of Homeland Security|MGMT/OCIO/OAST 
Office: 202-815-5957 
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov> 
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax) 
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov> 
[cid:image001.png@01D3A09F.E6927B00] 
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited. If you have received this message in error, please reply immediately to the sender and delete this message. Thank you.
