### ISSUE TITLE
Modify Practice Exam Attempt Messages

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#343]
OAST has provided updated language to include in messages after submitting exam attempts. Messages attached...

[Congratulations Practice Exam 9 11 19.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3606499/Congratulations.Practice.Exam.9.11.19.docx)
[Nice Try Practice Exam 9 11 19.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3606500/Nice.Try.Practice.Exam.9.11.19.docx)

**Comment by mikebarklage** [comment]
Updated on Dev.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
