### ISSUE TITLE
Probably a bad idea to send out completion certificates as editable doc files?

### ISSUE THREAD

**Issue by sheribyrne** [Section508Coordinators/DHSA-TT-200-A#345]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Almost edited it by accident which is why I know it's editable

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
Should be a locked PDF

## Expected Behavior / Recommendation
Should be a locked PDF

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
Thanks Sheri. We'll add this as a future enhancement. We aren't as concerned about the Trusted Tester course completion certificate as much as we are about the certificate that we provide after completion of the Certification Exam. We manage the issuance of that certification a bit differently.

**Comment by AnnMarieDavis** [comment]
Sheri,
This issue has been resolved.  It is still a Word document, but is locked so it cannot be edited or saved as a PDF without the password. It can still be printed. Thank you for bringing this to our attention.
