### ISSUE TITLE
10.B not being correctly marked as a failure

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#346]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
10.B should be a failure when the ANDI Output does not match the visual heading.
![10 B answer sheet error](https://user-images.githubusercontent.com/31414225/64963918-0561ba80-d868-11e9-8e7d-5a1d402893c1.jpg)

## Location
Randomized version of Incremental exam for Topic 10
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?KeyID=24108

## Expected Behavior / Recommendation
Correct answer sheet to indicate

**Comment by Tonylayton1** [comment]
the aria output should not be wrong. Update the aria labeled by to match the text of the header.

**Comment by mikebarklage** [comment]
Fixed.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
