### ISSUE TITLE
Captions for videos blocking content  in Edge

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#347]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [X] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Student Jonathan Ma reported on 9/16 
For the Video in the About Registration Page, when I view the video on Chrome, the captions do not obscure the "read below for details" box, but the caption on Windows Edge do obscure it.

## Location
Practice Exam

## Expected Behavior / Recommendation
Can we look at this again?

**Comment by mikebarklage** [comment]
OK, I have "fixed" this on Dev by adjusting the margins/padding until the captions are below the in-video text in Edge and below the video entirely in FF/Chrome, just like on the Final Exam. I also had to split "If you are concerned about the security of your personal information" into 2 separate captions.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
