### ISSUE TITLE
5.F User identified issue with error identification

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#349]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
If you attempt to submit the form and the Device ID* (ZC0-xxx-xxx-xx) is not competed, the error message states: You must enter a confirmation code.  The confirmation code has **two other required dependencies** (the radio button and the Device ID) that are NOT identified. The answer sheet is marking this as PASS for 5.F, 3.3.1-error-identification, but it is arguable that the one message is adequate for all 3 required fields.
![5 F Device ID error message](https://user-images.githubusercontent.com/31414225/65249518-1dcd1180-dac2-11e9-80da-a9a5d63a39f6.jpg)

## Location
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=27055

**Comment by Tonylayton1** [comment]
This was by design. The user must enter device type and device ID in order to get the confirmation code. If they follow this error message, they will attempt to "get code" which will tell them they must enter their device ID and Type.

**Comment by drewnielson** [comment]
@AnnMarieDavis, let's just make sure we make a note of this just in case we get the same question from other students later.
