### ISSUE TITLE
Page 1, Region 3 Transcript button: R2 (False for 18.A [r3e07])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#35]
Transcript button:
R2 (False for 18.A [r3e07])
The button is present and named correctly. It opens the compliant transcript found in the “page 1 video instructions” document. The transcript opens in a separate window with the window title “Video transcript” and language set to “English”.  The window size is locked , and small enough so that if the user zooms to 200%, some text will be cut out.

**Cliff: Same issue for Final – window can be resized in Chrome**

**Comment by KSmithO** [comment]
Need to address for students in training, unless there is a way to stop this action in Chrome.

**Comment by KSmithO** [comment]
Keep this on hold.  If Carney can't fix before people get there, call OAST so we can tell you what page you are actually presented.

**Comment by mikebarklage** [comment]
Updated on Dev for all browsers, waiting for approval.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified
