### ISSUE TITLE
12.D Error on answer sheet

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#350]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
 Osheen Shrivastav reported - I am having trouble with 12.D test case in practice exam. 12.D indicates that if an iframe has a negative tabindex, test condition DOES NOT APPLY.

For the ZipChip About Registration page, iFrame has a negative tab-index and I marked the test as DNA. But it seems, I did not pass that condition. Is there anything I am missing with this test ID?

![12 D iFrame negative tabindex](https://user-images.githubusercontent.com/31414225/65348070-5b0ecd80-dbae-11e9-8e6d-fd55dde76598.png)

iFrame shows a negative tabindex

## Location
answer sheet attempt #2 
https://exams-dev1-c.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=4040&KeyID=30270&ExamID=2

Page
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=30270

## Expected Behavior / Recommendation
When an iframe has a -1 value, no title should be expected. 12.D should be DNA

**Comment by Tonylayton1** [comment]
we removed it from the tab index in response to a previous update, where the desire was that the iframe did not receive focus. I believe we reversed this in the final exam. This is not meant to be DNA as the iframe is on the page for the purspose of testing the iframe name.

**Comment by Tonylayton1** [comment]
Woops! Should have added: remove the -1 tab index from the iframe to match what we did in the final exam

**Comment by mikebarklage** [comment]
Updated on Dev.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
