### ISSUE TITLE
Topic 16a, audio only examples do not display transcript

### ISSUE THREAD

**Issue by elogle** [Section508Coordinators/DHSA-TT-200-A#351]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
Hi @elogle - I'm having a hard time pinning down the issue you submitted. Can you tell me what page in the course (perhaps the URL) and which video is not displaying a transcript? 

For each of the audio-only examples on the 16.A, Passing Examples page (https://training.section508testing.net/mod/book/view.php?id=1270&chapterid=3083), it looks like the transcripts are displaying properly. Is that the page where you noticed the issue, or was it somewhere else in the course?
