### ISSUE TITLE
15.B Answer sheet updates

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#353]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [X] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Answer sheet issues:

1. Correct spelling of Thump-Print List to Thumb-Print List

1. Change instructions at the top of the page to:
Select all checkboxes for items below whose sequence and meaning FAILS test condition 15.B.

## Location
15.B Answer Sheet
![15 B answer sheet_fix](https://user-images.githubusercontent.com/31414225/65610620-9d098c00-df7f-11e9-8f54-b484413d035a.jpg)

Error found related to
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_frame2.php?KeyID=38390

**Comment by mikebarklage** [comment]
Fixed on Dev.

Also bear in mind, this will change the instructions for 15.B on all exams, not just the practice.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified on dev
