### ISSUE TITLE
Course Error Please Fix!!!

### ISSUE THREAD

**Issue by Josh-Octo** [Section508Coordinators/DHSA-TT-200-A#354]
I am currently taking the 508 TT course and I have been stuck on one practical test question for hours.

> Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components, such as shape, size, visual location, orientation, or sound.

Please provide assistance. I have tried every answer combination many times over and have had no luck. This course is extremely difficult because of its testing method. There is no reason a user should get locked into a single question with no way to go past or receive help. The UX is horrible.

## Issue Type (put a capital X between the brackets to indicate issue type)
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X] Other, specify...Testing trap. One bad question should not stop all testing progress.

## Description
[Description of the issue]

## Location
[Topic 13]

## Actual Behavior / Observation
No correct answer

## Expected Behavior / Recommendation
A correct answer, Some way to move forward

## Steps to Reproduce the Issue (if applicable)
Try to get it right. If you can, please please tell me what the answer is.

**Comment by drewnielson** [comment]
Hi @Josh-Octo. Sorry for your frustration, and sorry for not being able to address this issue sooner. It will be difficult for me to pinpoint a particular issue from your broad description, but I would be happy to schedule a time to pull up some of your individual exam attempts and walk through them to identify whether the exam is scoring the attempt correctly. Do you have some availability tomorrow or early next week to talk through it?

**Comment by Josh-Octo** [comment]
Hi,

I would love to go over some if the issues I’ve found. I should have some time tomorrow after 2:30. Next week is fine as well. Let me know what works for you.

Thanks,
Josh

Joshua Wilson
Octo Consulting | Manager
tel | mobile (757) 338-7654
joshua.wilson@octoconsulting.com<https://mailto:joshua.wilson@octoconsulting.com>
[/var/folders/t8/9m0n7jbd3mx91s5_tp_g2h_40000gp/T/com.microsoft.Outlook/WebArchiveCopyPasteTempFiles/cidA3272FCD-3A38-4445-9826-6EAED7093FC0]
On Oct 3, 2019, 1:17 PM -0400, Andrew Nielson <notifications@github.com>, wrote:

Hi @Josh-Octo<https://github.com/Josh-Octo>. Sorry for your frustration, and sorry for not being able to address this issue sooner. It will be difficult for me to pinpoint a particular issue from your broad description, but I would be happy to schedule a time to pull up some of your individual exam attempts and walk through them to identify whether the exam is scoring the attempt correctly. Do you have some availability tomorrow or early next week to talk through it?

**Comment by drewnielson** [comment]
Noted design recommendations separately. Closing this specific issue.
