### ISSUE TITLE
ANDI does not catch anything in my application

### ISSUE THREAD

**Issue by anujautt** [Section508Coordinators/DHSA-TT-200-A#355]
Hi,
my application is hosted in another portal application. When I run ANDI on my application it only identifies issues in the portal application. Is there a way to use ANDI for the hosted application? 
Thanks for you help.
![ANDI output](https://user-images.githubusercontent.com/56039502/65979733-cb85dc00-e443-11e9-8ef0-c4670b81e071.PNG)

**Comment by drewnielson** [comment]
Hi @anujautt. ANDI actually has a separate repository and issues list in GitHub: https://github.com/SSAgov/ANDI/issues. 

There certainly are some limitations, and the Social Security Administration is working on addressing some of them. Please post this issue in the ANDI repository/issues list, so they can identify how to potentially resolve.
