### ISSUE TITLE
Topic Ten Content Structure, determinable heading

### ISSUE THREAD

**Issue by elogle** [Section508Coordinators/DHSA-TT-200-A#357]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X ] Incorrect content
- [X ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
According to the test process for Content Structure Determinable Headings, headings that have a mismatch between visual heading and the ANDI Output FAIL. In the incremental exam, the heading Number of Searches Including the Team...text has an ANDI output of Registered Users. I marked this fail but did not pass. Next time, I skipped this, knowing that it was wrong, and I passed.

## Location
[https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?studentEmail=emily.ogle27@yahoo.com&SCOInstanceID=5520&examId=10, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[Discrepancy between test process content and actual result in incremental exam]

## Expected Behavior / Recommendation
[I expect that if I follow the test process, "Note: If the ANDI Output displays different text than the heading text on the page, then the heading is not properly defined programmatically. " that failing a mismatch would be a correct answer.]

## Steps to Reproduce the Issue (if applicable)
[Turned on ANDI, focused on Number of search... text, identified mismatch, which said Registered User]

**Comment by drewnielson** [comment]
@elogle, thanks for noting the issue. We are also tracking the issue under issue #346. We have it fixed in our dev environment and will release to production shortly. Closing this issue in favor of #346. Noting as resolved pending deployment to production.
