### ISSUE TITLE
Score not showing up - stuck on Loading Score after 1st attempt

### ISSUE THREAD

**Issue by skalbag007** [Section508Coordinators/DHSA-TT-200-A#358]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
After I finished my first attempt when I clicked on Submit my Answers, my score is not showing up.
My screen is stuck on Loading Score. I have tried refreshing couple of times as well after waiting for more than 5 minutes.

## Location
https://exams-dev1-c.section508testing.net/dhsv5/scormapi/lesson1.php?SCOInstanceID=8504&studentName=Shreya%20Kalbag&ltiUserId=5419&studentEmail=shreya.kalbag@hii-tsd.com&examId=1

## Actual Behavior / Observation
Frozen screen

## Expected Behavior / Recommendation
I would hope to see the score for my first attempt and my answers hopefully retained.

## Steps to Reproduce the Issue (if applicable)
Finished first attempt and clicked on Submit my answers.

![image](https://user-images.githubusercontent.com/56353274/66486175-14f3ae00-ea78-11e9-8fef-3d489b2eec9b.png)

**Comment by drewnielson** [comment]
@skalbag007, thanks for noting the issue.

@mikebarklage, this is the same issue as described in [DSP-75](https://neweditions.atlassian.net/secure/RapidBoard.jspa?rapidView=84&projectKey=DSP&modal=detail&selectedIssue=DSP-75), in the JIRA issues list.

**Comment by jaunitageorge123** [comment]
I'm also having the same issue with the practice exam. :(

![image](https://user-images.githubusercontent.com/56369808/66593463-0cc56c80-eb65-11e9-888d-14f5449107c7.png)

**Comment by mikebarklage** [comment]
Are the users receiving the confirmation email in any of these cases?

**Comment by drewnielson** [comment]
@mikebarklage, the one other student who reported the issue said he did NOT receive the email confirmation, but he never received any emails for any attempt.

@skalbag007 and @jaunitageorge123, what about you - did either of you receive the confirmation email listing your missed Test IDs?

**Comment by jaunitageorge123** [comment]
I ended up receiving it, but I’m not sure the test IDs were correct – for the score I received (87% in one case and 92% in another), there appeared to be a lot of incorrect responses. I’d really like to know what I did improperly.

Any chance I can schedule a time to discuss my results on the practice exam before I take the final?

Jaunita George, Esq., PMP
Senior Consultant
Enterprise Resource Performance, Inc. (ERPi)
jgeorge@erpi.net<mailto:jgeorge@erpi.net> | (703) 424-5019 (work cell) or (206) 778-1882 (personal cell) | www.erpi.net<http://www.erpi.net/>
[ERPi_log_email]
A Service-Disabled Veteran-Owned Small Business (SDVOSB)

**Comment by jaunitageorge123** [comment]
Just for reference, here's what they sent as my incorrect test results when I scored a 92%:

Incorrect Test IDs are listed below:
12.B - The <title> element identifies the contents or purpose of the Web page.
13.A - Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.
13.B - Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components, such as shape, size, visual location, orientation, or sound.
14.C - The layout table DOES NOT designate the layout table using ARIA role='table' AND DOES NOT include table header structure and relationship elements and/or associated attributes.
17.A - The multimedia provides accurate captions for the audio content.
17.B - The multimedia provides an equivalent soundtrack (combination of narration and audio descriptions) for the video content.
18.A - There is a mechanism to resize, scale, or zoom in on the text to at least 200% of its original size without loss of content or functionality.
2.D - The page provides notification of each automatic update/change in content.
5.C - The combination of the accessible name, accessible description, and other programmatic associations (e.g., table column and/or row associations) describes each input field and includes all relevant instructions and cues (textual and graphical).
10.B - Each programmatically determinable heading is a visual heading and each visual heading is programmatically determinable.
4.D - A visible indication of focus is provided when focus is on the interface component.
4.E - When an interface component receives focus, it does not initiate an unexpected change of context.
6.B - The page provides notification of each change in content that is the result of interaction with a link or button.

**Comment by drewnielson** [comment]
@jaunitageorge123, we normally aren't offering 1 on 1 reviews any more, but I would be happy to make an exception. Please contact the DHS Accessibility Helpdesk (202-447-0440 | accessibility@hq.dhs.gov), and they can schedule a review session with me.

**Comment by jaunitageorge123** [comment]
Thank you so much! I’ll give them a call first thing in the morning. 😊

Jaunita George, Esq., PMP
Senior Consultant
Enterprise Resource Performance, Inc. (ERPi)
jgeorge@erpi.net<mailto:jgeorge@erpi.net> | (703) 424-5019 (work cell) or (206) 778-1882 (personal cell) | www.erpi.net<http://www.erpi.net/>
[ERPi_log_email]
A Service-Disabled Veteran-Owned Small Business (SDVOSB)

**Comment by cyclissmo** [comment]
Having the exact same issue with the certification exam. 

Submitted my first attempt on 12/27/19 at about 3:30 AM PST 
Firefox 71.0(64 bit) / Windows 10
VPN proxy through local server in Los Angeles
Waited about 15 minutes, refreshed a few times, no change. No emails received.

Screen cap with dev tools open showing no response for scoreExam.php (maybe this info helps?)
![image](https://user-images.githubusercontent.com/448781/71515867-96c6cc80-285a-11ea-8d2b-648059a57215.png)

https://exams.section508testing.net/dhsv5/scormapi/lesson1.php?SCOInstanceID=15572&studentName=Mike%20Zeballos&ltiUserId=6400&studentEmail=mike@studioefx.com&examId=1

**Comment by cyclissmo** [comment]
Follow-up to my bug report, I got it to work by doing the following:

1. Closed the exam page tab (that was hanging);
2. Navigated back to the Trusted Tester Certification Exam learning plan page;
3. Clicked on the certification exam link to launch the exam;
4. The exam page opens, and my test results display almost immediately.
5. I received the email a minute later.

**Comment by Tonylayton1** [comment]
This could be related to issue #371 . Please close if this is no longer occuring.

**Comment by AnnMarieDavis** [comment]
Earlier updates have fixed this issue.
