### ISSUE TITLE
Resetting my scores

### ISSUE THREAD

**Issue by jaunitageorge123** [Section508Coordinators/DHSA-TT-200-A#359]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The practice exam in the course reset my saved responses, so now I have to retest the site. 

## Location
Practice exam answer entry main page. 

## Actual Behavior / Observation
The issue happened when I started the test for Forms. 

## Expected Behavior / Recommendation
I expected to be able to complete the Forms tests and then save my responses, while seeing my prior responses in the page. 

## Steps to Reproduce the Issue (if applicable)
Complete tests 2-4, when you get to test five and open the page, it may delete your previous answers.

**Comment by drewnielson** [comment]
@jaunitageorge123, sorry for the inconvenience, but thanks for the noting the issue.

@mikebarklage, any chance this is related to #358 and [DSP-75](https://neweditions.atlassian.net/secure/RapidBoard.jspa?rapidView=84&projectKey=DSP&modal=detail&selectedIssue=DSP-75)?

**Comment by jaunitageorge123** [comment]
That’s fine. If this happens during the final exam, will I be held to the three attempt limit? I just want to make sure that I have the opportunity to pass, if possible. 😊

Jaunita George, Esq., PMP
Senior Consultant
Enterprise Resource Performance, Inc. (ERPi)
jgeorge@erpi.net<mailto:jgeorge@erpi.net> | (703) 424-5019 (work cell) or (206) 778-1882 (personal cell) | www.erpi.net<http://www.erpi.net/>
[ERPi_log_email]
A Service-Disabled Veteran-Owned Small Business (SDVOSB)

**Comment by drewnielson** [comment]
@jaunitageorge123, unfortunately, we don't have a way to modify the attempt limit mid-exam, but if this does happen while you are in the final, let me know, and we can certainly come up with a way to make some accommodation on attempts.

**Comment by jaunitageorge123** [comment]
Thank you! 😊

Jaunita George, Esq., PMP
Senior Consultant
Enterprise Resource Performance, Inc. (ERPi)
jgeorge@erpi.net<mailto:jgeorge@erpi.net> | (703) 424-5019 (work cell) or (206) 778-1882 (personal cell) | www.erpi.net<http://www.erpi.net/>
[ERPi_log_email]
A Service-Disabled Veteran-Owned Small Business (SDVOSB)

**Comment by mikebarklage** [comment]
"any chance this is related to #358 and DSP-75?"

That doesn't seem likely, although - if this is the exam submitted at 2019-10-10 00:29:22 - prior answers appear to have been recorded properly, maybe just not displaying. Page 1 Topics 2 & 4 and all Topics on Page 3 have been answered; Page 1 Topic 5 thru all of Page 2 has been left blank.

**Comment by Tonylayton1** [comment]
Has this issue come up again? I have not been able to replicate this in the dev environment and it is 5 months old.

**Comment by AnnMarieDavis** [comment]
This issue has not come up again. But I'm happy to report that this student is certified and appears to have had no issues with the final exam.
