### ISSUE TITLE
Page 1, Region 3 CC button R3 (True for 17.A  , DNA for 17.E, false for 17.D [r3e03])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#36]
R3 (True for 17.A  , DNA for 17.E, false for 17.D [r3e03])
Closed captioning is always on, but there is NO CC BUTTON, closed captioning displays on the video, **matches the audio ***cs: updated, see comment**, and is timed correctly with the audio. See the “page 1 video instructions” document for the compliant captions. 

Cliff: 

1. The key #1241 says 17.A is NC.
2. ***There is no caption for the first part of the sentence, so the ONLINE answer key is correct, but the WRITTEN one here for R3 is incorrect.

**Comment by mikebarklage** [comment]
Docs updated, no approval necessary.

**Comment by Tonylayton1** [comment]
Document did not account for both issues at once. The documentation has been updated to account for it now.

**Comment by AnnMarieDavis** [comment]
Verified
