### ISSUE TITLE
Keyboard Trap > Passing Example 1 > Inconsistent behavior on Firefox

### ISSUE THREAD

**Issue by JRNPW** [Section508Coordinators/DHSA-TT-200-A#361]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
When using Firefox, the website example for Keyboard Trap Passing Example 1 does not function as described

## Location
Topic 4: Keyboard Access and Focus > Lesson 3 > Passing Examples https://training.section508testing.net/mod/book/view.php?id=1229&chapterid=2691

Passing Example demo site: https://dev.section508testing.net/html/4C_Pass1.html

## Actual Behavior / Observation
When using Firefox, I tried to tab through the presented dialog box. I was unable to access the "Course Topics" link.

## Expected Behavior / Recommendation
Firefox users should also be able to follow the instructions with all described behaviors being the same as other browsers.

**Comment by drewnielson** [comment]
@JRNPW, thanks for noting your suspected issues. I am able to navigate to the links and buttons without issue using Firefox. Can you give me more details about your user environment, e.g., version of Firefox, OS? Do you notice the same behavior on any other websites (where you can navigate to links in another browser, but not in Firefox)? I do notice that the visible indication of focus is not as evident in Firefox as it is in Chrome. Is it a visible focus issue, or are you definitely unable to navigate to the links using a keyboard?

**Comment by JRNPW** [comment]
You're welcome, Drew. I'm using Firefox 69.0.2 on macOS Mojave (10.14.6). I just double-checked, and the focus completely skips the "Course Topics" link. I agree that the visible indication isn't as clear, but it skips from "Browse" to "New Folder." I could probably capture a video if you want to see it in action.

**Comment by drewnielson** [comment]
@JRNPW thanks! Certainly seems like odd behavior. I'll have to dig in a little more and dig up our Mac again as well. No need to grab a video, but thanks for confirming.

**Comment by AnnMarieDavis** [comment]
I was able to navigate to the Course Topics in Firefox and although focus did not remain with the modal dialog box, there was not a keyboard trap. Should we modify the course content or close this issue?

**Comment by JRNPW** [comment]
I suspect that this is related to the settings mentioned in this [Mozilla Developers Network page](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility). Therefore, probably not a bug but a misconfiguration of the Firefox browser.
