### ISSUE TITLE
Certification Exam - "Using the Course Interface" page gives incorrect info about number of attempts allowed

### ISSUE THREAD

**Issue by istrahan-aspiritech** [Section508Coordinators/DHSA-TT-200-A#362]
## Issue Type
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...

## Description
The "Using the Course Interface" page in the Course Introduction for the certification exam incorrectly says that the user can retake the exam an unlimited number of times within the three days. (At least, I'm assuming this is incorrect, because every other page that states the number of attempts allowed on the certification exam says that only 3 attempts are allowed.)

## Location
https://training.section508testing.net/mod/book/view.php?id=1419&chapterid=3253

## Actual Behavior / Observation
In the last paragraph of the "Using the Course Interface" page, it says, "Within your three days of access to the exam, you can retake the exams as many times as needed to pass."

## Expected Behavior / Recommendation
The page should say that you have 3 attempts to submit the exam

## Steps to Reproduce the Issue (if applicable)
1. Navigate to the "Trusted Tester - Certification Exam for Web on Windows" course
2. Navigate to the "Course Introduction"
3. Navigate to the "Using the Course Interface" page

**Comment by drewnielson** [comment]
@istrahan-aspiritech, thanks for pointing that out. I thought we had already fixed that. Just updated the language.
