### ISSUE TITLE
Hi I have completed my second attempt on the final exam. I went to page 4 to submit. I pressed submit. The screen changed to page 5. I have now been waiting at least five minutes for my score to load. Help! 

### ISSUE THREAD

**Issue by LydiaSchuck** [Section508Coordinators/DHSA-TT-200-A#363]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [x] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
@LydiaSchuck, very sorry for the issue. Try to log out, then log back in again and launch the exam. Review your results to make sure they were all saved. Then you should be able to submit again. Let me know if you still have an issue.

**Comment by LydiaSchuck** [comment]
It worked. And then I passed over the weekend. Thanks for your help.

________________________________

**Comment by drewnielson** [comment]
OK, great. Congrats on passing!
