### ISSUE TITLE
Error with Practice Exam

### ISSUE THREAD

**Issue by KimKWee** [Section508Coordinators/DHSA-TT-200-A#364]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [X ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X ] Other, specify...[practice exam will not load]

## Description
[When trying to open practice exam to retake, receive error: An error occurred when launching the external tool: Sorry, there was an error connecting you to the application]

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[When trying to open practice exam to retake, receive error: An error occurred when launching the external tool: Sorry, there was an error connecting you to the application]

## Expected Behavior / Recommendation
[Should be able to retake practice exam]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

![image](https://user-images.githubusercontent.com/43556683/67164594-dc8a8480-f341-11e9-867b-65b210c01102.png)
<img width="935" alt="Practice Exam Error" src="https://user-images.githubusercontent.com/43556683/67164605-f1671800-f341-11e9-9c72-ca7e236cca41.png">

**Comment by KimKWee** [comment]
I was able to get in to retake the practice exam (after refreshing the page several times) however was not able to get in again after that. Was hoping to get in this morning thinking the system just needed a break but wasn't the case (smile).

**Comment by drewnielson** [comment]
@KimKWee sorry for the issue. Thanks for raising it. We're looking into the cause.

**Comment by mikebarklage** [comment]
Unfortunately, this is the default message the LTI library uses for every error, so that doesn't tell us much.

Again, I don't have access to the exams on Pilot Dev - I did at some point, but not anymore - so I can't try to launch one. Can anyone at OAST launch an exam, and do you also see this message?

Otherwise, my initial advice for this (and the scoring page issue) is to get Moonami involved because there may be server connectivity issues.

**Comment by drewnielson** [comment]
Mike, those were my screenshots, so definitely confirmed that I’m seeing
the same issue. I see that you are enrolled in the courses (with the pilot
dev exams). Let me know if you need a password reset. .

**Comment by mikebarklage** [comment]
Enrolled, yes, but without access unless I actually go through the entire course:

![ttw](https://user-images.githubusercontent.com/50433189/67223063-6c343f80-f3e3-11e9-8976-336484866328.jpg)

**Comment by mikebarklage** [comment]
I am seeing the error when I try to launch the admin tool, though.

**Comment by mikebarklage** [comment]
Based on this, I think Moonami's system clock is out of sync again:

lti_errorlog=Debug+error%3A+OAuth+signature+check+failed+-+perhaps+an+incorrect+secret+or+timestamp.

**Comment by drewnielson** [comment]
Thanks @mikebarklage. I see you copied John Porten on the system clock sync issue. I'll forward that along to Moonami Support as well. I also just fixed your issue with course access from the Dashboard. You should see the links to the courses from the Dashboard now.

**Comment by mikebarklage** [comment]
Yep, I can get into the exams now (or will when the clock issue is fixed). Thanks!

**Comment by drewnielson** [comment]
System clock sync issue fixed. Exams available.
