### ISSUE TITLE
Error in Trusted Tester - Certification Exam for Web on Windows 

### ISSUE THREAD

**Issue by makader86** [Section508Coordinators/DHSA-TT-200-A#365]
I am try to attempt to final exam but the page has error and is not available for exam  
Please see error below that error 

**Certification Exam
An error occurred when launching the external tool:Sorry, there was an error connecting you to the application.**

**Comment by drewnielson** [comment]
@makader86 sorry for the issue. Thanks for raising it. We are looking into the cause.

**Comment by drewnielson** [comment]
System clock sync issue fixed. Exams available.
