### ISSUE TITLE
passed certification exam, however when I log in fresh to see my "exam wrap up" it states an error occurred.

### ISSUE THREAD

**Issue by ChrisLoiselle** [Section508Coordinators/DHSA-TT-200-A#366]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [x] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
[URL, Topic, Chapter, Subchapter]

https://training.section508testing.net/mod/lti/return.php?course=65&launch_container=4&instanceid=54&sesskey=DrCWFzgiKy&lti_errormsg=Sorry%2C+there+was+an+error+connecting+you+to+the+application.&lti_errorlog=Debug+error%3A+OAuth+signature+check+failed+-+perhaps+an+incorrect+secret+or+timestamp.

## Actual Behavior / Observation
[Describe what you observed or the error you found]

Certification Exam
An error occurred when launching the external tool:Sorry, there was an error connecting you to the application.

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
@ChrisLoiselle sorry for the inconvenience - we are definitely experiencing some issue with the external exam engine tool. Working on fixing it. The Accessibility Help Desk will send out an update to students once we get it fixed.

**Comment by ChrisLoiselle** [comment]
I log into the TT dashboard, go to the exam page that has an X listed, follow that link and the page reads as: 
No Further Attempt Needed!

You already passed the Exam.

I then go to the TT exam course dashboard and follow the exam follow up 
Exam Wrap-up
 Trusted Tester Web on Windows Certification Exam SurveyURL
Not available unless: The activity Certification Exam is complete and passed

I can't close out the "enrolled status" of this course. 

Any suggestions?

**Comment by drewnielson** [comment]
Sorry Chris. With the exam engine down yesterday, it looks like the core course application just didn't get the communication back on your final attempt score. I updated your score manually, so you should be able to get to the exam survey now, and the course status should show up as passed on your dashboard. Congrats on passing!

**Comment by ChrisLoiselle** [comment]
thank you! do you still send out tt certs from oast that I could hang on my wall of fame?

**Comment by drewnielson** [comment]
Yep - it might take a few days, but the Accessibility Help Desk will send you a certificate with your new Trusted Tester ID.
