### ISSUE TITLE
Is the practice exam passing grade calculation offset?  The Total Practice exam questions are 37. First screen 11 Questions, Second screen 12 Questions, Third screen 14 questions. I took the test and received 79% with the 27 incorrectly answered, which means I only answered correctly 10 and received failing score of 79%. Nice Try! You scored 79% on the Practice Exam.

### ISSUE THREAD

**Issue by AbdiHussein1** [Section508Coordinators/DHSA-TT-200-A#367]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [x] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
@AbdiHussein1, the practice exam includes the correct answers from your previous attempts to calculate your cumulative score. So after your first attempt, even though you only have to provide answers for questions you previously missed, all of your correct answers are added to the correct answers on your subsequent attempts to give you a total score.

In the future, please submit your questions using the Q&A Question Board in the Course Resource, or submit your question to the Accessibility Help Desk (accessibility@hq.dhs.gov). This repository is really used only for tracking bugs and issues.

**Comment by AbdiHussein1** [comment]
Hi Andrew,
Thanks for the prompt response. Just to make sure I understand you well. Are you saying these are the questions that I correctly answered.

And I should ignore the line below that says incorrectly answered. I will post my questions on the QA from now on.

Warm regards,



Abdi.



Incorrectly answered Test IDs below:


2.C - The user can pause, stop, hide, or control the frequency of automatically updating content.
4.F - The focus order preserves the meaning and operability of the Web page.
7.B - There is no accessible name and accessible description for a decorative image.
13.A - Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.
14.C - The layout table DOES NOT designate the layout table using ARIA role='table' AND DOES NOT include table header structure and relationship elements and/or associated attributes.
16.A - A text-based alternative is provided for audio-only content that provides an accurate and complete representation of the audio-only content.
16.B - The video-only content information is also available through an equivalent text or audio alternative.
17.A - The multimedia provides accurate captions for the audio content.
17.E - User controls for captions are provided at the same menu level as the user controls for volume or program selection.
17.F - User controls for audio descriptions are provided at the same menu level as the user controls for volume or program selection.
19.A - There are two or more ways to locate a Web page within a set of web pages.
4.D - A visible indication of focus is provided when focus is on the interface component.
5.B - Each form label is sufficiently descriptive.
5.C - The combination of the accessible name, accessible description, and other programmatic associations (e.g., table column and/or row associations) describes each input field and includes all relevant instructions and cues (textual and graphical).
5.D - Changing field values/selections (e.g., entering data in a text field, changing a radio button selection) does NOT initiate an unexpected change of context.
5.F - The item in error is identified in text and sufficiently described to the user in text.
7.E - The image of text cannot be replaced by text or is customizable.
9.A - A keyboard-accessible method is provided to bypass repetitive content.
10.B - Each programmatically determinable heading is a visual heading and each visual heading is programmatically determinable.
10.D - All visually apparent lists are programmatically identified according to their type.
11.B - The human language for any content segment that differs from the default human language of the page can be programmatically determined.
4.A - All functionality can be accessed and executed using only the keyboard.
5.A - Labels or instructions are provided for form elements.
5.E - The page provides notification of each form-related change in content.
12.C - Each <frame> has a title attribute that describes its content.
14.A - Each data table has programmatic markup to identify it as a table.
14.B - All data cells are programmatically associated with relevant headers.

**Comment by AbdiHussein1** [comment]
Please disregard my last email. My apology.

________________________________
