### ISSUE TITLE
9C Accessible name and description consistent identification incremental exam

### ISSUE THREAD

**Issue by nguyenlha** [Section508Coordinators/DHSA-TT-200-A#368]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Selecting the failure options for both the "link" links on the "Request an Audit" page does not pass this test.  Also, if section headings are expected to be tested under this test id and have consistent identification (I'm currently not sure), then selecting the “Number of Searches Including the term “Workbalance”" text, which has different ANDI output on the About page and the Data page, also does not pass this test on the incremental exam.  Note: the different "Number of Searches..." ANDI output might be found on other incremental exams as well.

## Location
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=ha.l.nguyen@uscis.dhs.gov&SCOInstanceID=4308&examId=9

## Actual Behavior / Observation
Selecting the failure options for both the "link" links on the "Request an Audit" page does not pass this test.  Also, selecting the "Number of Searches..." failure option does not pass this test.

## Expected Behavior / Recommendation
Selecting the failure options for both the "link" links on the "Request an Audit" page passes this test and need clarification on the "Number of Searches..." section heading consistent identification.

## Steps to Reproduce the Issue (if applicable)
Click on the "Request an Audit" link to notice the two "link" links in both the top navigation and footer.

**Comment by Tonylayton1** [comment]
Creating a new issue in JIRA to address this, since it is for the final exam.

**Comment by Tonylayton1** [comment]
To test 9.C the other 2 pages need to be constant. This student had it randomized on page 3 as well. Can the 2 pages not being tested be changed so that they don't show any failure options?

The student's second issue is with the aria live region labeledby on page 1. It does not match the one on page 2. both should be labeled by the header "Number of Searches Including the term "Workbalance"" but the page 1 live region is labeled by "Registered Users"
