### ISSUE TITLE
5.E - 4.1.2-change-notify-form

### ISSUE THREAD

**Issue by sdwaram1** [Section508Coordinators/DHSA-TT-200-A#369]
5.E - 4.1.2-change-notify-form

I am stuck in the 5.E test. I have tried every possible success and failure options with no success. The error messages on form submission are displayed in a pop up box specifying the format for every form field that needs to be populated which is a pass, Get super-certified ( selecting this will expand additional details below ) with a check box provides the required information to the user that additional details will be displayed on checking the checkbox which is a pass, Get Captcha with the image and required text is displayed as a message in the pop up box when the user submits the form without providing the Captcha text which is a pass. 

Can you explain how to evaluate 5.E for the Incremental Exam?

**Comment by AnnMarieDavis** [comment]
The **Submit an issue** link is for bugs or issues with the course itself.  Please repost your question to the **Trusted Tester Q&A - Question Board**.  https://training.section508testing.net/mod/forum/discuss.php?d=315
Other students have posted this question and were given a hint to be sure to look for content changes both ABOVE and BELOW the selected interactive element. 

You should also review questions already posted there and in the **Q&A Database (FAQ)**. The FAQ is searchable. https://training.section508testing.net/mod/page/view.php?id=1440
