### ISSUE TITLE
Page 1 Region 3  AD button R2 (True for 17.D and 17.F, False for 17.B [r3e03])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#37]
R2 (True for 17.D and 17.F, False for 17.B [r3e03])
The button is present as it appears in the mockup and is named correctly. **When toggled on, the non-compliant AD file plays at the beginning of the video.***CS: see comment**   See “page 1 video instructions” for non-complaint audio description.

Cliff: ***AD plays correct description but at start of video. However, the action (holds his neck) does not happen until after the first sentence. This is marked as pass in online key, but written video document says it should fail, as it should start after “by the end of the day” when he holds his neck.

**Comment by mikebarklage** [comment]
AD shifted to later in the video on Dev, waiting for approval.

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by AnnMarieDavis** [comment]
Verified this was moved per Cliff's instructions.
