### ISSUE TITLE
Student results not displaying in exam admin tool

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#371]
## Issue Type 
- [x] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
I’m trying to look at the results for a specific student, Ha Nguyen. Several of the Topic 9 Incremental Exams show no data to support his scores. 

## Location
exam admin tool

## Actual Behavior / Observation
there are multiple instances of students taking the incremental exam, but when you open the exam instance, it reports no data.  No table provided with student answers or link to the pages tested.

## Steps to Reproduce the Issue (if applicable)
tried to access this over several days

**Comment by Tonylayton1** [comment]
This issue is quite old now and I was never able to replicate it on the dev server. It could have been eliminated due to many changes that have been made since initially logging it. Please move the issue back a step if this is still coming up for students.

**Comment by AnnMarieDavis** [comment]
I have not seen this in a long time.  I agree that other updates appear to have corrected this issue.
