### ISSUE TITLE
Unable to locate student in exam admin

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#372]
Unable to find student searching by name:
Student: Arun Kumar (one of 4 students with the same name)
SCO ID for passed final exam: 10937
Student email: arun789kumar@gmail.com
Link to exam page for student:
https://exams.section508testing.net/dhsv5/scormapi/lesson1.php?SCOInstanceID=10937&studentName=Arun%20Kumar&ltiUserId=3039&studentEmail=arun789kumar@gmail.com&examId=1

**Comment by mikebarklage** [comment]
Moodle has this student's name as Sandeep Reddy. They show up in search results if you search on that name instead:

https://exams.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=10937&KeyID=69488&ExamID=1

Oddly, I only see entries for Final Exams under that name - and 4 of them, even though they passed the 3rd try at 98%.

I forget, did you want to move forward with adding email addresses to the search, or am I holding off on that?

**Comment by drewnielson** [comment]
Definitely strange. So a student with the same Student ID (3039); but name Arun Kumar has exam results for all of the incremental exams and the practice. Is it possible that the data got corrupted somehow? It might also be possible that the student changed their name just for the final exam, though that seems unlikely. Their current user profile is still lists their name as Arun Kumar, and that profile show's their final score of 98% for the final exam.

Yes, let's still add user email to the exam admin search. I just created a separate issue (#373) for that.

**Comment by mikebarklage** [comment]
With all this talk of gaming the exam, my first thought was they changed their name after passing so a friend could also get certified. It would help explain why they tried to make a 4th attempt.

**Comment by AnnMarieDavis** [comment]
Yikes!!! That never occurred to me! We’ve had a number of students use different email addresses and may need to consider the implications of that.

Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by AnnMarieDavis** [comment]
Yes, Mike definitely move forward on adding email addresses to the search options and search results.

**Comment by mikebarklage** [comment]
Adding email to search is up on Dev and is covered by ticket #373 .

**Comment by Tonylayton1** [comment]
I can confirm that the ability to search via email has been added, but cannot adequately test it on the test server, as there is only 1 student (me) - I believe this will need to be tested on the live server.

**Comment by AnnMarieDavis** [comment]
Verified email addresses have been added.
