### ISSUE TITLE
Add student email to exam admin fields and to search

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#373]
Add student email to the exam admin and make it possible to search by student email.

**Comment by mikebarklage** [comment]
I've added this on Dev.

**Comment by AnnMarieDavis** [comment]
We would also like the email address field added to the Class Instance Completion Report (that indicates students have passed the final exam).

**Comment by Tonylayton1** [comment]
I can confirm that the ability to search via email has been added, but cannot adequately test it on the test server, as there is only 1 student (me) - I believe this will need to be tested on the live server.

**Comment by mikebarklage** [comment]
Ann Marie - which page is that?

Tony - that shouldn't be the case. Dev should be pointing you to exams-dev.section508testing.net, which contains Pilot Dev data (and lots of it) up to Oct 29, when we updated the servers.

**Comment by AnnMarieDavis** [comment]
It looks like it is a moonami issue to add to the Class Instance Completion Report. Disregard this add on.

**Comment by AnnMarieDavis** [comment]
LOVE this new feature!  Confirmed
