### ISSUE TITLE
Topic 5.E Test Name 4.1.2-change notify form 

### ISSUE THREAD

**Issue by joshuastriker** [Section508Coordinators/DHSA-TT-200-A#375]
If the ANDI Output is displaying a small pyramid with an X through it and the following statement textbox has no accessible name, associated <label>, or [title] in brick red color. Does this mean this step failed? 

If the ANDI Output step displays HR Email in green does that step mean the step has passed? I have taken this test about 50 times. I mark it as failed and list the appropriate fields that also display this information but I am not passing it. What am I doing wrong?

**Comment by AnnMarieDavis** [comment]
Joshua,
The submit an issue link in the course is to report problems with the course itself. Please post questions to the **Trusted Tester Q&A - Question Board** from the course menu. https://training.section508testing.net/mod/forum/view.php?f=33
