### ISSUE TITLE
Incremental Practice Exam - Fails to Load Score/Freezes

### ISSUE THREAD

**Issue by aculbret** [Section508Coordinators/DHSA-TT-200-A#377]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [x] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by aculbret** [comment]
While taking the Interim practice exam for one lesson topic I needed to re-do, and submitting the answers, the screen fails to refresh with the results (either section failed or grade of 100%). After submitting, screen displays "Your Score (Please wait for your score to load)" with the words "Loading score..." showing below, but the panel locks up and the screen does not refresh to load score.  (waiting over 10 min. now).
![508-TT-Interim-Test-Failure](https://user-images.githubusercontent.com/57373830/68973844-48370480-07bd-11ea-8061-5f9b19792755.PNG)

**Comment by aculbret** [comment]
Topic 5, end of topic Interim Practical Exam

**Comment by AnnMarieDavis** [comment]
Please clear your cache and refresh your browser. There have been recent changes in browser settings that allow more limited deletions of the browser history; do not use these limited settings. Be sure you clear the entire cache.
