### ISSUE TITLE
There appears to be no solution for 5.E

### ISSUE THREAD

**Issue by abarbieri7** [Section508Coordinators/DHSA-TT-200-A#379]
Can I get some help here?

- [X] System Bug (the course doesn't function properly)
- [X] Other, specify...[replace this text with your issue type description]

## Description
I am unable to find a solution. The form technically does not change content. So it should be DNA. But if you wanted to say the "Get Super Certified..." checkbox changes content, it has a warning in the title of what and where the change will occur. If it is the CAPTCHA, if you know one, you know them all. So this should be a pass, because a notification is provided. I find no other elements that on focus, input, exit or activation make a change to content in the current page. 

## Location
[https://training.section508testing.net/course/view.php?id=78, Topic 5, Forms - Incremental Practical Exam, 4.1.2-change-notify-form

## Actual Behavior / Observation
No matter what I do, it says 5.E is incorrect.

## Expected Behavior / Recommendation
I would be moving on to Topic 6.

Thanks, A.

**Comment by dslinger** [comment]
I just left another ticket for this issue, and I agree that there seems no way to move forward.

**Comment by AnnMarieDavis** [comment]
This is not an exam issue (bug). 

It is considered a change of content if a checkbox changes content. For test ID 5.E, 4.1.2-change-notify-form you would need to determine if the label provides sufficient warning of what and where the change will occur. If you still have a question about why your answer was incorrect, please contact the Accessibility Help Desk (accessibility@hq.dhs.gov)
