### ISSUE TITLE
Practicing Exam 

### ISSUE THREAD

**Issue by Dkvkarma** [Section508Coordinators/DHSA-TT-200-A#380]
How one can Practice Exam after scoring 90%. Before attempting Final Exam.
Thanks
Dilip

**Comment by drewnielson** [comment]
Please contact the Accessibility Help Desk (accessibility@hq.dhs.gov) and request a Practice Exam reset. You'll need to score a 90% on the practice exam again before moving on, but you request a reset on the practice exam as many times as you'd like before moving on to the Final exam.
