### ISSUE TITLE
Video help for Incremental Practical Exam

### ISSUE THREAD

**Issue by Mark0068** [Section508Coordinators/DHSA-TT-200-A#381]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [X ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x] Other, specify...[replace this text with your issue type description]

## Description
Video doesn't run:  The Topic 4 Incremental Exam Video Demo [https://training.section508testing.net/mod/page/view.php?id=1449]

## Location
TT Incremental quiz 4 FAQ

## Actual Behavior / Observation

Error msg:  Sorry, this activity is currently hidden

## Expected Behavior / Recommendation
Please let m know when this will be available, or what I am doing wrong.

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by drewnielson** [comment]
Sorry for not seeing this issue submission sooner. Please navigate to https://training.section508testing.net/mod/page/view.php?id=1450, and you should be able to view the video there.
