### ISSUE TITLE
Ambiguous Question on Topic 5 Practical Exam

### ISSUE THREAD

**Issue by dslinger** [Section508Coordinators/DHSA-TT-200-A#382]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x ] Other, specify... cannot complete Incremental Practical Exam

## Description
I have retaken the Incremental Practical Exam for Topic 5: Forms several times and keep getting the following item incorrect:

5.E | The page provides notification of each form-related change in content.

It is unclear what specific items are failures. What I believe is a failure is the Submit button, as typically the error message is vague and/or the page advances the form without allowing me to return and correct my form submissions. However, when I mark it as Fail and include Submit button, I continue to get the question wrong. I've also tried including each one of the form elements that the error messages don't identify. This is also marked as incorrect. I don't know what the test wants from me at this point

## Location

Tpic 5: Forms 

## Actual Behavior / Observation
Cannot complete Practical Exam

## Expected Behavior / Recommendation
It is either marking incorrectly or is ambiguous about what information is required for a correct answer.

**Comment by abarbieri7** [comment]
Hello. Is this the correct place to file issues like ours? Do we know this is monitored? I was making good progress and now am stuck until someone resolves these issues. Have a good weekend.

**Comment by drewnielson** [comment]
Apologies for not noticing the original issue submission. I don't believe this is an issue, but happy to walk through it with each of you. Please contact the Accessibility Help Desk (accessibility@hq.dhs.gov) to schedule a 1-on-1 session with me. Also feel free to copy me (andrew.nielson@associates.hq.dhs.gov) when you email the help desk.
