### ISSUE TITLE
Practice Test - Not Saving Answers in Firefox

### ISSUE THREAD

**Issue by laurastewart-work** [Section508Coordinators/DHSA-TT-200-A#383]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ X ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Practice Test - Not Saving Answers in Firefox

## Location
URL for Page 1:  https://exams.section508testing.net/dhsv5/scormapi/lesson1.php?SCOInstanceID=8079&studentName=Laura%20Stewart&ltiUserId=2654&studentEmail=laura.stewart@fema.dhs.gov&examId=2

## Actual Behavior / Observation
I just finished taking the Practice Exam using Firefox, so I'm sure that I have answered everything on all three pages (Zip Chip - About Registration - Test List is page name).  So, all of the buttons on those pages should say Modify Results. 
![image](https://user-images.githubusercontent.com/55752185/70267978-88125b80-176d-11ea-86db-7ae9ac0525ca.png)

## Expected Behavior / Recommendation
Since I've spent all day answer every question on 3 pages, all of the buttons should say Modify Results.

## Steps to Reproduce the Issue (if applicable)
I think it had something to do with refreshing the page (F5).  I did this because I wanted to go back to the previous page and nothing happened.

**Comment by AnnMarieDavis** [comment]
This is not an exam issue (bug). 

Before you submit, all buttons should say "modify results" to indicate all answers have been provided.  If you are still seeing "In progress" on a button, you are missing an answer for at least one test id OR you have not indicated the element(s) that caused the Test ID to fail.
