### ISSUE TITLE
Answer sheet for 8.A timeout

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#384]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X ] Other, specify...[clarification needed]

## Description
Answer sheet options are confusing.
![image](https://user-images.githubusercontent.com/31414225/70451091-cad87a00-1a72-11ea-9e62-b8f4336aab82.png)

## Location
https://exams.section508testing.net/dhsv5/scormapi/lesson1.php?SCOInstanceID=332&studentName=Ann%20Marie%20Davis&ltiUserId=3382&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=8

## Actual Behavior / Observation
Current answer sheet has 3 options. 
- The user cannot turn off the time limit before time expires, cannot adjust the time limit to at least ten times the length of the default setting before time expires, and the page does not provide a warning before time expires.
- Upon receiving a warning, the user does not have at least 20 seconds to extend the time limit with a simple action
- The user cannot extend the time limit at least ten times.

## Expected Behavior / Recommendation
Change first option to:

- The user cannot perform ONE of the following: (1) turn off the time limit before time expires, OR  (2) adjust the time limit to at least ten times the length of the default setting before time expires, OR (3) the page does not provide a warning before time expires AND allow at least 20 seconds to extend the time limit with a simple action AND can extend the time limit at least ten times.

Remove 2 Options:
- Upon receiving a warning, the user does not have at least 20 seconds to extend the time limit with a simple action
- The user cannot extend the time limit at least ten times.

**Comment by mikebarklage** [comment]
Tony, please see the discussion over on JIRA. Thanks.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
New option combining all 3 answers into one is correct.
