### ISSUE TITLE
Certificate Exam deleted progress when logged into another computer

### ISSUE THREAD

**Issue by cyclissmo** [Section508Coordinators/DHSA-TT-200-A#385]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
While completing the certification exam, many of my answers were lost when logged out and logged in again on another device.

## Location
Trusted Tester Certification Exam, no specific location

## Actual Behavior / Observation
From my desktop I clicked exit to exit the course after saving my progress. I logged back into my account from another device to continue the exam. I should have seen steps 1 through 16 completed. I saw only steps 1 through 4 completed; the remainder of my exam progress have been lost.

## Expected Behavior / Recommendation
I expected my exam session to persist on logout; and restore where I left off when I logged in on another device.

## Steps to Reproduce the Issue (if applicable)
Cannot reproduce.

**Comment by AnnMarieDavis** [comment]
I log in from other computers and different websites regularly and have not had this problem.  Unable to reproduce.
