### ISSUE TITLE
Open Captions - Section 17

### ISSUE THREAD

**Issue by Marimbadog** [Section508Coordinators/DHSA-TT-200-A#387]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Topic 17 "synchronized media" does not have any exemptions for open captions as opposed to closed captions. Open captions (captions that are always on the screen) should meet the accessibility principals for topic 17. However, in the test practice, the video fails tests 17.D and 17.E because there are no caption controls. 

## Location
Topic 17, Tests 17.D and 17.E

## Expected Behavior / Recommendation
There should be a does not apply exemption for open captions throughout topic 17.

**Comment by AnnMarieDavis** [comment]
This is not incorrect content. There is a Section 508 requirement in Chapter 5 of the standards for caption control buttons regardless of whether they are "needed" or not.
