### ISSUE TITLE
Incremental corrections

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#390]
Adding issue from Jira into GitHub. Check the text indicated in red against the incremental exam correct answers to ensure they are being scored correctly. Documents are attached. 

[Page1 Randomization_w Correct Answer Guidance.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/4118367/Page1.Randomization_w.Correct.Answer.Guidance.docx)
[Page2 Randomization_w Correct Answer Guidance.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/4118368/Page2.Randomization_w.Correct.Answer.Guidance.docx)
[Page3 Randomization_w Correct Answer Guidance.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/4118369/Page3.Randomization_w.Correct.Answer.Guidance.docx)

**Comment by Tonylayton1** [comment]
Updates for page 1:
Mention of 15.C is an artifact, requires no change in the course.
Update default answer for 7.E to True, not DNA. Will open separate issue.
Default answer for 17.E is already DNA, requires no change in the course. .

Updates for page 2:
Update site logo icon passing alt text to "Work Balance scale company logo". Will open separate issue (also this should apply to all three pages even though there was no comment on page 1).
The 4.D and the 4.D/4.F issues do not affect anything, as topic 4 is only tested on page 3. Doc outdated since that ID and page combo were no longer important. 

Updates for page 3:
The 5.B issue is linked to the 7.D issue (no captcha alternative), so this text is only not present when it would not be applicable, so it isn't a failure. Also, topic 7 isn't testing on the incremental page 3, so this won't come up anyway.

**Comment by AnnMarieDavis** [comment]
I was able to verify a new randomization was presented on my 3rd attempt.
