### ISSUE TITLE
18.A Dialog boxes do not resize on the practice exam

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#391]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [X] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The modal dialog boxes for errors on the Practice Exam About Registration -fails to Resize. There is no place on the answer sheet to mark this failure.
 
## Location
ZipChip - About Registration Page - Resize - Fails on modal box resize.## Actual Behavior / 

## Observation
When resizing the page, the dialog boxes do not resize. 
![image](https://user-images.githubusercontent.com/31414225/73205510-1b816080-410f-11ea-91d2-d8596952a6e6.png)

## Expected Behavior / Recommendation
Either the behavior must change (and the dialog boxes must resize) or a way to log the error must be provided on the answer sheet.

## Steps to Reproduce the Issue (if applicable)
Issue posted on Practice Exam Q&A Board by John von Plutzner. I observed the same behavior but did not check the answer sheet, but do not remember us having that as an option.

**Comment by Tonylayton1** [comment]
Mike, can dialog boxes be enlarged with the zoom feature? Is this not default browser behavior?

**Comment by mikebarklage** [comment]
No, they can't, and yes this is normal behavior when using default browser alert boxes.

It would be possible to replace the default alerts with custom popup windows that could be zoomed, assuming that doesn't interfere with other Test IDs. But OAST will have to decide whether default alert boxes violate Section 508 rules in the real-world web sites that use them.

**Comment by Tonylayton1** [comment]
Seems to be standard browser behavior. Unless you were expecting anything different on a compliant website in the wild, I believe this should be okay as is.

**Comment by AnnMarieDavis** [comment]
Discussed with Andrew and we agreed this requirement would not apply to these system generated dialog boxes. I will update the guidance on our Q&A pages.
