### ISSUE TITLE
Incremental page 1 7.E 

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#393]
Update default answer for 7.E to True, not DNA.

**Comment by mikebarklage** [comment]
Updated for Topic 7 exam on Dev.

**Comment by Tonylayton1** [comment]
It still says DNA on my correct answer list

**Comment by mikebarklage** [comment]
Sorry, I misread this yesterday. Default now changed to C/True. But I think that's what it already was before I changed it - 7.E is already default True on Prod.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
I marked DNA for 7.E and the scoring counted it as correct.  It should have been wrong as that is not the expected answer. The correct answer should be PASS due to the text in the Workbalance logo.

**Comment by Tonylayton1** [comment]
I thought logos/seals/signage didn't count for this ID?

**Comment by Tonylayton1** [comment]
Change default answer to pass for 7E for topic 7 incremental

**Comment by mikebarklage** [comment]
The default answer for 7.E on Topic 7 (and all other exams) is already PASS on both Dev and Prod. I don't see code that may overwrite that. Can this issue be reproduced?

**Comment by Tonylayton1** [comment]
I concur that the default answer is already Pass. There doesn't appear to be an issue here.

**Comment by AnnMarieDavis** [comment]
verified
