### ISSUE TITLE
Unsecure Connection Issue

### ISSUE THREAD

**Issue by Mhkunicki** [Section508Coordinators/DHSA-TT-200-A#394]
I am working on the Trusted Tester Training for Web on Windows, Topic 8: Adjustable Time Limits.

When clicking on the Adjustable Time Limits - Incremental Practical Exam link I get this warning message:

Your connection is not private
Attackers might be trying to steal your information from exams.section508testing.net (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

Help improve Chrome security by sending URLs of some pages you visit, limited system information, and some page content to Google. Privacy policy.

![Adjustable Time Limits - Incremental Practical ExamExternal tool](https://user-images.githubusercontent.com/52809363/73324019-7f8f4c00-4217-11ea-9fe6-2ceebd3bbdee.PNG)

Please advise.

**Comment by AnnMarieDavis** [comment]
Mike, is their a vulnerability related to this?

**Comment by mikebarklage** [comment]
Jan 28 was one of the days we had to contact Moonami about an expired SSL certificate, which seems to no longer be an issue since March.

**Comment by AnnMarieDavis** [comment]
This issue is being closed due to age. If the student is still having a problem, please contact the Accessibility Help Desk at accessibility@hq.dhs.gov or call 202-447-0440.
