### ISSUE TITLE
Final Exam Passed, but the status in course summary is showing as failed. Please fix!!

### ISSUE THREAD

**Issue by umasarath52** [Section508Coordinators/DHSA-TT-200-A#396]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Final exam pass status is not reflecting in the course summary and unable to proceed with "Exam Wrap-up"

## Location
Course: Trusted Tester - Certification Exam for Web on Windows

## Actual Behavior / Observation
Completed the final exam and passed with 94%. The status of the exam in the course is showing as "Completed: Certification Exam (did not achieve pass grade)". After clicking the main exam link, the message is showed as "No Further Attempt Needed - You have already passed the exam"

I received email as well that I passed the final exam. I am attaching screenshots for your reference.

My email id is umasarath52@gmail.com
[Trusted Tester Final Exam Screenshots.pdf](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/4174055/Trusted.Tester.Final.Exam.Screenshots.pdf)

## Expected Behavior / Recommendation
The final exam status has to reflect properly on the course summary page. I haven't received my certificate even after one week.

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by umasarath52** [comment]
Any update on the issue. It has been 20 days since I received my certificate.

**Comment by drewnielson** [comment]
Doug and team, could you please look into this?

**Comment by AnnMarieDavis** [comment]
certificate has been issued.
