### ISSUE TITLE
Issue with 4.A Skip to Content link

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#397]
## Issue Type 
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [X] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Keyboard is "stuck" on Skip to content link on the About Registration page of the Practice exam. Selecting it does not move to the main content.  This is not an intended failure on the page according to the answer sheet.
## Location
https://exams.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=120924#

## Actual Behavior / Observation
2 students (Mitch Bandes and Jon Buonaspina) experienced this issue and reported it on the Q&A board.  I was able to recreate the issue.

## Expected Behavior / Recommendation
Please fix the bug with the Skip to Main Content button. It is not an option on the answer sheet for 4.A and so needs to behave as expected.

**Comment by Tonylayton1** [comment]
Skip to content has its own failure for 9.A where sometimes selecting it does not advance the focus at all. The button does nothing. Let me know if this is going to confuse students into thinking it is a 4.A issue, otherwise this is broken by design.

**Comment by AnnMarieDavis** [comment]
The page does not advance past repetitive content, but the keyboard is not "stuck" on the link. 
 So this appears to have been resolved.

It is behaving as expected for the answer sheet - it should pass for 4.A and fail for 9.A as you have it.
