### ISSUE TITLE
Incremental 5.E randomization

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#398]
Please double check to make sure 5.E is randomizing. In reviewing feedback, it came up as NC about 20 times in a row.

**Comment by mikebarklage** [comment]
5.E is set to randomize, but it is linked to 4.E, which was not. I've updated 4.C for exam 5 to randomize on Dev.

(Note to myself for later deployment: 4.C is id 12.)

**Comment by mikebarklage** [comment]
This is why I shouldn't update this until I've tested: 4.C is, in turn, linked to 4.A and some other topic 4 IDs. I've updated them to randomize and just got a "c" for 5.E. Topic 4 IDs will appear as "nc" on our answer key page with no associated checkbox.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified in production
