### ISSUE TITLE
Feedback in summary table

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#399]
The new feedback is added in a separate cell from the ID description. Please ensure that the new cell is correctly referencing its th cell by either a) adding the feedback in the same cell as the description b) marking the whole table up as complex c) use a simple table structure with no merged cells (this might make the page very tall with word wrapping but maybe it can be styled to look the same as it does now)

**Comment by mikebarklage** [comment]
I picked option a) since it's easiest. I italicized the feedback to visually separate it, but I'm open to making the UX better than that.

**Comment by Tonylayton1** [comment]
looks good. verified on dev.

**Comment by AnnMarieDavis** [comment]
This has been a huge improvement.  I must admit I'm a little disappointed I haven't seen any comments from students about the new feature.... However, the email traffic may be lighter and I wonder if taking less attempts to pass.
