### ISSUE TITLE
Color Contrast issue with 'CC' and 'D' buttons 

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#4]
The ‘CC’ and ‘D’ buttons have a color contrast ratio that is 3.7:1.
Location: Lesson 2: Language of Parts/Test Requirement page

![image](https://user-images.githubusercontent.com/34749031/58045001-38d94600-7b0f-11e9-9d66-fa39a1536736.png)

**Comment by katbecker** [comment]
Ugh given that this player was supposed designed for accessibility. Anyway, I attempted to overrule the player css setting it to 87% opacity with " !IMPORTANT". That should result in #DEDEDE on #464646. It looks like it respects that override in Firefox and Chrome, but please re-review in your MS browsers: https://dev.section508testing.net/mod/book/view.php?id=800&chapterid=1225

**Comment by HD508Github** [comment]
I tested all three user agents (i.e., Firefox, Chrome and IE11) with the overrule player css setting (87% opacity with " !IMPORTANT") and all three PASSED!  The issue is resolved.  Thanks a bunch Kat.

**Comment by HD508Github** [comment]
Thanks Kat.  I re-tested and the issue is resolved for all three browsers (i.e., Firefox, Chrome and IE11).   GitHub has been updated with this comments as well.

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D4D4A9.1E4A3BD0]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.
