### ISSUE TITLE
4A Home PAge Final

### ISSUE THREAD

**Issue by burgess213** [Section508Coordinators/DHSA-TT-200-A#401]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ X] Incorrect content
-[ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## 
[the HOME page of Clean Brake has a frame section with updates. The pause updates button can be accessed by the keyboard but the Resume updates button cannot be accessed. Plus once pause updates has been selected, tabbing with the keyboard is not operational. Resume updates can only be selected with the mouse.]

## Location
[URL, Topic, Chapter, Subchapter]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]

**Comment by AnnMarieDavis** [comment]
Unable to reproduce the issue.
