### ISSUE TITLE
Admin Section: answers not displaying on attempt following pass

### ISSUE THREAD

**Issue by mikebarklage** [Section508Coordinators/DHSA-TT-200-A#403]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X ] Other, specify...[Admin section bug]

## Description

When a student passes an Incremental Topic exam, then re-opens the same Topic Exam and re-takes it, the subsequent attempt's answers throw an error and are not displayed in the admin section.

The Admin code needs to be updated to handle the case where the "Previous Wrong Answers" dataset exists, but contains no wrong answers.

**Comment by mikebarklage** [comment]
Issue referenced in JIRA DSP-80.

**Comment by mikebarklage** [comment]
Should be fixed on Dev.

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by AnnMarieDavis** [comment]
Verified

Tested in topic 11. Passed first attempt. Made another attempt and missed 11.A. Passed next attempt.  All records correctly reported in the exam admin tool.
