### ISSUE TITLE
15.B answer sheet is not correctly associated with exam

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#405]
## Issue Type
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The correct answer sheet is not associated with an iteration of the incremental exam for 15.B.  The answer sheet is looking for the student to fail the list headings for being linearized content, but the version of the exam presented for this randomized version only linearizes the player button images.

## Location
See exam results for Normita Castro 
https://exams.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=22625&KeyID=149876&ExamID=15&studentEmail=Normita.Castro@associates.fema.dhs.gov

https://exams.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?KeyID=149876

## Expected Behavior / Recommendation
Proper results page needs to be associated with this page.  The page tested PASSED for 15.B

**Comment by Tonylayton1** [comment]
Confirmed. Not sure what happened but the list order is not changing like it is supposed to on the NC variant. When 15.B is NC, the list items should look the same as they do now visually, but the actual order (if viewed with no CSS or linearized) should show list 1 header -> list 2 header -> list 1 content -> list 2 content.
This randomized along with 10.D, could there be a conflict or something with that ID?

**Comment by mikebarklage** [comment]
This randomization was marked as 13.B instead of 15.B, in not one but two locations, somehow. Should be fixed on Dev.

**Comment by mikebarklage** [comment]
It is linked with 10.D, but since 10.D takes precedence, 15.B is only NC in 1/4 of randomized exams instead of 1/2.

**Comment by Tonylayton1** [comment]
verified on Dev

**Comment by AnnMarieDavis** [comment]
Something is still amuck here.  List headers are not displaying as linearized content using ANDI, but the answer sheet is looking for that. 

https://exams.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?studentEmail=annmarie.davis@associates.hq.dhs.gov&SCOInstanceID=322&examId=15
![image](https://user-images.githubusercontent.com/31414225/80102428-b5a34a00-8540-11ea-9552-d4b32f356c98.png)

https://exams.section508testing.net/dhsv5/scormapi/lesson1.php?SCOInstanceID=322&studentName=Ann%20Marie%20Davis&ltiUserId=3382&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=15

**Comment by mikebarklage** [comment]
This change is still only on Dev, but the URLs are from Prod.

**Comment by AnnMarieDavis** [comment]
Verified - ready for deployment.  This is a moderately urgent since the current answer sheet is incorrect.

**Comment by mikebarklage** [comment]
Did Nic sign off on deploying right away?

**Comment by AnnMarieDavis** [comment]
He will be at the meeting on Thursday.  I didn't ask about deploying before then.
