### ISSUE TITLE
Incremental Exam answer sheet for 7.E: 1.4.5-image-of-text

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#410]
Issue submitted on behalf of Sailesh Panchang
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X] Other, specify..Answer sheet choices confusing

## Description
For the four images in the layout table: The choices I have off the result sheet are:
"Qualities table text (all four instance of text next to the images)"
i.e. this does not reference four images of text. and this is followed with four quality images 1 to 4.

## Location
Topic 7, Incremental Exam, answer sheet for 7.E

## Actual Behavior / Observation

- Students testing for images, would not necessarily be aware that the images are contained in a layout table.

-  It would be helpful to include a descriptor, such as: image of a woman, image of runners, etc. 

- It is difficult to distinguish between selecting between the 4 images and the option of the text - the answer sheet does not indicate the text is an image

- Navigating the answer sheet is difficult for blind users as it does not utilize headings to skip between sections

## Expected Behavior / Recommendation

1. Consider revising the way the answers are presented on this answer sheet.
2. Consider using headings on the answer sheets to allow JAWS users to better navigate between sections.

REQUESTED Change is to change the descriptor for Image 1, Image 2, Image 3 to distinguish them.

**Comment by Tonylayton1** [comment]
The answer sheet should not reference the text as images because the text is sometimes just text. Therefore some answer options need to be sufficiently open to applying to multiple randomized variables. Also, if we say the text pieces are images in the answer then it gives it away as the answer.

Would the following be more clear?

"The four stylized paragraphs describing Our Top Qualities"

**Comment by mikebarklage** [comment]
Pending approval, I replaced r2_6 with "The four stylized paragraphs describing Our Top Qualities" on Dev. You may need to refresh local caches to see it.

**Comment by Tonylayton1** [comment]
Text has been updated. The original issue also mentioned making the regions headers, but they are currently fieldsets so a screen reader should recognize what region an individual checkbox belongs to already.

**Comment by AnnMarieDavis** [comment]
Sorry - that is really confusing to me. 

- Let's change the "text" option to "All four instances of text next to 4 pictorial images in Our Top Qualities section." 

You also can't really identify the images as Qualities table Image 1, 2, etc. since the text is sometimes an image, and students have not yet identified this as a table -- that is topic 14 which has not yet been covered.  So let's also change 

-  Qualities table image 1 to "Image of woman in an office"

- Qualities table image 2 to "Image of runners outside an office building"

- Qualities table image 3 to "Image of white towel on a towel bar "

- Qualities table image 4 to "Image of exercise equipment "

**Comment by mikebarklage** [comment]
Updated text for 5 checkboxes on Dev.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified
