### ISSUE TITLE
Disable prev/next page buttons when greyed out

### ISSUE THREAD

**Issue by mikebarklage** [Section508Coordinators/DHSA-TT-200-A#413]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [X] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
When the Previous and Next Page buttons are greyed out, they are not actually disabled - clicking on them will attempt to navigate pages anyway.

This was not a high-priority issue until we added Pre-scoring, where a student might see a list of IDs they skipped and must go back and fix, but can click forward and get scored anyway, possibly resulting in disqualification.

I have fixed this on Dev so grey navigation arrows don't do anything. Ready for QA.

## Location
All exams, technically

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified unable to advance to exam when not all Test IDs are completed. Greyed out advance button is not selectable.
