### ISSUE TITLE
4.A/4.F Practice Page 2

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#415]
Currently, the 4.A failure on page 2 is counting toward 4.F as well and should not be. I also discovered another minor issue is reporting 4.C but they are all related so I'll list them here.

1) remove r3e07 from 4.F when 4.F fails. 
2) 4.F was only counting one of the ends of the keyboard trap, so add r3e03 to 4.F (complete list for 4.F should be [r3e09, r3e03])
3) If it's simple, 4.A no longer has to fail alongside 4.C and 4.F as a block, so it can be unlinked and made independent of the others.

**Comment by mikebarklage** [comment]
Updated on Dev.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
The answer key is failing 4.F for forward and BACKWARD order when there is a looping keyboard trap (4.C). Although we do not have a final ruling from the U.S. Access Board regarding this, we will close this issue and expect students to provide that as an answer.
