### ISSUE TITLE
Practice Exam 4.F page 2 new order issue

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#416]
When 4.C and 4.F fail, swap the order of the Device ID edit text box and the "Get Code" button below it. Add r4e07 to the list of failure reasons for 4.F. 
when 4.F and 4.C fail, the full list should be 
4.C: r3e09, r3e03
4.F: r3e09, r3e03, r4e07

**Comment by mikebarklage** [comment]
Done.

**Comment by AnnMarieDavis** [comment]
Verified by OAST using the Add/Edit answer key.
