### ISSUE TITLE
Incremental topic 4, remove 4.A issue from 4.F

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#417]
When 4.F fails, remove r2e05 from the list of reasons, as this is from the 4.A failure and no longer counts toward 4.F. As a result, 4.A can fail independently from 4.F and 4.C.

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified on page 2 that "Address line 2 Text and associated text entry field" failed 4.A for keyboard access, but did not fail 4.F for focus order. 4.F is not applicable to elements that do not  receive keyboard focus.
