### ISSUE TITLE
Incremental topic 4 - 4.G and 4.H in relation to 4.F

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#419]
When 4.G and 4.H fail, 4.F is being counted as failing for the same reason but I don't think it should be. When 4.F fails, remove r3e01 from the list of failure reasons. This should allow 4.A to fail independently of 4.G/4.H

**Comment by mikebarklage** [comment]
Done.

**Comment by AnnMarieDavis** [comment]
419 and 423 appear to duplicate an issue.  Please point out the difference if I'm missing something.

**Comment by mikebarklage** [comment]
423 is a fix for where the focus lands, this is a change to the answer sheet. By testing 423, you probably tested this one as well, though.

**Comment by AnnMarieDavis** [comment]
OAST verified
