### ISSUE TITLE
Page 2 Page language R3, R4, R5

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#42]
R3 (False for 11.A [g1e13])
The page language is set and it is the incorrect language (french)
R4 (False for 11.A [g1e13])
The page language is set and it is the incorrect language (german)
R5 (False for 11.A [g1e13])
The page language is set and it is the incorrect language (Italian) 

Cliff: Could not get these

**Comment by KSmithO** [comment]
issue that seems like needs resolution before release

**Comment by mikebarklage** [comment]
Not an issue - these are two different False/NC IDs and yourKey.php can only access one of them:

NC ID 2239 means no language attribute (default)

NC ID 4000 means random choice of FR, DE, or IT

The latter case will only appear in generated exam keys, at random.

**Comment by drewnielson** [comment]
Based on response from Mike, closing issue.
