### ISSUE TITLE
answers not saving on truster tester practice exam

### ISSUE THREAD

**Issue by natashaoliveira** [Section508Coordinators/DHSA-TT-200-A#421]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ X] System Bug (the course doesn't function properly)

## Description
Hello - I am taking the 508 Trusted Tester Practice Exam . When submitting my answer sheet, the application directs me to a page that says  "some answers are missing".  I have gone back in to make sure every single question was answered (and still is) but this page will not go away. I have cleared my cache several times. I also noticed that some of the locations for the "missed questions" are for pages that I did not test  (i.e. page 2 or 3) . This is because I am not presented with those pages in the topic areas. When selecting each topic I am only presented with 1 test page. If I am to test the entire site, how are the other pages tracked? 
 
Can someone please help me understand what's going on? 

## Location
[https://exams.section508testing.net/dhsv5/scormapi/lesson1.php?SCOInstanceID=25990&studentName=NaTasha%20Oliveira&ltiUserId=7611&studentEmail=natasha.oliveira815@gmail.com&examId=2

## Actual Behavior / Observation
My selected answer for the exam did not save

## Expected Behavior / Recommendation
Upon submission I should have been directed to a page that calculated my score for the exam

## Steps to Reproduce the Issue (if applicable)

1. Open the answer sheet.
2. Select the “test this page” button.
3. Complete your testing for that topic.
4. Close the web page 
5. Open the next test topic answer sheet. 
6. Repeat steps 2-4 until you finish testing that page.
7. Select the next page of the practice exam and repeat these steps

**Comment by AnnMarieDavis** [comment]
When you fail a Test ID, you must also indicate the element(s) that caused the failure. The exam does not allow students to submit without providing that information because it will be wrong without both pieces of the answer.
