### ISSUE TITLE
Facing problem while submission

### ISSUE THREAD

**Issue by Niharika-9** [Section508Coordinators/DHSA-TT-200-A#422]
Hello,

I am Marreddy Lakshmi Niharika. To retake the certification exam, I was retaking the prefinal exam. While submitting the exam. I was facing  technical issue as exam submission disqualified and below is the screenshot for that. Could you please look into it.
![1590134818348_image](https://user-images.githubusercontent.com/65759107/82645994-6af51a80-9c31-11ea-9180-d2ccd3d4f8be.png)

**Comment by AnnMarieDavis** [comment]
This is not an exam issue. Students answer sheets are disqualified and not graded when students are not adequately applying the test process. This is functioning as designed.
