### ISSUE TITLE
Answer error for 4.G and 4.H

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#423]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The answer sheet fails the page noted below for 4.G and 4.H for the video checkbox.   

I don’t see anything wrong with it. I suspect there was an inadvertent change to the page where the text above the checkbox now is visible before the box is selected – rather than being revealed content that appears after the checkbox is selected.

## Location
https://exams.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=175481

## Actual Behavior / Observation
The only revealed content from selecting the view video checkbox is the video itself appears. That is expected, but the answer sheet fails these test IDs

## Expected Behavior / Recommendation
For this page, change the code to make that revealed content when the checkbox is selected 
OR change the answer sheet to make 4.G and 4.H PASS

**Comment by mikebarklage** [comment]
As I understand it, Practice Page 3 fails 4.G/4.H by moving focus back to the top of the page when the Show Video checkbox is selected. Instead of doing that, it's throwing a Javascript error.

**Comment by mikebarklage** [comment]
Actually, when I test this using my own account on Dev and Prod, it's working as expected - focus moves to the Skip Content link.

**Comment by Tonylayton1** [comment]
The issue is only occurring when 9.A fails as well, causing there to be no skip navigation button. If focus is being sent to the skip nav button, this would make sense as there is no button to send focus to.

**Comment by mikebarklage** [comment]
Ah, that makes sense. And 9.A has 2 NC options, one of which displays the Skip Nav link, so that combination only happens maybe 1/8 of the time. It would explain why we didn't encounter it.

**Comment by mikebarklage** [comment]
Instead of building around that topic 4 vs 9.A conflict, would it be better to send focus to the first top nav link (navItem1, About Registration) instead?

**Comment by Tonylayton1** [comment]
Yes that should be fine

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified by OAST
