### ISSUE TITLE
Frame name seems adequate

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#424]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [X] Other, specify... clear, unarguable test result needed

## Description
Frame names are site_navigation / main_content / site_footer.  

## Location
https://exams.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_main.php?KeyID=175481

## Actual Behavior / Observation
It is arguable that the frame names adequately describe their content. They do appear as file names and "main content" is not particularly descriptive, but a user would know what they would see if they select it. 

## Expected Behavior / Recommendation
Because this is arguable that the "file" names with underscores adequately describe the content, we need a more straightforward example. Perhaps change at least one frame name to something like "frame 2"

**Comment by AnnMarieDavis** [comment]
added label

**Comment by Tonylayton1** [comment]
I'm not sure I understand the issue. The titles are intended to describe the frame, not the filename. How would "frame 2" be more descriptive than "main content"?

**Comment by AnnMarieDavis** [comment]
Can we eliminate the underscores in the frame titles?

**Comment by mikebarklage** [comment]
Yep, updated on Dev.

**Comment by Tonylayton1** [comment]
There are no longer underscores, but there are no spaces. I believe this came up at one point before and we learned that spaces cannot be used in the title. It is debatable whether this alleviates the issue of the titles looking like filenames ("Main_Content" vs "MainContent") which is probably why we didn't make this change sooner.

**Comment by mikebarklage** [comment]
Are you waiting for further clarification on this? Is there any change I should make?

**Comment by AnnMarieDavis** [comment]
Let's make this "Main Content"

**Comment by mikebarklage** [comment]
Updated frame titles to "Site Navigation", "Main Content", and "Site Footer".

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
OAST verified
