### ISSUE TITLE
2.B, Evaluate Result #3

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#425]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Students are expected to pass Page 1 and 2 of the practice exam because there is a disable animation button that stops the animation. However, these are combined with a failure for 6.A because the name of the button does not change to "enable animation". Since it fails 6.A, it technically also fails 2.B since it does not pass evalaution criteria #3 --- AND 3. The mechanism passes all applicable Test Conditions in this test process. 

This option is also not provided on the answer sheet as a reason for the failure.

## Location
https://exams.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/index.php?KeyID=175481

## Expected Behavior / Recommendation
Correct the name/state of the button after it is selected so this is a true pass.  This impacts the answer sheet for 6.A as well - so we need to be sure we make changes in tandem.

**Comment by AnnMarieDavis** [comment]
Arguably this DOES meet the requirement to stop the animation and pass all 2.B requirements. It only subsequently fails for then enabling the automation.

**Comment by Tonylayton1** [comment]
This is not an intended 6.a failure. Recommend just fixing the button to change to "Enable Animation" when the animation is disabled.

**Comment by mikebarklage** [comment]
Updated on Dev - be sure to refresh your browser's JS cache first.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified on page 3 of first attempt and page 1 & 2 of https://exams-dev.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?studentEmail=annmarie.davis@associates.hq.dhs.gov&SCOInstanceID=11171&examId=2

**Comment by AnnMarieDavis** [comment]
OAST verified

**Comment by mikebarklage** [comment]
Followup to what I said in today's call - this item DOES include a JS change, but it only affects the web pages for the Practice exam, not the exam engine.
