### ISSUE TITLE
Practice exam Page 1 4.C and 4.F

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#426]
When we revised the 4.F reporting to include both 4.C points of failure, I missed page 1 of the practice exam. Currently page 1 shows the following when 4.C/4.F fail:

4.C: nc - r5_3, r5_1
4.F: nc - r5_3

Please add r5_1 to 4.F

This should only affect the correct answer reporting.

**Comment by mikebarklage** [comment]
Updated on Dev.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified on Answer sheet for 1st attempt
