### ISSUE TITLE
Final exam request

### ISSUE THREAD

**Issue by rahulkumar8cs** [Section508Coordinators/DHSA-TT-200-A#427]
I have again completed all the incremental exam and practice exam and I am requesting for final exam from last 5 days. 
In my dashboard it is not showing.

Can you please review.
Id-rahulkumar8cs

**Comment by AnnMarieDavis** [comment]
Rahul,
This is not an exam issue - please direct access issues to the Accessibility Help Desk (accessibility@hq.dhs.gov).
