### ISSUE TITLE
Topic 5: ALT Exceeds 250 characters

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#44]
## Issue Type (put an X between the brackets to indicate issue type)
* [ ] System Bug (the course doesn't function properly)
* [ ] Typo/grammar
* [ ] Incorrect content
* [ ] 508 issue (something is not accessible according to our own test process)
* [x ] Other, specify...

## Description
The ALT description exceeds 250 characters.

## Location
https://training.section508testing.net/mod/book/view.php?id=1232&chapterid=2750, 
Topic 5
Forms
DNA Examples, Example 2

## Actual Behavior / Observation
Very long ALT description

## Expected Behavior / Recommendation
Condensed text:  While not a major issue, it is recommended to use the aria-describedby attribute wherever this occurs in the training.  This way, the AT user has the ability to make a selection to hear more information about the image element

## Steps to Reproduce the Issue (if applicable)
ANDI > graphic/images module > navigate to DNA examples, Example 2 image> view ANDI Output and ALT alert 
![Top5_ALT Long Desc (Lesson2-DNA example page)](https://user-images.githubusercontent.com/34749031/59107881-98a16080-8907-11e9-9195-e8db7bcfe558.jpg)

**Comment by KSmithO** [comment]
Not a 508 issue but something to consider during course updates.

**Comment by HD508Github** [comment]
Correct, not a 508 issue; but I had brought to Andrew’s attention to address in the future, if needed.

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D4D4A9.1E4A3BD0]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.
