### ISSUE TITLE
Page 2, region 4 R2 (True for 10.D, False for 13.B [r4e03, r4e04, r4e05, r4e06] and 15.B  [r4e03, r4e04, r4e05, r4e06], and 15.C [r4e03, r4e04, r4e05, r4e06])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#48]
R2 (True for 10.D, False for 13.B [r4e03, r4e04, r4e05, r4e06] and 15.B  [r4e03, r4e04, r4e05, r4e06], and _15.C [r4e03, r4e04, r4e05, r4e06])_
The two lists appear as they do in the mockup. 
When viewed inline without CSS, the headers and lists are ordered on the page as follows: “Standard Certified” header, “Super Certified” header, Standard Certified list items, Super-Certified list items. 
Each group of list items is nested in an appropriate list tag.

Comment: All the below have a strike through them:
_and 15.C [r4e03, r4e04, r4e05, r4e06])_

Cliff: When 15.B set to NC, reading order of lists is still correct. Reading order seems to be controlled by other test ID. Don’t know if this is an issue or will happen in “real” test. But if not you may want to not allow NC setting of 15.B separately.
![image](https://user-images.githubusercontent.com/34742733/59109074-5d546100-890a-11e9-9218-0b2268bf250c.png)

**Comment by mikebarklage** [comment]
This is the result of using the yourKey.php page, which does not automatically change linked IDs. It won't happen for students.

**Comment by drewnielson** [comment]
Thanks @mikebarklage. @cliffbert, any follow up or further question before we close the issue?
