### ISSUE TITLE
Page 2, region 2 Play/Pause button R1

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#51]
Play/Pause button 
R1 
Button is named correctly and toggles appropriately between pause and play. 

Cliff: Icons not visible in IE11. May need to use “normal” images.

Also – typo “receive”
![image](https://user-images.githubusercontent.com/34742733/59109717-8c1f0700-890b-11e9-9e51-9ae25230c339.png)

**Comment by KSmithO** [comment]
need to understand more if the icons 'matter' for testing purposes in order to determine impact

**Comment by Tonylayton1** [comment]
The icons do not matter for testing and their disappearance could not be verified on our end. The typo has been fixed and verified

**Comment by AnnMarieDavis** [comment]
Spelling of receive has been corrected.
IE does not display the icons, but they are not crucial to the functionality and we tell people NOT to use IE for the course... so if you don't read instructions, you get what you get...
