### ISSUE TITLE
Page 3, Region 1 About Link R2 (False for 4.F [r1e03])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#53]
R2 (False for 4.F [r1e03])
Link is as presented in the mockup, but its tab order is switched  with the “Data” link. Linked to R2 of “Data” link

Cliff:  This switch doesn’t really impact the meaning or operability of the page – need something more confusing, e.g. focus on Submit button before Get Captcha or other form fields.

The other fails for 4.F seem ok.
http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page3_main.php?studentEmail=cliff.soon@hq.dhs.gov&SCOInstanceID=56&examId=4

**Comment by mikebarklage** [comment]
This 4.F failure removed from exam on Dev, kept other 4.F failures on same page, waiting for approval.

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by AnnMarieDavis** [comment]
Answers have been changed for 4.F so that users should select the LAST item that received focus.  Carney has made the requested change and the issue can close.
OAST still needs to clarify instructions how to respond on answer sheets for FOCUS questions.
