### ISSUE TITLE
Page 3, Region 2 Company Name* Text and associated text entry field- (False for 5 .A [r2e03], 5.B [r2e03], and 13.A [r2e03])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#55]
R3 (False for 5 .A [r2e03], 5.B [r2e03], and 13.A [r2e03])
Text is as presented in the PSD except the asterisk is omitted. The associated text entry field is present and accessible. 

Cliff: All these 5.A fails should be C, per comments for Final – 5.A only evaluates presence of visual labels, not whether they are accurate

**Comment by KSmithO** [comment]
This is a late edition change since we added a new test ID and changed what 5A was looking for. Will need instructions for students on how to handle this in exam since training/test process have 1 test ID and the exams have the old version implemented.

**Comment by Tonylayton1** [comment]
As per issue #125 , ensure the test names are accurate when new ID is added.

**Comment by AnnMarieDavis** [comment]
Dependency for this fix is for the answer sheet to be updated for Topic 5 forms:
(Descriptions are only provided when they are different then the previous test condition)
5.A Forms (Label Provided) — 3.3.2-label-provided
       Labels or instructions are provided for form elements.
5.B Forms (Descriptive Label) —2.4.6-label-descriptive 
       Each form label is sufficiently descriptive.
5.C Forms (Programmatic Label) — 1.3.1-programmatic-label
5.D Forms (On Input) — 3.2.2-on-input
5.E Forms (Change Notification) — 4.1.2-change-notify-form
5.F Forms (Error Identification) — 3.3.1-error-identification
5.G Forms (Error Suggestion) — 3.3.3-error-suggestion
5.H Forms (Error Prevention) — 3.3.4-error-prevention

**Comment by Tonylayton1** [comment]
Documentation updated, see randomization doc, default results spreadsheet, and updated checkbox array list. 

Summary: the failures that were already being used for the old 5.A can be used for the updated/new 5.B, so 5.A along with everything else is simply shifted down 1 ID (failures for 5.A through 5.H become failures for 5.B though 5.G respectively).

A new failure for 5.A has been specified on the randomization doc - yes and no labels are removed from 2 radio buttons, but aria labels will ensure they still pass 5.C. 

The Checkbox array has been updated so that the fieldset and each radio button are their own entries, rather than being grouped into 1 entry. 

when 5.A is NC, it should fail for r3_09 and r3_10.

**Comment by AnnMarieDavis** [comment]
We no longer use the term Not Compliant or NC in the test process. Change ALL instructions as follows:

Select all elements that FAIL Test ID ... [leave the test ID # at the end of the instructions]

**Comment by AnnMarieDavis** [comment]
This impacts all exam answer sheets for Topic 5.

**Comment by Tonylayton1** [comment]
Issues with topic 5 new ID and renumbering:

When 5.A is failing, the visual labels on the "yes" and "no" buttons on the test webpage are still present
The checkbox list has not been expanded to include the separated radio buttons; region 3 should have 13 checkboxes now
5.G is opening the global checkbox list, and 5.H is opening the page specific list - should be the opposite

**Comment by mikebarklage** [comment]
I missed a couple of code updates for the 5.G/5.H change - one in the JS engine, the other in the PHP script that refreshes the JS exam data. It should be working now and I've also updated the Updating Test IDs doc.

**Comment by Tonylayton1** [comment]
5.G/5.H issue is fixed. 

5.A failure still not working correctly, as the visual yes and no labels are present regardless of the pass or fail setting. The checkbox list array is also still not expanded to 13 items in region 3.

**Comment by mikebarklage** [comment]
I had interpreted that as removing the label tag but not the text. Both are gone now.

I also added the new checkboxes to topics 4, 5, 8, and 16.

**Comment by Tonylayton1** [comment]
verified on dev. note: i had to clear my local cache for the new checkboxes to show up.

**Comment by AnnMarieDavis** [comment]
the answers for the incremental did not line up with the Test IDs on my attempt this evening and page content shifted... may be a VPN issue, so I will clear testing cache and retake this in the morning...

**Comment by drewnielson** [comment]
Verified in dev. Ann Marie, go ahead and re-open if you still see an issue, but my guess is that it was a cache issue for you.
