### ISSUE TITLE
Page 3, Region 2  State* Text and associated text entry field- R2 (False for 4.C [r2e09] and 4.F [r2e09])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#57]
R2 (False for 4.C [r2e09] and 4.F [r2e09])
***Same  as R1 except that when the user tabs out of the “State*” field, it moves focus up to the “Company Name*” field

Cliff: ***In Edge, more than one field is highlighted at the same time when this happens

**Comment by KSmithO** [comment]
This may be an issue we need to look in to for impact on students

**Comment by Tonylayton1** [comment]
Inadvertently solved by addressing #60

**Comment by AnnMarieDavis** [comment]
Verified
