### ISSUE TITLE
Page 3, Region 4-Submit button, R1 (True for 5.E, 5.F, and 5.G)

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#61]
R1 (True for 5.E, 5.F, and 5.G)
An accessible submit button with appropriate label.
Upon selecting submit, a confirmation dialogue box appears that asks “Are you sure the information you have provided is correct?” with the options “Yes, submit” and “No, review information”. The latter closes the dialogue box and the user remains on page 3
When the user selects “Yes, submit”, the page should perform all of the checks described in the “Page3 error dialogues on form submit”, and if any errors are present dialogue boxes with appear, and the user will remain on the page after all dialogues have been closed .

Cliff Comment: For #1226, the key said fail 5.F, but it did show me the formats for these fields in the error dialogs
![image](https://user-images.githubusercontent.com/34742733/59111483-1f0d7080-890f-11e9-9226-e221c58ce0d4.png)
![image](https://user-images.githubusercontent.com/34742733/59111494-246abb00-890f-11e9-8ca5-dfa6db25fdec.png)
![image](https://user-images.githubusercontent.com/34742733/59111508-26cd1500-890f-11e9-8d60-2ae7bf9d1a35.png)
![image](https://user-images.githubusercontent.com/34742733/59111515-29c80580-890f-11e9-8e24-ba1d01da1608.png)

**Comment by Tonylayton1** [comment]
Could not replicate

**Comment by AnnMarieDavis** [comment]
Dependency for this fix is for the answer sheet to be updated for Topic 5 forms:
(Descriptions are only provided when they are different then the previous test condition)
5.A Forms (Label Provided) — 3.3.2-label-provided
       Labels or instructions are provided for form elements.
5.B Forms (Descriptive Label) —2.4.6-label-descriptive 
       Each form label is sufficiently descriptive.
5.C Forms (Programmatic Label) — 1.3.1-programmatic-label
5.D Forms (On Input) — 3.2.2-on-input
5.E Forms (Change Notification) — 4.1.2-change-notify-form
5.F Forms (Error Identification) — 3.3.1-error-identification
5.G Forms (Error Suggestion) — 3.3.3-error-suggestion
5.H Forms (Error Prevention) — 3.3.4-error-prevention

**Comment by drewnielson** [comment]
@AnnMarieDavis, I'm not sure that is what @cliffbert was getting at with this issue. Your description would already be covered by issue #55. We'll need to clarify with @cliffbert.

**Comment by AnnMarieDavis** [comment]
Oops!  Looks like inadvertently put in that content. However, it may be helpful to reference that info since the test conditions cited are not the updated numbering... and a fix may need to take into account that related updated.

**Comment by drewnielson** [comment]
@cliffbert, can you review the original comment and clarify? Tony is not able to replicate the issue, so just want to make sure that we have clearly identified and described the issue.

**Comment by cliffbert** [comment]
@drewnielson @Tonylayton1 Had a 5.F fail although the page did show me the required formats per above. Let me know if this needs more clarification, otherwise if you can't replicate it, it may have been fixed.

**Comment by AnnMarieDavis** [comment]
I am not getting specific error messages in the Practice Exam.  Instead the message states: 52.23.182.152 says Error.  I entered all the required  formats incorrectly on the practice test and received the same message twice.
![2019-07-08_issue  61](https://user-images.githubusercontent.com/31414225/60814553-d7734200-a163-11e9-8b59-cf3ea2033d8d.png)

http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=148&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=5

**Comment by Tonylayton1** [comment]
Cannot replicate. If 5.G (previously 5.F) is marked as a failure, it correctly does not give the format instructions in the error messages. Note: manually toggling 5.G to NC may cause issues, as the ID is wrapped up with other IDs.

**Comment by drewnielson** [comment]
Closing the issue. I think @AnnMarieDavis's issue was unrelated to original issue and due to a misunderstanding of the content. As for the original, since we cannot replicate, we cannot adequately address. Will reopen or will open a new issue when/if we can better identify.
