### ISSUE TITLE
Page 3, region 7: data device link-R2 (False for 6.A [r7e02], 6.B [r7e02], and 9.C [r7e02 ])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#68]
R2 (False for 6.A [r7e02], 6.B [r7e02], and 9.C [r7e02 ])
As above, but the link text is “link”

Cliff: Should be 5_2

**Comment by Tonylayton1** [comment]
Issue could not be replicated - correct answer is 7_2

**Comment by AnnMarieDavis** [comment]
No issues noted on page with 6.A or 6.B - results are properly recorded for incremental.
