### ISSUE TITLE
Draft specific instruction for reporting loss of focus in exams

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#7]
In addition to the instruction, also need to decide where to provide the instruction

**Comment by drewnielson** [comment]
Pretty sure that @cliffbert addressed this sufficiently directly in the exam content, on the response options page of the exam. @cliffbert, do you think we need any additional instruction in the course, or should we consider this done?

**Comment by cliffbert** [comment]
Done, unless you want to see it in action first

**Comment by drewnielson** [comment]
Nah, we can follow up under the revisions already provided to Carney.
