### ISSUE TITLE
Topic 5: iFrame CCA issue (Button text)

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#70]
## Issue Type (put an X between the brackets to indicate issue type)
* [ ] System Bug (the course doesn't function properly)
* [ ] Typo/grammar
* [ ] Incorrect content
* [ x] 508 issue (something is not accessible according to our own test process)
* [ ] Other, specify...[replace this text with your issue type description]

## Description
Text on the 'Add to Cart' button has a color contrast ratio (3.2:1) that is less than 4.5:1

## Location
URL: https://training.section508testing.net/mod/book/view.php?id=1232&chapterid=2758
Topic 5
Chapter: Forms, DNA examples]

## Actual Behavior / Observation
[Describe what you observed or the error you found]

## Expected Behavior / Recommendation
CC should be a minimum of 4.5:1
## Steps to Reproduce the Issue (if applicable)
Topic 5 > Lesson 3 > DNA examples > ANDI module > select iframe > click 'text in new tab' button > open CCA > test foreground and background of button text
![Top5_iFrame CCA Issue (Lesson3-DNA example page)](https://user-images.githubusercontent.com/34749031/59123252-d06dcf80-892a-11e9-9b44-f577850b2c11.jpg)

**Comment by KSmithO** [comment]
Color contrast requirements do not apply for inactive (disabled) user interface components. This button is inactive bc those cute puppy tshirts are all sold out.

**Comment by drewnielson** [comment]
Agreed with @KSmithO; from the test process:
### Color Contrast
#### Identify Content
Identify ALL text AND images of text.
**EXCLUDE** text that is:
* In logotypes: logo or brand name
* For ***inactive (disabled)*** [emphasis added] user interface components
...

**Comment by HD508Github** [comment]
Correct--I realized this one of the exceptions to the CCA standard.  Thanks!

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D4D4A9.1E4A3BD0]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.
