### ISSUE TITLE
2 items in Moodle

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#72]
1.	Can we remove the now defunct TTY number from the footer of each page:  
![image](https://user-images.githubusercontent.com/34742733/59195993-799b0c80-8b5b-11e9-9845-0d6df14196c1.png)

**Comment by katbecker** [comment]
I can do #1 quick and easy once assigned, but #2 is from a plug in. We'd asked John/Moonami to put it into a new block with a better name, but I think that got lost. Can we break that task off of this one?

**Comment by KSmithO** [comment]
Broke off to issue #73

**Comment by katbecker** [comment]
Removed. I noticed that the training templates have fax, but the main site template doesn't: should that be removed, too?

**Comment by drewnielson** [comment]
Actually, we still have a functioning fax machine, so I guess we can keep it.
