### ISSUE TITLE
Topic 5: ALT and ANDI Output requires an update

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#74]
Location: Topic 5 > Lesson 3 > Passing examples > Example 2 image
Issue: The ALT and ANDI Output is missing the word 'required' from the ANDI Output highlighted area within the image.
![Top5_ALT Desc Examp2 (Lesson3-Passing example page)](https://user-images.githubusercontent.com/34749031/59211644-52a20200-8b7e-11e9-991a-460791037317.jpg)

**Comment by KSmithO** [comment]
Ready for retest

**Comment by HD508Github** [comment]
Re-tested and the issue is resolved.
![image](https://user-images.githubusercontent.com/34749031/59215798-2be8c900-8b88-11e9-942b-9170af958848.png)
