### ISSUE TITLE
Topic 5: Color Contrast issue with image text

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#75]
Location: Topic 5 > Lesson 6 > How to Test page > Sign in image
The error message text in the image has a color contrast ratio (4.7:1) that is below 4.5:1.
![Top5_CCA Issue (Lesson6 How to Test page)](https://user-images.githubusercontent.com/34749031/59212997-d5788c00-8b81-11e9-80b9-ed5f7a90ddbc.jpg)

**Comment by KSmithO** [comment]
Maybe I am misunderstanding, but 4.7:1 is higher than 4.5:1.  This does not appear to be a failure.

**Comment by HD508Github** [comment]
Sorry Kristen, this was logged in error.  Please close.

Kind Regards,
Halimatou(Halima)Diallo
Sr. Accessibility Technician
Supporting the Department of Homeland Security|MGMT/OCIO/OAST
Office: 202-815-5957
Email: Halimatou.Diallo@associates.hq.dhs.gov<mailto:Halimatou.Diallo@associates.hq.dhs.gov>
DHS Accessibility Help Desk: 202-447-0440 (Voice), 202-447-0582 (Fax)
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/> | Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>
[cid:image001.png@01D4D4A9.1E4A3BD0]
This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this message in error, please reply immediately to the sender and delete this message.  Thank you.

**Comment by KSmithO** [comment]
done

Thanks,
Kristen Smith| Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 774-0382;  (202) 578-8845
Email: Kristen.Smith@associates.hq.dhs.gov<mailto:Kristen.Smith@associates.hq.dhs.gov>

DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/>
 Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If  the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this in error, please reply immediately to the sender and delete this message.
