### ISSUE TITLE
Topic 5: Color Contrast issue with image text

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#76]
Topic 5: Lesson 5 > Failing examples > Example 1 image
Issue: The alert message has a color contrast ratio (4.3:1) that is less than 4.5:1.  Similar issue exists in Topic 6, Passing examples.
![Top5_CCA Issue (Lesson5 Failing example page)](https://user-images.githubusercontent.com/34749031/59213187-491a9900-8b82-11e9-9ff6-232681747cd8.jpg)

**Comment by drewnielson** [comment]
Image comes from an external source, cannot fix. Accompanying text conveys the same information.
