### ISSUE TITLE
Need language on knowledge check completion page to tell people what to do next

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#78]
As a student, I do not know what to do after I complete and pass the knowledge checks. A sentence with instructions on how to go back to the table of contents, or a button to move to the next activity would be helpful:

![image](https://user-images.githubusercontent.com/34742733/59213545-20df6a00-8b83-11e9-9b0b-8652613874b7.png)

**Comment by drewnielson** [comment]
For now, without actually modifying the Moodle code (which would require Moonami support) the only way I could think of was to include something in the "overall feedback" for each quiz - a previous suggestion from Kat. I added a link (that looks like a button) to "Return to Course Main Page". The only problem is that it shows up as "feedback" in a couple places. @KSmithO take a look and let me know what you think...
![image](https://user-images.githubusercontent.com/29068131/59232850-138ea380-8bb4-11e9-9209-0f200cb9e8b1.png)

also here...
![image](https://user-images.githubusercontent.com/29068131/59232893-42a51500-8bb4-11e9-87d6-b36dc8c21ade.png)

**Comment by KSmithO** [comment]
I like it! Its slightly awkward where it is now but my focus was on the button, not "feedback". Not crazy elegant but functional and works appropriately,

**Comment by drewnielson** [comment]
OK, I'll consider this fixed then.
