### ISSUE TITLE
Topic 5: Color Contrast Issue

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#79]
Location: Topic 5 > Lesson 7 > How to Test page
Issue: Image text has a color contrast ratio of 4.4:1, which is below 4.5:1 requirement.
![Top5_CCA Issue (Lesson7 How to Test page)](https://user-images.githubusercontent.com/34749031/59213560-2ccb2c00-8b83-11e9-88bc-81d747bf3ef3.jpg)

**Comment by drewnielson** [comment]
Fixed: changed image to black and white. @HD508Github, please verify.
