### ISSUE TITLE
Topic 5: Color Contrast Issue with image text

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#80]
Location: Topic 5 > Lesson 7 > Passing examples page > Example 2
Issue: The red text in the image has a color contrast ratio (4.1:1) that is below 4.5:1.
![Top5_CCA Image Issue (Lesson7 Passing example page)](https://user-images.githubusercontent.com/34749031/59213787-ae22be80-8b83-11e9-9b5d-a67d4aadb4c9.jpg)

**Comment by drewnielson** [comment]
The image in question is coming from an outside source, so we cannot fix. The accompanying text is sufficient to convey the same information.
