### ISSUE TITLE
Topic 5: Color Contrast Issue with image text

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#81]
Location: Topic 5 > Lesson 8 > Passing examples page > Example 1 (2nd image)
Issue: The error message text associated with the 'New password' and 'New password (again)' input fields have a color contrast ratio (3.1:1) that below 4.5:1.
![Top5_CCA Image Issue (Lesson8 Passing example page)](https://user-images.githubusercontent.com/34749031/59215086-5d609500-8b86-11e9-8594-3f34ea4545f7.jpg)

**Comment by drewnielson** [comment]
This image is coming from an outside source, so we couldn't fix it anyway. Although the image of text itself does not pass for color contrast, our description of the issue in the course text passes for color contrast and is sufficient to convey the information contained in the image.
