### ISSUE TITLE
Topic 5: Color Contrast Issue with images

### ISSUE THREAD

**Issue by HD508Github** [Section508Coordinators/DHSA-TT-200-A#82]
Location: Topic 5 > Lesson 8 > Passing examples page > Example 3 images
Issue: Both the green "plus' sign image (2.2:1) and the red "X" sign image (4.2:1) have color contrast ratios that are less than 4.5:1.
![Top5_CCA Image Issue (Lesson8 Failing example page)](https://user-images.githubusercontent.com/34749031/59215384-1b841e80-8b87-11e9-9adf-039cd0870161.jpg)

**Comment by drewnielson** [comment]
Fixed. @HD508Github please verify
