### ISSUE TITLE
Text for Incremental exams reference the "certification" exam

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#83]
In Incremental exams, the language on screen references the "certification exam" which is confusing.
![image](https://user-images.githubusercontent.com/34742733/59215747-052a9280-8b88-11e9-82d1-391d4405a91f.png)

![image](https://user-images.githubusercontent.com/34742733/59215769-12e01800-8b88-11e9-9ff8-c3af82d803df.png)

**Comment by cliffbert** [comment]
Per email 5/30/19, text will be changed to:

Congratulations! You scored 100% on the Incremental Exam. Close this window and return to the course window to continue.
--
Nice Try! You scored 10% on the Incremental Exam. The minimum required score for passing is 100%.  Close this window and return to the course window to either review the topic or retake this exam.

**Comment by mikebarklage** [comment]
Text updated on Dev, waiting for approval.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified via spot check of a few pages for both Congratulations and Nice Try messages.
