### ISSUE TITLE
Incremental Exam language references IE9

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#84]
Incremental Exam page references IE9-seems unnecessary for a number of reasons, one being we tell them to not use IE and another that IE9 is crazy old

![image](https://user-images.githubusercontent.com/34742733/59216058-d103a180-8b88-11e9-872e-4d1855ae9256.png)

**Comment by cliffbert** [comment]
Per email 5/30/19, text will be changed to:

Do   NOT test COTS plug-ins. The test results of COTS plug-ins are not reported   here.    Select   Test This Page to open a new window with the content to be tested,   along with the ANDI tool. Report the test results for this topic using Enter   Results (or Modify Results) below. When done, navigate to the next   page to submit your results.
--

**Comment by mikebarklage** [comment]
Text update on Dev, waiting for approval.

**Comment by Tonylayton1** [comment]
Verified on Dev

**Comment by AnnMarieDavis** [comment]
Spot checked 5 different topics and the requested language appears.
