### ISSUE TITLE
Interactive Example 2 on Repetitive content DNA examples

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#85]
https://training.section508testing.net/mod/book/view.php?id=1244&chapterid=2902

## Issue Type (put an X between the brackets to indicate issue type)
- [x ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
the interactive example doesn't open in Chrome (doesn't connect message) or IE (doesn't open in frame - open in a new window) It does eventuallly load 

## Location
[https://training.section508testing.net/mod/book/view.php?id=1244&chapterid=2902, Topic 9, Lesson 3, DNA example 2]

## Actual Behavior / Observation
wouldn't open in Chrome initially.  After 10 mintues it did finally load.  In windows, user must open in a new window

## Expected Behavior / Recommendation
Interactive example load immediately 

## Steps to Reproduce the Issue (if applicable)
it finally loaded after 15 minutes

**Comment by drewnielson** [comment]
Fixed
