### ISSUE TITLE
Topics that need the restrictions set

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#88]
Topic 5: Forms ![image](https://user-images.githubusercontent.com/34742733/59217641-66ecfb80-8b8c-11e9-86b4-e15eff9b7858.png)
Topic 11: language
![image](https://user-images.githubusercontent.com/34742733/59219919-905c5600-8b91-11e9-8a09-d20382e33ac4.png)
Topic 17: sync media
![image](https://user-images.githubusercontent.com/34742733/59219950-ad912480-8b91-11e9-859b-4c3ab420cc1b.png)

**Comment by drewnielson** [comment]
Updated all three to include the restrictions.
