### ISSUE TITLE
Remove Glossary and Resources from incremental exam pages

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#90]
remove glossary and resources link from incremental exam pages (old data):

![image](https://user-images.githubusercontent.com/34742733/59222686-0e236000-8b98-11e9-87ed-8a43ab57c95d.png)

**Comment by cliffbert** [comment]
Note: Title of issue does not match screenshot

Per email 5/30/19, text will be changed to:

Do   NOT test COTS plug-ins. The test results of COTS plug-ins are not reported   here.    Select   Test This Page to open a new window with the content to be tested,   along with the ANDI tool. Report the test results for this topic using Enter   Results (or Modify Results) below. When done, navigate to the next   page to submit your results.
--

**Comment by knpmartin** [comment]
Issue #84 was entered to address the issue of the incorrect text. This issue appears to be addressing the problem with selecting the Resources link in the exam. The link opens the Resource window for 3.4.1/4.0 
content.

http://3.217.25.10/dhsv5/dhscourse/common/resources/resources.html

**Comment by mikebarklage** [comment]
Links removed on Dev, waiting for approval.

**Comment by Tonylayton1** [comment]
Links have been removed

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by AnnMarieDavis** [comment]
Verified that all incremental practice exam pages only contain Help | Exit buttons.
