### ISSUE TITLE
Provide explicit instructions for users on selecting "EXIT" when finished with incremental exam

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#91]
Students MUST select Exit if they need or want to re-take the incremental exam; otherwise the web page does not 'reset' for them to re-take the incremental. Need to alert students that they just MUST select EXIT each time

![image](https://user-images.githubusercontent.com/34742733/59222727-2b582e80-8b98-11e9-932a-c1242819496a.png)

**Comment by drewnielson** [comment]
Might also want to include instruction that they will need to refresh the course page in order to update the status of their incremental exam and continue with the following activity.

**Comment by AnnMarieDavis** [comment]
Suggest Added text: 
After you test this page and have entered your results button, refresh the course page to update the status of the incremental exam. To retake missed test IDs or for further topic test practice, select the EXIT button in the menu banner at the top of the page.

**Comment by KSmithO** [comment]
Changed in Course Intro-still needs to change on each incremental exam page

**Comment by mikebarklage** [comment]
Per another item on the list, I've changed the instruction text above the exam UI to this:

"Do NOT test COTS plug-ins. The test results of COTS plug-ins are not reported here.

Select Test This Page to open a new window with the content to be tested, along with the ANDI tool. Report the test results for this topic using Enter Results (or Modify Results) below. When done, navigate to the next page to submit your results."

How would these new instructions fit in with that text?

**Comment by mikebarklage** [comment]
Will add new text to the Scoring Results page.

**Comment by AnnMarieDavis** [comment]
This may be OBE if Mike is able to make the submit results perform the update that is currently happening only with the Exit button.

"Do NOT test COTS plug-ins. The test results of COTS plug-ins are not reported here.

Suggest this:
1. Select Test This Page to open a new window with the content to be tested, along with the ANDI tool. 
2. Report the test results for this topic using Enter Results (or Modify Results) below. 
3. When done, navigate to the next page to submit your results. 
4. Refresh the course page to update the status of the incremental exam. 
5. IMPORTANT: Select the EXIT button in the menu banner at the top of the page to update the Dashboard with the status.

**Comment by Tonylayton1** [comment]
I'm not sure if this is addressed fully. Moving to review - please provide more guidance if needed.

**Comment by AnnMarieDavis** [comment]
Suggested instructions are provided on each page as appropriate.

**Comment by puffybc** [comment]
This is still very unintuitive.
There should just be a "Retake" button and the refreshing etc should be done automatically with a new webpage to test loaded.
