### ISSUE TITLE
Issue with 9.C incremental exam

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#92]
9.C needs to have more than 1 web page to be considered. Its tough in the incremental b/c a user is only presented 1 web page, not a web site. In theory, 1 web page would make this DNA:

![image](https://user-images.githubusercontent.com/34742733/59224543-ac192980-8b9c-11e9-8c25-cd27247ddb30.png)

**Comment by drewnielson** [comment]
Hmmm, are we expecting them to limit their test to just the page that opens by default when they click on "Test this page" or wouldn't it include the full set of 3 pages that is generated ("About", "Data", and "Request an Audit")?

**Comment by KSmithO** [comment]
Here is the issue-each page, when it opens, generates the ties to the other pages as well. In every other scenario, we are asking them to only test the page they are presented. In this case, if we want them to NOT follow the logic, we should tell them to test the other pages presented as well for {X}-only 9.C? not 9A and 9B as well (does it matter)?

Thanks,
Kristen Smith| Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 774-0382;  (202) 578-8845
Email: Kristen.Smith@associates.hq.dhs.gov<mailto:Kristen.Smith@associates.hq.dhs.gov>

DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/>
 Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If  the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this in error, please reply immediately to the sender and delete this message.

**Comment by mikebarklage** [comment]
Added extra instruction text to Topic 9 exam to address this, waiting for approval.

**Comment by Tonylayton1** [comment]
Instructions have been added.

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by AnnMarieDavis** [comment]
1. Place the new language in _italics_ so it stands out. I also recommend it be placed first on the page otherwise students may miss these instructions thinking it's the same instructions they've seen each time before.
2. Change Practical to Practice Exam 
3. Ensure the answer key is also scoring 9.A for all three pages as well.  
New language 
_For the purpose of the Topic 9 Incremental Practice Exam only, you must test across all three of the test pages presented when you select the "Test this Page" button. ("About," "Data," and "Request an Audit")_

**Comment by mikebarklage** [comment]
I have updated the language on Dev.

**Comment by AnnMarieDavis** [comment]
Verified new language and that it stands out making it less likely to be "missed" by students.
