### ISSUE TITLE
11 B answer for incremental-may not be correct?

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#94]
I did not see another language on the page for 11B to be C:

![image](https://user-images.githubusercontent.com/34742733/59225479-d53ab980-8b9e-11e9-9efd-80c9592a60b3.png)

**Comment by drewnielson** [comment]
Made the same observation on the generated page.

**Comment by mikebarklage** [comment]
German text always appears, either with or without a proper language tag: "Besser laufen, als faulen!"

**Comment by drewnielson** [comment]
Looks like we just missed the German text. Also looks like this might actually be an ANDI bug (see screenshot).
![image](https://user-images.githubusercontent.com/29068131/59374181-47cfa480-8d19-11e9-886c-71988bcecca4.png)
I'll send to the ANDI developer.

**Comment by drewnielson** [comment]
Wait, nevermind. Kristen and I simply tested it incorrectly (i.e., didn't follow our own process). We didn't notice it is inside an iframe, so ANDI only picks up the language attribute once we open the iframe content in a new window. Closing the issue.

**Comment by drewnielson** [comment]
Reopening issue, because it will still cause problems for students. Removing from Carney's list, but still something we need to address. Since the course doesn't cover iframes until Topic 12, a student may not know that they need to open iframe content in a new window to perform other tests, e..g, 11.B and plenty of previous tests. @cliffbert, @AnnMarieDavis, @KSmithO, should we consider moving Topic 12 earlier in the course to address this issue?

**Comment by mikebarklage** [comment]
Or we could move the German phrase to the main page, outside of the iFrame.

**Comment by cliffbert** [comment]
Even if we move it, it seems kind of too much to expect. I think Mike's suggestion has better chance of success.

**Comment by KSmithO** [comment]
Agreed to cliffs comment. Two other thoughts though:
1) are there any additional tests and content in that iframe that require students to know to open the iframe directly before they get to topic 12 in order to achieve the correct test result?
2) another option is to put a line of text in the training, maybe up front in course intro/test tools and on each splash page of the incremental exam reminding students that to test content in an iframe, you need to open that iframe to test content ( and provide simple instructions on how to do that).

Thanks,
Kristen Smith
Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 578-8845; (202) 774-0382
Email: Kristen.Smith@associates.hq.dhs.gov
DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov
Email: accessibility@hq.dhs.gov
________________________________

**Comment by drewnielson** [comment]
The content in the iframe is a table, which is addressed in Topic 14, so I think we should be fine to just move the German text out of the iframe and into the main body of page.

**Comment by drewnielson** [comment]
Just brought to our attention that the heading "Advantages of certification" within the iframe could also be an issue, since students test for heading structure in the Topic 10 incremental (before they receive guidance about testing iframe content). If possible, we should also move the heading just above the iframe instead of having it inside the iframe.

**Comment by mikebarklage** [comment]
On Dev, moved the German text above the iFrame, updated checkboxes and answers as a result, waiting for approval.

**Comment by AnnMarieDavis** [comment]
For the page I tested in dev, ANDI did not identify the German phrase and the main page language was it not en.  I failed both, but was told the answer was wrong.

**Comment by AnnMarieDavis** [comment]
Suggest both moving the text outside of the iframe and possibly making the German text a separate paragraph rather than putting it in a <span> for now.

**Comment by KSmithO** [comment]
Hmm-I had this page: http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/page2_main.php?studentEmail=Kristen.Smith@Associates.HQ.DHS.GOV&SCOInstanceID=136&examId=11

And it identified everything correctly (page lang correct, part of lang not correct b/c not identified and German no longer in iframe).

Thanks,
Kristen Smith| Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 774-0382;  (202) 578-8845
Email: Kristen.Smith@associates.hq.dhs.gov<mailto:Kristen.Smith@associates.hq.dhs.gov>

DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/>
 Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If  the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this in error, please reply immediately to the sender and delete this message.

**Comment by mikebarklage** [comment]
AnnMarieDavis, you tested on Pilot Dev (3.217.25.10) but Carney's fixes are still only on Original Dev (52.23.182.152).

**Comment by KSmithO** [comment]
She has the right link now!

Thanks,
Kristen Smith| Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 774-0382;  (202) 578-8845
Email: Kristen.Smith@associates.hq.dhs.gov<mailto:Kristen.Smith@associates.hq.dhs.gov>

DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/>
 Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If  the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this in error, please reply immediately to the sender and delete this message.

**Comment by Tonylayton1** [comment]
This has been updated and verified on dev

**Comment by Tonylayton1** [comment]
I see in a comment way above and noticed the suggestion to move the header text out of the iframe as well. Should we do this? There are no scripted failures tied to this particular header so it shouldn't trip up students if it remains in the iframe, but moving it shouldn't be difficult.

**Comment by AnnMarieDavis** [comment]
The language fix is verified.

If this page is also used to test for Topic 10 Structure, it would be better if the header can be moved outside the iframe. I thought I saw that it was outside of the iframe when I was testing tables. If this page is unique to language, no change is needed.

**Comment by Tonylayton1** [comment]
It is also used on topic 10, so the header should be moved out of the iframe

**Comment by mikebarklage** [comment]
"Advantages of Certification" has been moved.

**Comment by Tonylayton1** [comment]
verified

**Comment by drewnielson** [comment]
verified on dev
