### ISSUE TITLE
12D for incremental is not correct

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#95]
Per test process, do not test iframes that have a negative tab index. This answer should be DNA but it is NC:

![image](https://user-images.githubusercontent.com/34742733/59225930-f5b74380-8b9f-11e9-8430-89804cfdce3f.png)
![image](https://user-images.githubusercontent.com/34742733/59225937-f8b23400-8b9f-11e9-9a47-8c8717454f69.png)

**Comment by drewnielson** [comment]
Agreed. I think the tabindex="-1" was added at some point to avoid a visible focus issue, but that definitely affects the result on this test. Just need to remove the tabindex attribute.

**Comment by mikebarklage** [comment]
Removed tabindex attribute on Dev, waiting for approval.

**Comment by Tonylayton1** [comment]
Verified on dev

**Comment by AnnMarieDavis** [comment]
This negative tab index is fixed. 
However, I'm not sure I agree with the required answer for 12.B when I took this test (see visual above). 
The first expected answer of "The Page Title does not distinguish itself from the other pages in the web site" is for when two or more pages share the same Page Title but obviously the content would be different. In the example provided for students, this would apply if a couple of pages were titled "Workforce"  
Please REMOVE that as an expected response. The correct answer required should be ONLY "The Page Title does not accurately reflect the contents of the page."

**Comment by drewnielson** [comment]
Agreed with @AnnMarieDavis about the 12.B response in this case. Remove failure option: "The Page Title does not distinguish itself from the other pages in the web site."

**Comment by mikebarklage** [comment]
Tony - I dropped rO_16 from the answers for 12.B as requested. Both answers are still listed in the documentation, though.

**Comment by mikebarklage** [comment]
Just to be clear, here is where we're at on Topic 12:

No page title:
False for 12.A - rO_14
False for 12.B - rO_15

Page title exists but is unclear:
True for 12.A
False for 12.B - rO_15

Does that work?

**Comment by AnnMarieDavis** [comment]
I reopened the Workbalance web pages:
Page title (12.A) is True when "About"  and "Request an Audit" are displayed, but False on "Data" page.
A clear title (12.B) is True for "About" but False for "Request an Audit" and "Data" pages

**Comment by Tonylayton1** [comment]
Verified on dev and documentation is updated. Student will now see one of the following options:

page title is "Workbalance - Data" = compliant for 12.A and 12.B
page title is "page 2" = compliant for 12.A but NC for 12.B for rO_15
page title is missing = NC for 12.A for rO_14 and NC for 12.B for rO_15

for reference
rO_14 = A page title element is not defined for the webpage
rO_15 = The Page Title does not accurately identify the contents or purpose of the Web page.

**Comment by AnnMarieDavis** [comment]
I'm still not getting 12.B correct.  

- About tab - Page title is "Workbalance" = C for 12.A and 12.B

- Data tab - Page title is missing = NC for 12.A and 12.B

- Request an Audit tab - Page title is "Workbalance" = C for 12.A and  NC for 12.B

ON the answer sheet I marked 2 checkboxes:  The page title does not accurately define the contents... and The page title does not distinguish...

The option for A page tile is not defined should be marked for 12.A, not for 12.B.  
Second try
- About tab - Page title is "Workbalance" = C for 12.A and 12.B

- Data tab - Page title is Page 2= C for 12.A and NC 12.B

- Request an Audit tab - Page title is "Workbalance" = C for 12.A and  NC for 12.B

ON the answer sheet I marked 2 checkboxes: A page title element is not defined; The page title does not accurately define the contents... and The page title does not distinguish... 

The checkbox for _A page title element is not defined for the page_ should ONLY be selected as an option when testing for 12.A.

**Comment by AnnMarieDavis** [comment]
Because Workbalance is used twice for two different web pages, the answer sheet should also be requiring "The page title does not distinguish..."

**Comment by Tonylayton1** [comment]
Mike, for some reason the other 2 pages "About" and "Request and Audit" are not showing a compliant page title. both of them just say "Workbalance". let's ensure these are both always the full title "Workbalance - About" and "Workbalance - Request an Audit" so that any 508 issues are found on the page being tested "Data"

**Comment by mikebarklage** [comment]
Removed page title randomization from About and Request pages, now always displaying compliant page titles.

**Comment by Tonylayton1** [comment]
verified. the other 2 pages are now always showing the correct page title, so that the "Data" page title can be clearly evaluated.

**Comment by drewnielson** [comment]
verified on dev
