### ISSUE TITLE
Nice to have-have Course survey open in a new tab

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#99]
Using the course survey is a bit clunky since it opens in the same tab by default, and once you complete the survey, you either have to hit the "backpsace" button a couple of times or re-open the training URL.

**Comment by drewnielson** [comment]
Modified survey link to open in a pop-up window.

**Comment by katbecker** [comment]
Sorry: I corrected the link, but hadn't yet compared settings to those on the Standards Course. On that course we added " - Opens in New Window URL" to the link. Andrew has fixed the new window bit, but do you want this here, too?

**Comment by drewnielson** [comment]
Oh, yes, let's add the "opens in a new window" text as well
